### ISSUE TITLE
Specialized storage buildings

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#103]
### Expected behavior

- Split off storage of certain goods to other warehouse-type buildings
- Workers take goods to specialized storage

#### Specifications

- Granary for wheat/crops
- Larder / Smokehouse for meat
- etc.
- ldtteam/minecolonies#3797

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by ShadowProtocol** [comment]
#30
