### ISSUE TITLE
 I would love an additional line to the mouseover tooltip of my resource scrolls to indicate what builder the scroll is assigned to.

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#120]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [ ] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version:
- MineColonies Version:
- Related Mods and Their Versions:

### Expected behavior

 I would love an additional line to the mouseover tooltip of my resource scrolls to indicate what builder the scroll is assigned to. Bonus points if it works with Waila/Hwyla/etc if the scroll is placed in an item frame or similar, but not strictly necessary. If the item name could change (so it shows above my toolbar when mousewheel scrolling between items) that would be even more convenient, but I recognize that might be a bit more of a faff (or even impossible? I'm not a modder) to implement.
Alternately, a "book"/"binder" or "workdesk" to place resource scrolls and/or clipboards into to let you go through them (each one on a different page?) without having to search for which one is which would also work.

### Steps to reproduce the issue

1. 
2. 
3. 
4. ... Profit

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
A workdesk would be so cool! You could add clipboards and resource scrolls to it, and possibly also #77 and #78 (if they get implemented). Bonus points if it also has postbox and stash features!
