### ISSUE TITLE
Space wars tavern should play the cantina music (from Star Wars)

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies-features#125]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [ ] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.2

### Expected behavior

(From stream) The Space Wars Tavern, instead of playing the default Tavern music, should play the first part of https://www.youtube.com/watch?v=EsvfptdFXf4

#### Specifications

*

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Why Wontfix?

**Comment by Thodor12** [comment]
Regarding copyright laws this is probably too difficult to get right
