### ISSUE TITLE
Colonists are inactive when too far away

### ISSUE THREAD

**Issue by Nethet** [ldtteam/minecolonies-features#131]
# Prerequisites

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**
- [ x] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.2

#### Specifications

If you could do a thing thats not causing too much lag please, and that you can desactivate it in the config (that's obvious)

*

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by Nethet** [comment]
I wrote a whole paragrph that explaines the feature but it don't appear, so I write it as comment.
I have a bad PC, that's why i have a render distance of 4. And when I'm too far away of the colonists, they are inactive, that's annoying for going to sleep for example, or for the builder ect.
So could you add a feature that chunkload the entire village when the townhall is loaded, beacause if you go exploring you don't want to load the village (logic).

**Comment by MrMeender** [comment]
Just a quick solution for you: use command /setworldspawn in the middle of your colony. This way you'll make the chunks where you are and the chunks that extend by 10 in every direction spawn chunks. They never unload no matter how far you are.

**Comment by Nethet** [comment]
but it willbe always chunkloaded, isn't it ?

**Comment by ShadowProtocol** [comment]
No. Keeping that number of chunks loaded, especially on a server with several players, is just lag waiting to happen. Alternatives may be implemented in future to help your colonists keep working, but for now they will remain inactive when out of range.

**Comment by Nethet** [comment]
> No. Keeping that number of chunks loaded, especially on a server with several players, is just lag waiting to happen. Alternatives may be implemented in future to help your colonists keep working, but for now they will remain inactive when out of range.

Ok you're right with the server thing, it would lag as hell

**Comment by MrMeender** [comment]
> 
> 
> but it willbe always chunkloaded, isn't it ?

Spawn chunks are always loaded

**Comment by ravenbuilder934** [comment]
this was implemented as a config option btw
