### ISSUE TITLE
compatibility for the builder using quark

### ISSUE THREAD

**Issue by madlymercury** [ldtteam/minecolonies-features#132]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15

#### Specifications be able to use all quack chests

*

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by PowerSchill** [comment]
What exactly do you want the builder to do? Chests and/or racks are a part of the build schematic so the schematic designer designates what to use in a building.

**Comment by Raycoms** [comment]
Issue marked as stale
