### ISSUE TITLE
Streamline the display of resources in the Clipboard

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#140]
### Prerequisites 

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.125-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?

When viewing the clipboard to identify what resources are needed by workers "passive" requests  (fertilizer, armor, arrows, and smelter, etc.)  fill up the clipboard

## Enhancement or Change description

Remove "async" tasks from being displayed in the clipboard or place them on another tab. 

### Notes or related things

Proposed in [Patreon Discord](https://discord.com/channels/472875599422291968/473575384445878273/744991800883675298)

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This was implemented

**Comment by ravenbuilder934** [comment]
Was implemented
