### ISSUE TITLE
Change the Courier skills

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies-features#142]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 161 alpha (the Patreon modpack)
- Related Mods and their Versions: none

## Is your feature request related to a problem?
Not really

## Enhancement or Change description
To me, the Courier skills (Agility and Adaptability) don't make sense. A Courier doesn't really use Agility, and though Adaptability does make *some* sense (with the amount of pathfinding they do), I think they should be changed to Athletics and Stamina (or Stamina and Athletics). Athletics because they run fast, and Stamina for the amount they run (basically all day, at least in my colony).

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The current skills were set in a way to distribute skills nicely over different workers. They might not always fit 100%. Selecting skills is complex because there are secondary skills and negative skills too.
