### ISSUE TITLE
Setting for multiple taverns in the config

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies-features#144]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: v2.1 of the MineColonies Official modpack
- Related Mods and their Versions: none

## Is your feature request related to a problem?
no

## Enhancement or Change description
Since there's an option in the config to have multiple warehouses per colony, it would make sense to also have an option for multiple taverns.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Multiple taverns are not gonna happen
