### ISSUE TITLE
Warehouse item levels scroll

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/minecolonies-features#145]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version. (i update about every week or so)
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15

## Is your feature request related to a problem?
having to run back to warehouse to check on stock levels

## Enhancement or Change description
similar to the scroll item used to monitor the progress of the builder, it would be really handy to have a scroll like item to see warehouse levels at a glance and how much space in item slots is left how of total item slots.
bonus points if you can request to have a delivery person come to you with stuff, but i can see that being a challenge from just pathing alone.

### Notes or related things
not other notes.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ShadowProtocol** [comment]
Covered by #78 

Also check out the Stash and Post box - they fulfill the purpose of that "bonus" feature well enough.

**Comment by LuckyFalkor** [comment]
i guessed that would be the response to the bonus bit.
i did not see another request that matched mine, sorry for the duplicate.
i see there was a general warehouse one, but it did not have what i was looking for included.
