### ISSUE TITLE
Guard summoning item/structure

### ISSUE THREAD

**Issue by bugSandwich** [ldtteam/minecolonies-features#148]
- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

- Minecraft Version: 1.15.2

To eliminate the tedium of having to run between guard towers before a raid to get the town's forces to follow you, can a tool or buildable structure be added that makes all the town's guards follow you or unfollow you (and continue their regular/default function). This would eliminate the need to go between towers to change the guard behaviour manually before and after barbarian raids.

This could be done via an item which would be used to switch all guards between default and following behaviour (maybe a battle horn?) or done via a structure, like a town bell, that would perform the same function.

**Comment by ravenbuilder934** [comment]
You just described the rallying banner 😛

**Comment by bugSandwich** [comment]
Sorry, I didn't know that it existed. I couldn't find it on the wiki and had never seen it before. My bad

**Comment by ravenbuilder934** [comment]
No problem. The wiki is still WIP, as the devs add new features too fast for us to keep up!
