### ISSUE TITLE
Compost-able Eggs

### ISSUE THREAD

**Issue by Rosethorns** [ldtteam/minecolonies-features#150]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: minecolonies-0.13.288-PERSONAL-universal

## Is your feature request related to a problem?

Eggs are a common compost item in real compost, it seems a shame that we cannot compost eggs currently.

## Feature description

To allow the Minecolonies Compost to compost eggs

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by OrionDevelopment** [comment]
This is doable either via a data pack or via the config. Depending on version.

**Comment by ravenbuilder934** [comment]
Added
