### ISSUE TITLE
Add the possibility to move the home.

### ISSUE THREAD

**Issue by WaldeckTBD** [ldtteam/minecolonies-features#153]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: All
- MineColonies Version: All

## Is your feature request related to a problem?

No.

## Feature description

Add the possibility to do "/mc sethome" for change the home point to any part of the colony.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Closed because unclear what "the home point" of a colony is
