### ISSUE TITLE
Proposal for revision to child system

### ISSUE THREAD

**Issue by Rhea** [ldtteam/minecolonies-features#161]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.271-ALPHA
- Related Mods and their Versions:forge-31.2.41

## Is your feature request related to a problem?

Frustrations are having the average attributes of your citizens lower over time in the majority of cases. This is unrealistic, and more importantly, unenjoyable.

## Enhancement or Change description

A better solution to the current 'breeding' system (in my opinion), and one I believe would be relatively easy to implement, would be for 'parents' to produce a 'child' with attributes equal to the average of the two 'parents'. This value could then be given a random modifier of, for example, -2, to +2. This would however eventually and passively produce an equalisation of attributes across all citizens with progressive generations. The proposed system could be further improved with some minor added complexity by only averaging some of the 'parents' values, for example, the highest 3 and the lowest 2, and then randomising the others in some manner.

This would also mean 'breeding' your citizens would be an aspect of the game and the choice of where a citizen sleeps is something that can be managed to produce a specialised child, and so giving the mod/game more optional effort/reward steps.

The happiness of the colony, or indeed preferably the happiness of parents could instead be used to determined how often they attempt to produce a child, with happier parents producing one more quickly.

The player experience of those who would dislike this added effort would not be negatively affected still, as the average attributes of a passive breeding colony would remain mostly constant over time, rather than gradually lowering as it does now.

### Notes or related things

Thank you for the effort you've put in to this mod so far. 

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Was implemented, https://github.com/ldtteam/minecolonies/pull/5862. This issue can now be closed
