### ISSUE TITLE
Button to make the farmer only request compost (or bone meal)

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies-features#166]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.15
- MineColonies Version: MineColonies Offical pack

## Is your feature request related to a problem?
My Farmer is always using up my bone meal when I want to save it for my dyer. (I have several stacks of compost in my warehouse.)

## Feature description
On the 3rd page of the Farm hut, it would be nice to remove the button to turn off all fertilizer requests and instead have 2 buttons, one for turning off bone meal and one for turning off compost.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
With other mods, it might make sense to make it a filtered list,  but yes.

**Comment by warning-djkajslh** [comment]
Wait its been here since Oct 2020 and it still left untouched?

**Comment by ravenbuilder934** [comment]
mmhmm. When there are 265 suggestions, plus other features and bugs to fix, not all of them get done fast.

**Comment by warning-djkajslh** [comment]
I know, but isnt this issue a good first issue type?

**Comment by ravenbuilder934** [comment]
It is now! :P 
(I forgot to mark it.)

**Comment by Thodor12** [comment]
This is possible now with the warehouse master research (fullfill requests based on warehouse stock levels)
