### ISSUE TITLE
[suggestion] forester can shear Vines off trees

### ISSUE THREAD

**Issue by ziba1** [ldtteam/minecolonies-features#173]
Prerequisites:

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

 Context:

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.335

Is your feature request related to a problem?
The jungle structures use a lot of vines, a lot of time is spent harvesting them, which as the lord mayor of my sprawling village, is an outrageous notion :P 

Feature description:

Toggleable option for the forester to be able to shear and harvest vines

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Maybe have the farmer do it, or the plantation? Forester seems a little weird imo

**Comment by ziba1** [comment]
> Maybe have the farmer do it, or the plantation? Forester seems a little weird imo

Forester is already dealing with trees anyhow, seems more logical it would fall in his domain, plantation could work, but that has to be unlocked doesnt it ? For the sake of any jungle builders it would be better to be available early game imo
I dont see why the farmer would be involved

**Comment by Thodor12** [comment]
This logic is going to appear in the plantation
