### ISSUE TITLE
Wool to string recipe for the fletcher

### ISSUE THREAD

**Issue by AkGamerRo** [ldtteam/minecolonies-features#177]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.354-ALPHA

## Is your feature request related to a problem?

Guards(Archers) and fishermen require somewhat constant supply of string to function, which is hard to get in the early game.

## Feature description

* add a balanced recipe that turns wool into string to the fletcher

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
This already exists, 1 white wool block -> 4 string. This recipe is automatically available at the fletcher when you build it, along with a 3 gravel -> 1 flint recipe.
