### ISSUE TITLE
Suggestion: A Permanent World

### ISSUE THREAD

**Issue by PIPPIP5789** [ldtteam/minecolonies-features#185]
I have always loved Minecolonies, but have been steered away from playing on the server because I don't feel like spending months on creating a town, only to see it wiped at the next update/restart. I have played on a server that has a very unique way of doing their world - they never completely reset it. They will regenerate little sections that have been completely wiped out or griefed, and they will regen anything that they are asked to (you know, assuming it's not someone else's land when they are active). This allows for a rather stable flow of resources into the world while keeping the majority of it the same. It has been online for over 8 years now and never had to completely regen the world. Ever. This makes for a very unique experience, one where you can build and build on a city for years, and you will still have that city for as long as you play.

What about the new updates that get released? Easily fixed; the server I shall continue to reference, as a working example, does a few things every update. For one, they expand the map, which not only periodically accommodates a growing playerbase, but also allows players to have access to newer builds. When the Ocean Temples were released, they expanded on the world by a couple thousand blocks, then went through and regened empty parts of the sea, allowing temples to spawn throughout the world. Two, they will go through and remove any troublesome items. Elytras, for instance, were very buggy when they came out, so all Elytras were removed from the world before allowing players to access it. Eventually they were patched, so there was a big event where you could buy Elytras, easily bringing them back into the world, but either way, they were removed by staff to prevent any bugs. I assume that some items don't merge extremely well with Minecolonies, so I assume this could be helpful. Three, every update there is a big announcement with fireworks and stuff, and the staff makes it well known ahead of time that the server is updating, allowing players time to prepare themselves for the coming update. For instance, when the server eventually gets the new update with the Target Block that completely changed how redstone worked, there will be at least a couple weeks, maybe months, of prep time. This will allow the players to modify and fix their redstone so that they can stay on the same world, even under slightly different rules, without the update posing an issue to any kind of redstone machines. It's like this for all updates.

I know that Minecolonies, on occasion, removes an item or entity with an update. Minecraft has done so as well (I feel old remembering some of the old stuff like Beastboy, but oh well XD). That might appear to break the world, but you'll simply have to give everyone enough of a heads up to prepare themselves for such an eventuality. You could have "Update Sneak Peak" videos to let players know what is going to happen in the upcoming updates, giving them the time they need to prepare.

As I mentioned before, resources have never been an issue. However, as Minecolonies does restrict you to certain areas (your towns), it could become tedious and cumbersome to gather ores and the like, not being able to reset the world. However, with single-chunk regeneration, this is easily avoided, simply clearing out a couple of chunks, asking for a regen, and beginning to mine the new area. However, as this may seem......... cheap, I also would propose the idea of multiple towns, allowing a player to go to new areas. One area can last a player years, as I have done with my own Singleplayer Minecolonies world (after all, charcoal works like coal in every way, shape, and form; iron farms give you iron forever, and diamonds.... well, that's why there's a time limit; other ores are similar, as long as you're willing to put in the time). Eventually, running our of resources could happen, but you should be plenty fine by that time. And, who knows? If you run out of resources in a certain area, that could help influence trading to occur between cities, allowing further player interaction, trade, and a bunch of other things I have lacked seeing in Minecolonies (personally, anyway). 

I could continue for hours typing about this, but I think I have covered the basics of why a permanent world would not only work, but be better than any terminal world. I urge you to think and consider the creation of a permanent world, one where players can spend years on, one where their kids and even kid's kids will be able to help on one day, one where players can know they've built something that will last for years upon years, a place to call home, a true Minecraft server.

Thank you, and I hope you have the best of days! (Sorry for the walls of text)

**Comment by ravenbuilder934** [comment]
When have we removed an item or entity? We make sure to save breaking changes for Minecraft major version updates.
Multiple colonies are implemented already (you need to use commands though). 
Regening chunks won't become part of minecolonies, as it's not part of the mod's core functionality.
I'm also a bit confused-this is a suggestion for us to create a permanent server? Or to make changes to the mod itself?

**Comment by PIPPIP5789** [comment]
Sorry.... I suppose I wasn't concise enough to make my point.

From what I understand, you make a Minecolonies world, and players play on it for months or years. After that time, it get's put to the backburner as the dev crew works on updates further and further from that version, until that world no longer has any work done to it. After that, it's only a matter of time until that world is either completely refreshed, wiped, and updated, or it is taken down so players can't play on it any longer. My suggestion is to create a world/server that is never refreshed or restarted.

All the extra text was me attempting to address possible issues with the idea, or reasons you might not like it.

**Comment by ShadowProtocol** [comment]
Not only does this require significantly more server maintenance, it also does not account for many of the spontaneous updates we add and changes that arise out of fixes, that often occur only a day or two apart. Good for players maybe, but inconvenient for devs and admins.
