### ISSUE TITLE
Only put out alphas

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies-features#188]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official pack v3.0
- Related Mods and their Versions: none

## Is your feature request related to a problem?
Lots of people use the releases or the betas and are missing out on bugfixes and features.

## Enhancement or Change description
If we removed all the old betas/releases, and only uploaded alphas to Curseforge, those people would need to use alphas-and if they're using alphas, they might as well use the latest.

### Notes or related things
Partially removes the need for #157 

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by OrionDevelopment** [comment]
Due to the way curseforge works this is not possible. Since certain launches will only allow none alpha builds.

Closing.
