### ISSUE TITLE
Compress items when dumping items into inventories

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#19]
# Prerequisites

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**
- [X] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.x+
- MineColonies Version: <latest>
- Related Mods and Their Versions:

### Expected behavior

When dropping items into inventories the worker should attempt to compress items into full stacks when possible. This should include the warehouse inventory as well. 

### Actual behaviour

When items are deposited into an inventory they are deposited into new inventory slots. 

### Steps to reproduce the issue

1. Manually deposit 24 saplings into the lumberjack inventory. 
2. Give 40 saplings to the lumberjack.
3. Assuming the lumberjack doesn't use any of the saplings, when they place the saplings in the hut's inventory they will place them in a new inventory slot instead of combining them.

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This is purposefully not done on warehouses because of the level 3 sort option, not available from the get-go.
For citizens I'm not sure if we want to do this as most citizens don't require much inventory space anyway, with exception for the builder.
But seeing as this is a very old issue I'll be closing this as this was also made back on a now unsupported version.
