### ISSUE TITLE
Blacksmith tridents

### ISSUE THREAD

**Issue by mklosowski** [ldtteam/minecolonies-features#190]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.x
- MineColonies Version: 0.13.399-ALPHA
- Related Mods and their Versions: n/a

## Is your feature request related to a problem?
No

## Enhancement or Change description
Allow Blacksmiths to make tridents. 

### Notes or related things
When a Blacksmith reaches level 20 or higher, they automatically learn a recipe for making tridents. The recipe could require 3 diamonds + 4 iron ingots, or something else suitable since the trident is rather powerful. As an alternative, the requirement could be for the hut block to level 4 or 5, but it makes sense for the Blacksmith to have enough ability on their own, to succeed in forging a trident.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
There are new guard types planned, however a colony should not be able to produce a loot item like this unless the guards actively manage to kill drowneds who are carrying one.
