### ISSUE TITLE
Better raids mechanics and fixing gameplay issues

### ISSUE THREAD

**Issue by silverwolf1793** [ldtteam/minecolonies-features#193]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15
- MineColonies Version: 0.13.291-
- Related Mods and their Versions:

## Is your feature request related to a problem?

No... kinda
## Enhancement or Change description

Hi!

First of all let me tell you that I'm a HUGE fan of your mod, I really love it, it added just the thing I always thougth was lacking in vanilla MC, and that's the main reason I want to talk about raids, which I know that it has been pointed but I would like to sugest some changes on the mechanics that would make it enjoyable because in its current state I had to turn them off even if I love them:

Difficulty

There is some progression, yes, but its lacking in depth, for that I mean, I have 28 people in my town and of those, 15 are guards inside 5 guard towers and a lvl 4 barrack, even if I'm in hard thats a bit excesive in numbers but it still doesn't matter, the guards get owned each raid, I understand that this its a tradeoff to avoid players cheesing the fight by themselves, but that its what I want to suggest onto how to fix it:

Just let them cheese it.... I know how it sounds but hear me out

You could make it so that if a player does more than 50% of the damage, each time they get out of the town there is a chance that a raid will happen and the longer they stay out the more likely, you could even fit it in the lore saying that "the raiders/pirates were watching the place and realized you are the only defense available so now that you have gone out, it's their chance", that would force the player to guard the town 24/7 which at the start it could be a viable solution as it makes you feel "powerful", kinda like "the boss is in the house", yet as previous issues have let you know having to be paranoid of attacks each time you get out becomes really annoying after a while, that should be more than enough incentive for the players not to cheese it and once your guards are doing most of the damage the number of raids should go down as the enemies "got scared" with only ocasional "bandids" (not raiders, I'll explain further down) forcing one or two tower guards to become hostile to them.

Now that would pose the problem of incentive, having no raids would make the players forget about the guards, that can be easily avoided if once in a very long while (every 30 days even 40), with warnings some days in advance (like 10 for example) and without the previous penalty to the player, a raid could happen tailored to kill lots guards, at least half unless the player advances in "tactics, habilities and resources", kinda like a "war".

Tactics

Now, the second problem I've noticed its that as raiders/pirates usually come from the same spawn point they get together and own the lonely single guard locked in his tower, that its an issue, it forces you to have the rallying banner at all times, so to avoid that we need "tactics", first of all, here we could have a distinction, police and a fully functional army, in this part I'll speak only of the army, first of all, the army should only live in the barracks and they should have priority of equipment pick up, starting at unenchainted iron, if you want an upgrade you will need to study "tactics" in a "military academy".

Also there its formation, at the ringing bell of a raid the army should be able to have a similar effect to that of the "rallying banner" for themselves, here it could be a set spot placed by the player or simply "group" close to the town but siding from wherever the attack will come, while the "formation" selected by the player would result in their behaviour, for example, "marching" formation would make them group and never engage alone while "persue" would let them scatter around before the scattered raiders get the chance to attack citizens.

This would force the player to think carefully of their tactics on big raids giving more substance to the colony defense.

Police

This one could give a bit more use of the tavern. Once you have one "tourists, visitours and merchants" could come around, if they buy something you get gold or if they sell something (like vanilla villagers) they cost gold, the thing its that once in a while one of them could become a "bandind" or a "criminal" by trying to steal or attacking some citizen, that could be the use of the guard towers, they are the police, they should ehem... "take care of the issue one way or another" and if you don't have police.... well people will NOT be happy... also just to make things a bit more spicy, you could create "domestic issues" and some kind of prison for the colonists themselves where you would have to wage the chance of them becoming bad citizens again, letting them out or depending on the crime chancing other citizens to hate you if you "take care of them" by becoming hostile to you, that would be abit harder to implement tho...

Resources

Now this one its really important as it will be the main incentive for the player to grow the colony, here its were we need the "military academy", while your soldiers are innactive they could have to "train", that should be a drain in resources, say, iron, food, medicine, etc...
The main reason for that its that after some level soldiers could become capped only being able to progress by training and once guards have become "veterans" they should keep training as their level could go down, just as in real life, a bunch of fat lazy soldiers would deal terribly with an enemy attacker....

### Notes or related things

I think this overrall changes, while somewhat extensive they should not be that hard to implement (compared to what you have already achieved with the mod :P) and would make combat so much more entretaining and rewarding, I'm myself a programmer and while I've never developed mods in modern versions of MC I would gladly help with this on my spare time if you need it.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Updating (you're over 100 alphas behind!) should fix some of the difficulty issues

**Comment by silverwolf1793** [comment]
> Updating (you're over 100 alphas behind!) should fix some of the difficulty issues

yea but its more or less the same issue, its not an issue of difficulty but an issue of gameplay, I should have explained it a bit better

**Comment by ravenbuilder934** [comment]
Military academies already exist, the archery and combat academy

**Comment by Geoffrotism** [comment]
I have to agree. I'm on a patch that's only a couple versions behind and the issue isn't the difficulty... it's how "fun" raids are. Early game I think they are perfectly balanced, but as the town gets bigger they lose their charm and just become "unfun" or "less fun". Some changes I think would be worth thinking about:

- Pay gold to delay the next raid
    - Either allow once per raid or allow infinite times with exponential cost growth.
- Have varying spawn distances. It's weird to me that a town with 100 villagers and surrounding walls could have spawns right up against the walls. Potential Fixes:
    - A research that increase the base min spawn distance.
    - As the Town Hall level goes up, increase base min spawn distance
    -  Make spawn distance more random, I'd love to be able to sit on the walls and see a group of enemies charge in from the distance.)
- Increase or make variable attack times. With increasing town size it would be nice to have more time to "prepare" for attacks.
   
As far as new features, I think adding in "siege weapons" would be awesome. Have a new enemy type of engineer that spawns in with the materials to make a single piece of siege equipment. I'm basically thinking a prefab building. Early iterations could have the siege equipment just be cosmetic. 

Just my 2 cents. And thanks for making such an awesome mod!

**Comment by Raycoms** [comment]
Was adjusted in 1.16 already
