### ISSUE TITLE
Building Viewer

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies-features#209]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.486-ALPHA-universal

## Is your feature request related to a problem?
No

## Feature description
It would be very helpful to have something that shows all the buildings in the Colony and their tier. If you have a few houses, for example, and one of them is not upgraded to tier 4, you can identify it quickly with this tool. Maybe incorporate a tp option to send you to the specific building.

### Notes or related things
Discussed on Discord on 1.12 and recently on 1.16 https://discord.com/channels/139070364159311872/741531022872674314/783717435068252170

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
The town map should be able to fullfill this functionality now
