### ISSUE TITLE
/mc colony raid-now should be allowed to choose the type of raid

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies-features#212]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.484
- Related Mods and their Versions:

## Is your feature request related to a problem?
none,i think

## Enhancement or Change description

well,as my colony grows,i am tired of barbarain or pirates.i want to try amazon or othes,but my biom(or others) didnt allowed me to do that.So i want to add a parameter after the [colony] element in /mc colony raid-now.that would be useful but not so difficult to make it come true.

### Notes or related things

if amazon and desert werent in game at present,then m srry for disturbing you.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You do have a small chance to get amazons/vikings/egyptians when you're in the wrong biome, but I agree that it would be nice to choose the raid type.
