### ISSUE TITLE
Display help message in chat reminding player about 'Pickup Block' button whenever the player 'Deconstructs' a building.

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies-features#215]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

Really?

- Minecraft Version: 1.16.4
- MineColonies Version: 513

## Is your feature request related to a problem?
It's not clear how to retain the level of a block, or even that it's possible. Frustration has set in now that I've destroyed two buildings unwittingly. 

## Feature description
Know all those orange help message that appear when first starting out? Add one that pops up whenever you deconstruct a building letting people know that the 'pick up' or 'pickup' or whatever (I haven't actually seen it yet) button exists.

### Notes or related things
Did I really have to type in the version numbers?

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moleculor** [comment]
Or, perhaps better, a message when the deconstruction is finished? Not sure which would be better, honestly.

**Comment by ravenbuilder934** [comment]
There's already a message when the builder has finished deconstructing a building iirc

**Comment by Moleculor** [comment]
There is a message informing you that the building has finished being deconstructed, but no message instructing/reminding you about the existence of the Pickup button. Unless that's another thing (like the help screen) that should have shown up for me but didn't.
