### ISSUE TITLE
Same illager patrol spawn protection that is offered in Vanilla Minecraft.

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies-features#217]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 513

## Is your feature request related to a problem?
I keep having illager patrols spawning in the center of my colony. In [Vanilla Minecraft](https://minecraft.gamepedia.com/Patrol)...

"Patrols spawn in any biome except mushroom fields and its variants. **If a player is too close to a village, patrols do not spawn.**"

## Feature description

This would be nice to have also apply to colonies. If the player is (whatever the vanilla distance/formula is) or otherwise in a position where a random spawn of illagers may drop the illagers inside the village, suppress illager patrol spawns around that player.

### Notes or related things

I've been getting patrols crazy frequently in this colony, and they've killed as many or more of my colonists than all other sources of death combined. 

And I just lost my first ever colonist *who just so happened to spawn with my IRL name* to a mid-day illager patrol spawning in the center of my village, right between my town hall and builder's hut. After 56 hours of play. I had JUST handed him some materials and was running to grab more, too. 😢 

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
![image](https://user-images.githubusercontent.com/63612548/103015564-47b38600-4506-11eb-8541-e8b7b85552fe.png)

**Comment by Moleculor** [comment]
So keeping in mind that I've been told quite bluntly that this mod is balanced around Vanilla Minecraft...

Why is this *not* a problem?

...are we supposed to just torch-spam our villages? Or line the streets with carpet, snow, and half-slabs? 

Because otherwise Pillagers can (so far as I can tell) *literally* spawn in a group of five right next to a colonist and kill them in less than a minute, and the *first* notification you get that something is even wrong is a death notification. 

Worse, colonists are not as smart as villagers, and do not know to even run away *until* they start taking damage.

That feels like a problem to me. It was a bad enough problem for Mojang they specifically disallowed spawning of illagers within vanilla villages, where villagers are already smart/responsive enough to try to run from pillagers *and* have auto-spawning large-hit-box guards. Colonists do not have these advantages. Are we supposed to just convert our colonies to also utilize vanilla villagers just to offer a measure of protection?

**Comment by pwaksman973** [comment]
That is very annoying indeed, specially if you have more types of illager patrol and raids...
They spawn in the middle of the colony, go in a murder spree, absolutelly no chance to defend until some guards finally get there.

There are already mods for it like "https://www.curseforge.com/minecraft/mc-mods/minecolonies-pillager-patrol-fix" and "https://www.curseforge.com/minecraft/mc-mods/minecolonies-raid-fix" but those are weird and cause lag even when eating...

It would be very valid for the colony to handle it itself instead of passing to a third part
