### ISSUE TITLE
Trash System

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies-features#219]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.521-ALPHA

## Is your feature request related to a problem?

No.

## Feature description

Sanitation and garbage disposal was an issue in medieval times, causing disease when it was not taken care of properly. MineColonies does not currently have a system that mimics this.

* New item: Trash.
  * Unstackable, unburnable, completely useless except to clog up inventories, not pick-up-able by couriers (Can by players, but hoppers?). 
  * Generated by other workers at some rate in their inventory/hut block. More trash -> higher chance of a worker getting sick.

* New worker: Sanitation worker
  * Removes trash from hut blocks and takes them to the sanitation hut block for disposal. 
  * Higher levels = faster removal/carry more pieces of trash

* New research: Reduce, reuse, recycle!
  * Lowers rate of trash generation by x%.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
More suggestions in https://github.com/ldtteam/minecolonies/issues/1635

**Comment by Thodor12** [comment]
Closed because of mentioned issue
