### ISSUE TITLE
Suggestion: Customizable message for players entering colonies

### ISSUE THREAD

**Issue by ziba1** [ldtteam/minecolonies-features#230]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.537  Alpha

## Feature description
There is a default message to other players entering your colony, it would be nice if you could do your own custom message, maybe via the townhall gui, to either welcome other players, or warn them off, or give them some brief information

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by OrionDevelopment** [comment]
Minecraft has resourcepacks for this.
The messages are pulled from the language files.
Any resource pack can replace the string displayed.

See the minecraft wiki for how to make resourcepacks.

**Comment by ravenbuilder934** [comment]
@OrionDevelopment Would this work per colony?

**Comment by OrionDevelopment** [comment]
No and due to limitations in the way MC currently handles this, making this controllable via the UI, while keeping translations for the default will be not a trivial trick.

We might reopen this in the future to a server wide level, but this is already achievable today with resource packs, so I see no use there.

I am not saying we should not potentially reopen this, but for now I think this should stay closed.

**Comment by ravenbuilder934** [comment]
We have a wontfix label, should we reopen the issue and apply the label? Closed issues are more for fixed/implemented things

**Comment by OrionDevelopment** [comment]
Nah leave it closed anything that is open would indicate an issue that is still to be processed. As of now this is not.
