### ISSUE TITLE
tavern worker

### ISSUE THREAD

**Issue by Captain-William11** [ldtteam/minecolonies-features#233]
I would like to add a tavern worker which cells beers and different little foods like crisps. The currency that is already in the game to buy the beers like a little economy type situation in the tavern.

William.

**Comment by ravenbuilder934** [comment]
1. Please fill out the template
2. More general economy/trading is planned (if the player would be buying this)
3. Leisure is planned (if the citizens would be buying this)
4. Probably won't implement beer, it'll stay family-friendly
