### ISSUE TITLE
feature request: optionally filter open requests by 'Resolver: Player'

### ISSUE THREAD

**Issue by Spongman** [ldtteam/minecolonies-features#237]
there's currently no obvious way to look at a builder (or their hut) and see which resources they need that can only be provided by the player:
- the "Required Resources" tab in the hut shows in red _all_ missing resources whether or not they can be provided by other citizens.
- the "Open Requests" tab in the builder shows _all_ requests including those that can be fulfilled by other citizens. in theory you can scroll through that list and look for entries that don't have dependent requests, but it would be much simpler if there was a checkbox: "filter by Resolver: player"

**Comment by ravenbuilder934** [comment]
That would be the clipboard. (It includes player requests from all citizens, however.)

**Comment by Spongman** [comment]
ah, ok. so there are 3 different places to look for information? makes sense.

**Comment by ravenbuilder934** [comment]
They're for slightly different things, but yes.
