### ISSUE TITLE
Mail Man!

### ISSUE THREAD

**Issue by AcrazyD** [ldtteam/minecolonies-features#241]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: MC 1.16.4
- MineColonies Version: 0.13.437-release

## Is your feature request related to a problem?
 Not directly, more related to the lack of mods for what I'm needing exactly

## Feature description
 I want there to be a "PostMan" job (the name is bound to vary) that can be made to allow towns to mail things from town to town, This needs to be a timed system, maybe calculated based on how far the other town is from the sender - or based on a time value, either of which needs configs so modpack makers can make the delay longer or slower

### Notes or related things
 I'm working on a mod pack that is based around this and Create, and the Main Idea of it is, we have eliminated the usage of Teleportation outside a few select cases, and we are trying to find a Cross world mail system that isn't instant, and still sends things over 100k blocks away.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Trading is planned which will include interactions like this between colonies. Also FYI:

> MineColonies doesn't use the traditional classifications (alpha, beta, release) as the entire mod can be considered in a beta state (just based on the number of features still planned). However, Curseforge limits the number of releases and betas we can push out, and due to the devs' speed, the latest version will most often be an alpha. One classification is as stable as the others, so always get the latest version of MineColonies, regardless of its classification.
> 
> Because Curseforge hides alphas in the sidebar, you need to go to the Files tab and then View All to see them. Here's a quick link: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all

There are a lot of new fixes and features in the latest alpha 😄
