### ISSUE TITLE
Interchangable vertical/horizontal barrels

### ISSUE THREAD

**Issue by WrongWeekend** [ldtteam/minecolonies-features#243]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.566-ALPHA
- Related Mods and their Versions: N/A

## Is your feature request related to a problem?
Minecolonies' horizontal/vertical barrels use the same crafting materials, but in a different pattern, so they should be interchangeable in some way. This is especially the case if you have a surplus of one type but need more of the other type.

## Enhancement or Change description
Allow horizontal barrels to be crafted into vertical barrels and vice versa.

### Notes or related things
N/A

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by jzisser9** [comment]
This seems like a great idea, especially since all of the patterned wood and cobble blocks are interchangeable.
