### ISSUE TITLE
Suggestion: Need a better support for Eastern name order

### ISSUE THREAD

**Issue by HJ-zhtw** [ldtteam/minecolonies-features#244]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: NA
- MineColonies Version: NA
- Structurize Version: NA

## Problem description

Although that Wiki says we the user can customize the citizen names, offering the template like Japanese, we are not able to change the name order.
Not like the Western people's name, naming in Eastern cultures like Chinese, Japanese, Korean, or Vietnamese name is like surname+forename, and we don't have a space between them.
Please refer to: [Eastern name order - Wikipedia](https://en.wikipedia.org/wiki/Personal_name#Eastern_name_order)

It would be **great to make this change**.
### Notes or related things

I'm here to share the Chinese names (in Taiwan) template with every players!

[Download link (Mega)](https://mega.nz/file/jQ5CmapQ)
Key: `3T2bZOMTlJ_m5R5SsvH8dXgoYOX6wH_uwXJWH6zVBao`

The data I used was published by "Dept. of Household Registration, Ministry of the Interior. Republic of China(Taiwan)" in Oct., 2018.
* Top 100 Last name used in Taiwan
* Top 100 male & female name used in Taiwan
* Top 10 male & female 單名 used in Taiwan (I don't how to put "單名" in English, sorry.)
* Top 5 compound surname used in Taiwan
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Hey! Not strictly related, but can I put that template file on the wiki? (Credit to you of course.)

**Comment by HJ-zhtw** [comment]
> Hey! Not strictly related, but can I put that template file on the wiki? (Credit to you of course.)

Sure! :)

**Comment by ravenbuilder934** [comment]
Should be up within a few minutes 😄

**Comment by gattsuru** [comment]
I'm not sure 單名 has a named equivalent in at least American modes of speech, [if this discussion is accurate](https://forum.wordreference.com/threads/%E4%B8%A4%E4%B8%AA%E5%AD%97%E7%AC%A6%E7%9A%84%E5%90%8D%E5%AD%97.3747661/)  There's some parallel behaviors in a few Appalachian, African-American and Spanish-descended cultures, but they're not especially well-known, don't have the clear separation of a syllable count, and in the modern day tend to only show up in spoken form.

That said, colonists are generally (almost always?) referred to by their full name in an impersonal context, so I'm not sure how often the "can use two-syllable personal names among very close partners but not single-syllable ones" would come up.  Are there other norms regarding 单名?
