### ISSUE TITLE
Smarter Build Queues

### ISSUE THREAD

**Issue by dylan-cancelliere** [ldtteam/minecolonies-features#251]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.531-ALPHA

## Feature description

Smarter build queues. Rather than having builders start a build and then stay on it until they've completed the build or it gets cancelled, add an option that lets builders dynamically switch between builds if they run out of materials, or become blocked from completing the build for some other reason (maybe a tool broke or something). It would also probably require some way to view/modify the build queue from some centralized location, maybe the clipboard or town hall.

This supports two new use cases (that I can think of). Case one is that I can go around my colony and add upgrades to the queue for all the buildings I want to be upgraded in the near future, without having to plan out the order and ensure that my buillder has enough tools, materials, etc. The benefit of this is that if you're playing with other mods, or for whatever reason you're going to mostly ignore your colony for some time, you won't have to worry about builders getting blocked and doing absolutely nothing because they ran out of dirt or something, as they will move on to complete other upgrades/construction that you have enough resources for stockpiled in the warehouse.

Use case two is that if you need some absurd amount of a resource that one of your other citizens can produce but might take a long time to make, you can add that upgrade to the queue without worrying about your builder being blocked until you've produced enough of that resource. At the same time, once you have enough of the resource, the builder will eventually get around to the job, without you having to manually monitor your resource levels. An example of a situation like this could be that maybe you have everything you need to upgrade your town hall except 1000 oak logs. You have your forester chopping down oak trees and when he eventually gets enough, your builder will begin work on the town hall, without being unable to do anything the entirety of the time that the forester was working.

### Notes or related things

I'm not exactly sure how the current 'build queue' works in its current form, or even if it looks like a queue at all on the backend. But, this would be a really nice QoL feature that helps automate another aspect of the mod.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Goten87** [comment]
i idea for this is there is already a cancel button in the town hall a build now button will be nice there to when we press it it will pop a new screen with all the builds (name & current build task or idle) then we can select a builder even one thats working on a other project already that way we can let them build other projects more easy then to cancel a project and then rebuild that project again

**Comment by FurizuTenshi** [comment]
To add on to this perhaps, builders should just automatically seek and build anything you place in the town. Give us the option to set a priority on buildings high medium low, when they can't build something they are working on because of lack of materials AND none deliverable from anywhere, they work on the next thing they can find with lower priority. I'd love a reason for more than one builder. Doubly so if they work together on the same project to make it 2x faster

**Comment by ravenbuilder934** [comment]
> Doubly so if they work together on the same project to make it 2x faster

Already suggested multiple times, but would be *very* hard to code. You could have each builder build half, but flowing water in the schematic would mess that up.

**Comment by Thodor12** [comment]
This is not going to happen, too difficult to code in. The progress of a construction is kept within the specific builder their AI, not in the work order, only the general stage is kept there.
If the builder would drop the request to go and work on another one he'd have to release the work order so someone else can pick it up, but that would essentially void all progress on the construction.
