### ISSUE TITLE
Warehouse Sort

### ISSUE THREAD

**Issue by LordNavarre** [ldtteam/minecolonies-features#254]
- Minecraft Version: 1.15.2
- MineColonies Version:0.13.562alpha
- Related Mods and their Versions:

Please, on the warehouse sorting tab, either make it so we can click to or simply make it so it always is where
the warehouse sorts and fills the 1st floor first.

**Comment by ravenbuilder934** [comment]
Fill out the template

**Comment by Justen-N** [comment]
Actually, this should be closed in favor of adding a comment to #114  or #187
