### ISSUE TITLE
Outposts. 

### ISSUE THREAD

**Issue by kill23445** [ldtteam/minecolonies-features#258]
### Prerequisites 

- [?] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.566-ALPHA-universal

## Is your feature request related to a problem?
 No

## Feature description
 
- First recommend using supply ships & supply camps to supply outposts with resources provided by the main colony.
- Possibly 1-4 types of outposts all researchable. Such as Resource camp military outpost exploratory ect
- It should create large outpost area and only protect the building itself to prevent people from mass claiming everything
- Exploratory could cover things like mining wood cutting
- Resource camp could be a extremely cheep and small so people can allow a few builders to build schematics for them
- Military outposts could be used to guard vital points for people. Optionally when hostile outposts are added you could super buff them and require a outpost to be build within 600 blocks of them for them to be attacked without their buff (This could prevent people from being cheaty and taking them out quick. The loot and their buildings could also be protected until all hostiles are dead or give up / offer to join your colony

### Notes or related things

Just more ideas related to adding outposts. An expansion to the original topic That was kind of  plain just asking for outposts. "

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#12 Post a comment here instead of making a new issue
