### ISSUE TITLE
Option to set which level of tools workers request

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies-features#262]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

I'm getting tired of my workers requesting stone tools when I have a decent supply of diamonds and sticks for diamond tools.
## Feature description

A way to set which level of tool they use, restricted to the maximum level they can accept.  i.e. level 1 can only be set to wood, stone or gold, lv 2 to anything lv 1 has along with iron, lv 3 same as lv 2 plus diamond, etc.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
discussed in discord
