### ISSUE TITLE
Village loading

### ISSUE THREAD

**Issue by kcinnay2** [ldtteam/minecolonies-features#264]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.437-RELEASE

## Is your feature request related to a problem?
My feature idea relates to a big frustration I have at the moment with this mod. The fact that I can't leave my colony and always have to babysitt it, without being able to leave my colony as it will get unloaded, it feels like a giant anchor which kinda holds you at place and for me at least slows down the game a lot, as I most of the time don't have anything to do at the shepherd etc, meaning no work will get done as he is not loaded.

## Feature description
So my feature idea is that you have the option to make the village completely loaded when you are inside it, why not make an item you can craft which acts as a clone of Steve and loads the colony for you, or make it an option in the townhall, to always keep you village loaded no matter the distance etc. This could be easily disabled for servers etc and the people who cant handle it can always just not enable it.

-> Hope everything in this post is in order, first time ever posting here

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment]
Closed in favor of chunkloading mods, see ldtteam/minecolonies#477
