### ISSUE TITLE
Method to allow couriers to discard unwanted items

### ISSUE THREAD

**Issue by Narcisism** [ldtteam/minecolonies-features#265]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.589

## Is your feature request related to a problem?

My warehouse and chests are frequently cluttered up with stuff I do not want or need. In particular, Pillager banners are a problem for me.

## Feature description

An item or block in the same vein as the Stash and Postbox, a Trash Can that can have a whitelist set for it. Anything on the whitelist that ends up in the warehouse or courier inventories will be brought by the Couriers to the trash can. Items in the trash can are deleted from the world forever, just like trash cans from other mods.
Bonus points if you can set it to only delete items once you reach a certain threshold of them in storage. For example "keep X amount of  cobblestone, after that send to trash can."

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment]
Closed in favor of #219

**Comment by ravenbuilder934** [comment]
(please post a comment there with this specific idea/addon)
