### ISSUE TITLE
Filter what ores are mined by the miner

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies-features#266]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.589-ALPHA

## Is your feature request related to a problem?

I have other mods that add ores, but I don't want the miner mining them when I have something like Mystical Agriculture to create ingots.
## Feature description

I'd like a way to filter what my miners should and should not mine.  i.e. if I want them to mine iron, diamond, redstone, etc. but not modded ores, they should do so.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment]
Closed in favor of #15 . Please check if your idea has been posted, and if it has, react to it with a thumbs up in order to avoid cluttering the request list.

**Comment by ravenbuilder934** [comment]
And in this case, it'd be useful to post a comment there with this usecase

**Comment by darthvader45** [comment]
Thanks, I've done so on #15.
