### ISSUE TITLE
Suggestion: Generated Colonies/Waring Colonies/More options to rule over your citizens.

### ISSUE THREAD

**Issue by Arcanamue** [ldtteam/minecolonies-features#271]
Hello! So, I've been enjoying the city building part of Minecolonies, and slowly building up my little kingdom. But, there is something missing after all is said and done and all your buildings are upgraded as much as possible. Eventually, keeping your subjects happy (assuming your someone like me and RPing this as a King and subjects sorta situation), starts to get repetitive and your city will eventually start running itself really. It would be a really cool feature in the future (granted its probably asking for a lot, though with what the devs have done so far, I wouldn't put it by their skill) to have more of a kingdom or government sorta function. I'll list a few thoughts to clarify what I mean:

-Adjust the type of "Colony" it is. Say you just wana run a little town to help you in your mining and stuff, you just wana be more simple, then perhaps an option to change what kind of civilization you're running. Or perhaps, if you want to get more in depth, then change it to a kingdom. 

-More ways of ruling over or managing your citizens or subjects as I like to think of them. Perhaps there are more consequences to ruling a poorly run city, more crime. If the environment changed  because citizens are leaving stuff around, or the city is not as guarded as it could be. I almost imagine a royal request sorta situation, maybe at your throne you can call a town meeting or something, and hear grievances at the castle one by one, and or more in depth requests or even sort of quests. This could tie into something i'll detail in a few minutes regarding waring kingdoms. 

-Wall Schematics- so far I haven't seen any thoughts on schematics for city walls? This would be a nice feature. I could be wrong if it was already recommended or is in planning, but that would be something that would excite me.

-Generated Kingdoms! Perhaps, and again, idk how this would go over, and maybe it could me an option for players when creating a world. But, if you could stumble upon big kingdoms or small colonies along your journeys. Like, not just villages where the dumb villagers basically do nothing. I mean, fully fledged cities that are generated with walls and such, to the smallest towns. And perhaps you could take over these colonies or work your way up in them (if you don't already have your own), and ultimately end up ruling it. Perhaps nearby generated kingdoms may venture off and show up at your gates wanting something, or offering something, or to try and extort.(obviously this sounds far more narrated than i would ultimately mean, idk how much would be possible on this end, but a generated event sorta thing kinda like the raiders function that exists now). And through this, one could declare war on another kingdom for whatever reason, even if it is incited by you if you're a greedy ruler and want more. Perhaps you could gather your troops and have a small army march with you into battle. (Now you and your people are the raiders of another colony). I know all of this is basically possible in multiplayer stuff, but it would be so cool for it to be possible in single player too. 

-More dialogue options with NPCs. This really coincides with my previous recommendation of more options of ruling over your subjects, and ik it's only minecraft, but I find much enjoyment from reactions. If you wear a crown or something, (which ik there are things like pharos's staffs or something), but perhaps depending on the ruling accoutrement you wear, the people will respond differently. If you're a king, then they might stop and bow or something, especially if they are happy and respect you. 

These are just a few of the possibilities I think could work great for Minecolonies. I may have missed a few previous suggestions that might say similar things. But this is just my two cents. Thanks devs for an awesome mod!

**Comment by ravenbuilder934** [comment]
Colony specialization is planned
- Generated colonies are planned
- War is planned
- Wall schematics already exist, build tool GUI -> decorations -> walls
- Crime is planned iirc
- Please create a new issue for the dialogue/new ways to rule/interactions (follow the template next time)

**Comment by Arcanamue** [comment]
Hello! Apologies for that. Is there a place I can look at the roadmap? THX!
:)

**Comment by ravenbuilder934** [comment]
The closest thing to a roadmap we have is probably a pin in `#mod-discussion` of our [discord server](https://discord.minecolonies.com)

**Comment by Arcanamue** [comment]
Cool, thanks!
