### ISSUE TITLE
Optimize housing button in Town Hall

### ISSUE THREAD

**Issue by FurizuTenshi** [ldtteam/minecolonies-features#274]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
Not really, it would just make it easier to maintain housing.

## Feature description
A button in the Town Hall that optimizes everyones housing based on work distance. Either this, or have Automatic housing do a check every morning to optimize it.

### Notes or related things
As always, thanks for the cool mod!

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dabros** [comment]
Followed all related links but cant see what happened with this

Was there any movement on this or way I can re-raise it?

Housing becomes a big issue past 50 colonists, becomes a manual time sink even on easy/med, and especially when you raise raid difficulty and lose non-guard colonists.

**Comment by Thodor12** [comment]
Manual housing is a choice, automatic takes the burden away from you. We have no intention to address this because we don't like max possible optimization. Not to mention that there are way too many variables to make an effective sorting algorithm.
