### ISSUE TITLE
Teaching recipes - Tell User who can learn it

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies-features#282]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

When trying to teach a recipe to a worker/building, in the event of an error caused by trying to teach the recipe to the wrong person, it would be nice for the chat message to tell the user which building/worked can be taught that recipe (if any can).

## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
What about a JEI extension showing which crafter can craft an item? Would it fulfill this?

**Comment by Geoffrotism** [comment]
As a user, I would like to have it be more immersive with something like:
> If I were to try to save a recipe at X worker and X tells me "I can't do that type of work, try asking Y". 
But adding the info to the JEI does solve the intent of this github issue so no complaints if you want to go that route.
