### ISSUE TITLE
Apiary Honeybottle and Comb simultaneously

### ISSUE THREAD

**Issue by ErikderFreak** [ldtteam/minecolonies-features#285]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.602-ALPHA-universal

## Is your feature request related to a problem?

One Apiary is enough to make all of the honeybottles and combs you need. 
Problem is that you have to switch it constantly.

## Feature description

A research like the "double trouble" (2 plants for plantation), but for the Apiary, so the beekeeper will use half the hives for bottles and the other half for combs would be nice.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Gonna wait until https://github.com/ldtteam/minecolonies/pull/6181 is merged to start on this
