### ISSUE TITLE
Blacksmith can create netherite armor/tools/weapons

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies-features#288]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.610-ALPHA

## Feature description

A way for the blacksmith to accept recipes for netherite tools.  Considering his later upgrades include smithing tables, that seems almost intended for something.  I say it's high time they got a use for the blacksmith.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
(or an easier route would be to add custom crafting recipes that only the blacksmith can craft)

**Comment by darthvader45** [comment]
Yeah.

**Comment by darthvader45** [comment]
Thank you so much.  Now I can finally get my guards automatically decked out in netherite gear and my workers using netherite tools.  Then I can rock the awesome netherite goodness with em.

**Comment by ravenbuilder934** [comment]
Oh nonono, the feature hasn't actually been added yet - it's still in review
