### ISSUE TITLE
New Building Idea: Storage Hut

### ISSUE THREAD

**Issue by BenWoodford** [ldtteam/minecolonies-features#290]
### Prerequisites

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context

- Minecraft Version: all
- MineColonies Version: all

## Is your feature request related to a problem?

No

## Feature description

"Storage Hut"

A workerless hut that acts as a mini-warehouse with a whitelist of items. Couriers would aim to keep x amount (user configurable) of that item available in the storage hut at all times, and will pull from the hut's inventory when fulfilling requests if it's more efficient than taking from the Warehouse or other building

Would be very handy not only for easy access to resources the player takes from the colony (ingots, etc) but also makes request fulfilment more efficient as couriers will not need to travel so far to get items.

As an extension, perhaps having couriers that are relegated only to a set of huts (or have a specialist courier as a worker for the Storage Hut) so that couriers aren't spread so thin fulfilling requests along the entire colony. An ores & ingots courier would supply to Blacksmith, Smeltery, etc.

### Notes or related things
N/A

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Post a comment on #30 instead
