### ISSUE TITLE
Townhall as "age-key"

### ISSUE THREAD

**Issue by GulliUlli** [ldtteam/minecolonies-features#291]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context  0.13.602-ALPHA

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.602-ALPHA

## Feature description
  The townhall will be set as a Masterhouse of your colonie, so it will be important to upgrade this, to unlock the next upgrades for you city huts. ( like the builderhut yet). but then the townhall can be one stage higher then all other huts. BUT you have to upgrade all huts minimum 2stages lower then the Townhall. for example: you want to upgrade the townhall on stage 4 so all your huts in the city have to be minimum stage 2 to unlock the townhall upgrade. If your townhall is stage 4 then you can all your huts up to stage 4. (the mechanics of the builder will be the same).

### Notes or related things

sry for my bad engish im german :D

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment]
This was formerly the case, but was removed as it was considered overly limiting.
