### ISSUE TITLE
Shift-based working colony

### ISSUE THREAD

**Issue by SinFlame** [ldtteam/minecolonies-features#292]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 610 Alpha

## Is your feature request related to a problem?

Not an issue. 

## Feature description

* Implement a feature whereby colonists work during night time.
* This will split 2 type of colonists, Day workers and Night Workers. 
* This will be more immersive and it would be great for the player to go exploring, while letting the guards settle on taking care of the mobs. 
* Feature can only be unlocked after research from University level 3/4 for balance
* If economy system gets added in the future, night workers are paid double, for balance purposes. 

### Notes or related things

I have been playing since 1.12.2,(skipped 1.13-1.15) and I have seen this mod evolve greatly, thank you so much for the hours of fun! 

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Post a comment on #261 instead
