### ISSUE TITLE
additional healers per hospital

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies-features#297]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version:

## Is your feature request related to a problem?

frustrating when you get an epidemic

## Feature description

Additional healer at hospital lvl 3.

### Notes or related things

https://cdn.discordapp.com/attachments/244066364573089793/810986305285914624/2021-02-16_08.29.23.png
https://cdn.discordapp.com/attachments/244066364573089793/810986471724548146/2021-02-16_08.30.32.png
https://cdn.discordapp.com/attachments/244066364573089793/810986407690108949/2021-02-16_08.29.09.png
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by asoshinsky** [comment]
Love the idea! I had kinda same issue once.

**Comment by Thodor12** [comment]
Likely not going to happen as this would require schematic updates to all buildings to include a new amount of beds.
The main factor of healing is the time that it takes the citizens to heal themselves.
The hospital only gives a slight benefit to this speed and distributes the items automatically.
Having multiple healers in the hospital won't affect anything.
