### ISSUE TITLE
Pathblocks as a config option

### ISSUE THREAD

**Issue by Imrielle** [ldtteam/minecolonies-features#304]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.638-ALPHA-universal / structurize-0.13.139-ALPHA-universal
- Related Mods and their Versions: Pretty much every mod that adds blocks and slabs.

## Is your feature request related to a problem?
No.

## Enhancement or Change description
Add the [pathblocks list](https://github.com/ldtteam/minecolonies/blob/version/1.16.3/src/main/resources/data/minecolonies/tags/blocks/pathblocks.json) as a config option for further mod compatibility and modpack maker support.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Do you mean making that list's contents a config option (so you can add or remove from the list in the config file)? Or a config option to enable/disable it entirely? Because the former can already be done with datapacks iirc

**Comment by Imrielle** [comment]
The first, yes, a config option to add to or remove from the list.

I didn't think of it being a datapackable option, I suppose I'm still too things like this being in a config file.

**Comment by ravenbuilder934** [comment]
I'm going to close this then since it can already be done with datapacks
