### ISSUE TITLE
Suggestion: Have builders ignore player-placed torches while building

### ISSUE THREAD

**Issue by Nyhilo** [ldtteam/minecolonies-features#308]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ x ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.643-ALPHA-universal

## Is your feature request related to a problem?
It's a known thing that builders fill fully clear out a space before they continue building. This of course leads to the situation where an area is completely dark and then builders die from spawned mobs.

## Enhancement or Change description
My suggestion is to add make two changes to the build algorithm. 

* First, ignore all torches placed unless they need to place a block there. This will allow players to place torches to try an mitigate the issue while the builder is working.
* During the build cycle where the builder is placing torches, include the removal of non-schematic-matching torches in this cycle.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Too difficult to keep this in mind, if torches are placed on a block that needs to be excavated then that block wouldn't be allowed to be removed which can bring unforeseen complications with the construction
