### ISSUE TITLE
Add Podzol to the composter.

### ISSUE THREAD

**Issue by hobnob11** [ldtteam/minecolonies-features#310]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 668

## Is your feature request related to a problem?

Some of the buildings (in the Asian style at least) require podzol in their construction, and there is no way for citizens to produce this.
## Feature description

I'd suggest a simple recipe, maybe with dirt and compost? or maybe dirt and a sapling since podzol is made by growing 2x2 spruce trees that probably the composter would start with that lets them convert dirt into podzol. 
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
It was decided to add a chance to also get podzol when making dirt. I'll work on this soon:tm:
