### ISSUE TITLE
Graveyard and Gravedigger

### ISSUE THREAD

**Issue by sboigelot** [ldtteam/minecolonies-features#311]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context

- Minecraft Version: 1.16.+
- MineColonies Version: 0.13.657-ALPHA+

## Is your feature request related to a problem?

When colonist die, they do not leave grave behind.
This issue in in currently in dev by @sboigelot at the suggestion of @Raycoms over discord
This issue aim to collect all todo related to the graveyard in a central location so I can keep track of them during dev. Feel free to comment with your own addition

### Planned

- [x] Add a new research to unlock the graveyard
- [x] Implement a new worker building: the graveyard
- [x] Implement a new worker: the gravedigger
- [x] When a colonist dies within the boundary of the colony, a grave tile entity is created a the death position. This tile entity ("grave") contains the inventory of the dead colonist
- [x] The grave has a de-spawn timer and will disappear automatically in two phase [default -> decayed grave -> despawn]
- [x] The grave will carry the citizen data for potential respawning and listing of buried in the graveyard
- [x] The goal of the grave digger is to collect graves, break them, and retrieve the lost items
- [x] Depending on the worker level of the grave digger there is a chance to bring the citizen back alive when digging up the grave (extremely low chance, maybe up to 10% max on max level, could be improved by research)
- [x] +bonus mytsite?
- [x] Add one or more research to increase the citizen grave de-spawn timer
- [x] Add one or more research to increase the resurection chance
- [x] Add stone/schematics for 5 lvl of graveyard

### Optional

- [x] Successfully collecting a grave could reduce the grieving period of other colonist - Retrieving a grave from a dead citizen divide mourning period by 2 (morning of the next day only instead of full day) (only if all dead colonist grave are retrieved)
- [x] storing a list of all citizen resting in peace in the graveyard

### Extra TODO:

- [x] Fix/New/integrate gravedigger citizen model --> Black clothes texture + researcher model?
- [x] Update decayed grave model 
- [x] Fix graveyard hut block model - shovel go behind the box & orientation item is incorrect
- [x] GraveBlock shouldn't loot graveblock item
- [x] update death message to include "grave has been created" if inside colony
- [x] add achievement for the first grave collected by the grave digger
- [x] add achievement for the first resurrection
- [x] Improve grave-to-dig next selection to select the grave closest to despawn
- [x] Adjust physic shape of block hut graveyard
- [x] make sure everything work with client&server, not just local client
- [x] The gravedigger should be immune to "mourning" so they can collect grave of dead citizen
- [x] Change "working" icons and text for gravedigger gui
- [x] Update and check all translations
- [x] Explicitly Transfer item from grave before digging it to be sure the grave digger collect them
- [x] Add information panel in BuildingGraveyard GUI
- [x] Validate that gravedigger is IDLE while no grave to dig - for now stuck on Working?
- [x] add enchanter to list of building gradigger visits
- [x] change EMPTY grave emptying inventory to explicit one
- [x] use the tag tool to tag location in the graveyard structure and spawn permanent grave entity on the correct location when bury citizen
- [x] add warning if graveryard inventory full --> but collect the grave anyway to bury, leave items on the floor
- [x] create a tileEntity for named grave when citizen are buried in the graveyard
- [x] create a custom tileEntity renderer for named grave with citizen name on it
- [x] Cleanup chin black pixels on some gravedigger texture
- [x] limit number of bury citizen per number of tag -> make more space in structure while building upgrade
- [x] Redesign lvl 2 to 5 stone schematic

## Notes or related things

* The graveyard was also discussed in the following issues:
* *  #155  
* *  #98

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by darthvader45** [comment]
Nice.  Not too OP, but decently useful if a colonist is somehow brought back from the dead.

**Comment by sboigelot** [comment]
Extra TODO:

- [ ] New/integrate gravedigger citizen model
- [ ] Update decayed grave model
