### ISSUE TITLE
Citizen that used player skins.

### ISSUE THREAD

**Issue by kihgy** [ldtteam/minecolonies-features#318]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
No

## Feature description
After a while playing with this cool mod, and look at some other community building mods, I got an idea, this idea was originated from Ancient Warfare 2 and MCA. 
What about citizens that run around while having player skins?
Yes I would love it to have player npcs run around, gathering stuff, auto crafting, deliver stuff, lastly, protect you, follow you around.
The method to change the skin could be survival or via creative, difficulty or not.
Player skin might as well be related with citizen naming, would be weird if I have a specific player with an odd Minecolonies name.

Aaaand it may not even be possible at all since all the citizens in this mod use custom models different from player model, like the courier, but some models such as guards are basically just player models

### Notes or related things
Might not be possible at all but I can hope for it. Great mod.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Like you said, most models are different so this won't really work. However, both models and textures can be changed with a resourcepack iirc

**Comment by kihgy** [comment]
Nooooooooooooooooo

**Comment by kihgy** [comment]
But knights and archers are basically just player models, they can even render armor correctly.

**Comment by ravenbuilder934** [comment]
Male builders too. But it'd look weird to only have those job types with player skins 😛

**Comment by kihgy** [comment]
Yeah but in my defense i will say that knights and archers are valid candidate for this, as they dont finicky about beds or houses or breeding as other citizens, the bed in the tower is just for decorative. I see it as okay for guards to have that ability, maybe for them to be able to change into a player skin you will need a special rare material, that way you can have guards that use normal and players, this is cosmetic and as the guard change jobs, it would revert back to default minecolonies skin and name?
