### ISSUE TITLE
I want to see citizens run around and interact with the town more rather than just doing work inside their structure all days.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#320]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
Despite my colony have a lot of citizen, it always feel as it is too empty, as all the citizens will just stand inside of their huts all days, even if they have nothing to do. The exceptions of this is Guards, Corriers, Farmer, Fisherman, Lumberjack and Builder. The only time when you can see people actually moving is when the go to work or return home.

## Enhancement or Change description
- I want to see citizens to do more than just stand still in their working structures all day, either to take a break, socializing, talk to each other, go to the Tavern/Restaurant to have fun, it you don't have guards or corrier running around, you can't get a living town feeling that well. The other idea is that it is I just want to see citizen's to have an additional need to relax, have fun, in my opinion, it will also make running across the colony more exciting, "oh, I see my researcher is taking a break, taking to a guard, etc..."
-  This request was inspired from Tektopia's happiness modifier with the Bard and Tavern, while Minecolonies does have a tavern, I can't see a point in adding in a Bard(lowkey hope for this as I like the music play in the Tavern), but maybe the Tavern could also be used as a place to hang out. Another inspiration is the vanilla villager's schedule and gossip at meeting, feel like they do actually alive and not just mindless npcs standing at their job site all day, and even villagers will wonder from their job sites during work hours. And baby villagers as well, they are better as being children as Minecolonies's , not because they don't  have to go to school, but because they are hyperactive and play with each other, running around in the village, actually playing games.
- In conclusion, my request is asking to make citizens to have the need for entertainment, leisure, social, making the colony to feel more alive and fun.
- Here are a few ideas of this socializing behavior:
+ When there is no threats around, guards have the chance to invoke in a conversation with someone, and both the guard and citizen will be increased in happiness depend on how well the guard fight monsters.
+ Unemployed citizens should seek to other citizens, or guard to see how well they are doing
+ Tavern: Should be used for leisure activities as well, the place to gather, exchange, gossip and ask about everyone's day, if the town is secured enough, people could even go to the tavern at night before going to sleep, citizens that live in the tavern have more chance to go to the tavern at night. In the day, guards, or other citizens may also want to stop by to have a few drinks.
+ I really love it if there could be a playground or park structure, this will not only attract children to play during their free time, but will also attract umemployed, to come and see children have fun, another hangout spot beside the Tavern.
+ Various childish behaviors for children, playing tag ;) , chase, talk to each other and emit green particles indicating they are happy.
[ ] Bard/Entertainer/Jester "worker": Increase the happiness and mood factor, play music for everyone to hear, come to the tavern or the park to see him perform, dedicated structure is the "**studio**?". You can even make call them to follow you, as you may also want to enjoy those funky medieval Minecolonies music as you work.

### Notes or related things
- Could you also improve the slow-walk wander AI that citizens shares with visitors? Make citizens to have more energy, go like normal when they wander.
- I know this feature will result in a decrease in efficiency, so maybe leisure time is configurable?

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by warning-djkajslh** [comment]
This request seems a bit to farfetch'd as it ask for the addition of a completely new and hard-to-code mechanic, but it is very worth it and I really want this.

**Comment by kihgy** [comment]
Oops, I was supposed tolabel thid as Feature Request

**Comment by ravenbuilder934** [comment]
#211
