### ISSUE TITLE
New health healing worker: Cleric

### ISSUE THREAD

**Issue by kihgy** [ldtteam/minecolonies-features#322]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Feature description
The cleric is a magical support worker for normal citizens or guards. The cleric will be able to create beneficial potions, and they can farm crops, in this case are Nether warts, and can create potions automatically. They can aids guards with regen or healing, guards will take at least 1 healing type of potion to carry with them. Alternatively, clerics can come and assist guards by throw them with infinite instant healing potion like witches in raid, and can also drink infinite potions themself. Clerics could also fight undead using instant healing, this is super effective against a horde of zombies.

### Notes or related things
Clerics inspiration was from Tektopia. That mean yes, if leisure is eventually planned then perhap the cleric can prepare drinks in the Tavern

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#181 for most of it, upcoming witch guard for the potion-attacking bit
