### ISSUE TITLE
Guard Patrol on Horses

### ISSUE THREAD

**Issue by SinFlame** [ldtteam/minecolonies-features#323]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Feature description

Guards will now patrol using horses, and they will "park" their horses outside their respective towers. 
Horse armors obtained can be utilized fully. 

This will also introduce a new building, called "Stables" where Breeders will breed horses and keep them well, if a horse is injured, it can be taken back to the stable to do "grooming" 

The higher the stable level, the better the armor it can equip and speed of the horse is increased. 

Initial unlocking should be done in the university, and horse health and speed can be increased on the research branch. 

This will however, need a downside, which will be Raiders using horse mounts with armor too. 
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#61 (post a comment there)
