### ISSUE TITLE
New Worker: Crafter

### ISSUE THREAD

**Issue by SinFlame** [ldtteam/minecolonies-features#327]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Some mod items cannot be crafted by any crafters. 

## Feature description

This is the ultimate crafter, who can be unlocked after getting ALL level 3 crafters (Blacksmitch, Fletcher, Glassblower etc etc) 
This crafter can CRAFT ANYTHING, provided you have taught the recipe.

This will help wiith mod compatibility crafting. 
They should come with a crafting table and furnace recipe. 

Higher levels yield higher recipes. 
 
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I'm pretty sure we'd rather allow the existing crafters to craft everything between them. (@Raycoms, can you confirm?)

**Comment by Raycoms** [comment]
Yep

**Comment by ravenbuilder934** [comment]
Wontfix exists :P

**Comment by SinFlame** [comment]
If that's the case, I'll close the suggestion. 
Lots of mod items cannot be crafted, but it's not really a big deal. Would love some automation and see the workers get to work on late game.

**Comment by Raycoms** [comment]
Everything is managed via datapacks, you can add datapacks to any worker to allow specific mod items

**Comment by ravenbuilder934** [comment]
And which mod items? We might be able to account for them
