### ISSUE TITLE
New feature: Release your citizen.

### ISSUE THREAD

**Issue by kihgy** [ldtteam/minecolonies-features#328]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
Currently there is no way to reduce the population beside death.

## Feature description
Add in the ability to remove citizens from your town, either to free space for children or to trade citizens with your friends. 
After released, the citizen will leave the colony, you can set it so that the citizen will go to a designated colony.
Travelling citizens will appear in the destinated colony at the tavern, if the owner changed his mind however, they could also send the citizen back to the original colony.
If you just want the citizen to leave forever, then upon releasing, they will change into a "visitor" and hang around at the tavern for a while after leaving, if you want to re-invite them, then you can do ot for no price at all. Once the reformed citizen left, they may or may not return to your tavern for a visit.
Maybe there should be a price for each trade/release as the citizen will be now without a colony, and venture the wilderness.
### Notes or related things
This feel a bit like slave trading.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Post on #54
