### ISSUE TITLE
Sifter's input and output should be configurable 

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#332]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
Seeing that the sifter is a way to generate resources on demand without actually working for it, I think the ability to customize the input and output of a sifter would make it so the mod will be even more relevant to use in modpacks.

## Enhancement or Change description
Add in a config folder for the sifter's input and output
The structure of the file will be as follow:
Material A (Input Material)      -      Drop A (Output)       -      chance (Rarity of this output)
Material A - Drop B - chance
Material B - Drop A - chance

That's my rough take on the file, as I don't know any more in-depth of the mechanic. By default, the config will have the default inputs and outputs only.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Sifter was recently changed, what version are you on?

**Comment by warning-djkajslh** [comment]
I am currently in 

minecolonies-0.13.660-BETA-universal.jar
--

**Comment by ravenbuilder934** [comment]
That's over 60 versions out of date, try updating

**Comment by warning-djkajslh** [comment]
Okay, closing this for now
