### ISSUE TITLE
Make it so you cannot damage citizens by punching or arrow

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#337]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
Citizens can be a hazard to friendly fire
When I make adjustment to my colony, decorate the colony, I have to be careful whenever a citizen pass through, not to punch them. This is also a problem when I am defending my colony at night at there are guards run over to help, and I hit them accidentally. When guards are follow you, they become invulnerable to you, why can normal patrol guard and citizens be like that as well?
Another note: if you accidentally hit someone, and you have overpowered pet accompany you, then they will maul the citizen.

## Enhancement or Change description
Citizens and guards are now immune to any type of damage from the player: potions, punching, arrows, trident...

### Notes or related things
Can still kill them indirectly via fire or lava.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
this was already implemented during raids (for guards). for the rest, you can disable "attack citizens" or so in the town hall permissions gui
