### ISSUE TITLE
New Worker - Armoury / Arsenal

### ISSUE THREAD

**Issue by BellePullman** [ldtteam/minecolonies-features#339]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.53

## Is your feature request related to a problem?
Warehouse overloaded

## Feature description
Move storage of weapons, tools and armour to a dedicated Armoury / Arsenal building; or use this to enhance the Blacksmith's role.  Armourer / Blacksmith can repair weapons, tools and armour.  All weapons, tools and armour stored in this building not in the warehouse, saves space in the warehouse, makes it easier to find the items, and if combined with Blacksmith, makes ordering stock more direct. Could also be used for Guards to swap out their worn equipment before it breaks and to upgrade their gear - guards interact directly with the hut rather than rely on a courier, similar to how citizens collect food from the restaurant.

### Notes or related things
Pros and Cons of expanding the Blacksmith vs creating a new Worker - Blacksmith already creates these items, but could potentially become over-worked with their maintenance as well.  Multiple Blacksmiths might make the storage problem worse not better.  New, separate worker increases load on couriers but does not add to the Blacksmith's work, new worker would be able to repair but not create.  Separate worker and storage would allow for a single Armourer and multiple Blacksmiths if desired.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#30
