### ISSUE TITLE
New hut/worker: The Demolishionist

### ISSUE THREAD

**Issue by EliotWL** [ldtteam/minecolonies-features#340]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

No

## Feature description

A new hut and related worker that you use a wand to outline a space that you want them to demolish and take the items back to the inventory to be added to the warehouse.  To not overlap with the other workers, every time you want them to demolish something, you have to set the area/it's not a recurring location and they can't place any blocks, and don't ignore hut blocks (so builders still would have to do at least some of the demolition for taking down buildings to move them).  This would be helpful for times where you want something removed that doesn't really fit any of the other workers but want it done without directly doing it yourself.  Example would be tearing down a supply camp or removing an unwanted part of a player house you built yourself.  

### Notes or related things

Could also make it late game research once you already have a miner and a lumberjack to level 3 so they aren't too overpowered in the early game

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by seannyyx** [comment]
so what you're asking for is an empty structure.. (or multiple empty structures of varying sizes) so that you can set it in a space and have the space cleared out and then the empty structure would be "built"

**Comment by Thodor12** [comment]
Closing in favor of joint issue ldtteam/minecolonies#4535 [Digger worker]
