### ISSUE TITLE
Chair for sitting

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#342]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
Add in actual chairs for visitors, citizens and players to use instead of stairs

## Feature description
Chairs: make from all types of vanilla woods and wools

### Notes or related things
Chairs in the house for citizens to sit and relax before going to bed.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Probably too out of scope
