### ISSUE TITLE
Mod compat: Wiki Zoomer npc info and Citizens

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#350]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
I want to use the WIki Zoomer to gain access to npc model for showcase, but as I right click the citizen with the item, the citizen's GUI appeared instead.

## Enhancement or Change description
The npc info will be prioritized instead and the citizen is registered.

### Notes or related things
The worker section in the wiki could also use some help from this mod to showcase the worker's model.
https://i.imgur.com/HTiHsuW.png

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#135
