### ISSUE TITLE
Block Swap before Committing to Build

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies-features#355]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5 .. FORGE 36.1.2
- MineColonies Version: minecolonies-0.14.84-ALPHA-universal.jar

## Feature description

In the "Build Options" selection in the MCBuildings, before clicking on "build/update," while the preplanned builds and schematics are always great, it would be nice if I could click on the material requested, and get a selection box of what other !equivalent! "forge_tagged" materials could be used to replace blocks that are being used. It could be configurable in a JSON. So, for example, if I wanted to saw swap my spruce planks in the Nordic TownHall with another wooden plank, say Ebony Wooden Planks from BYG, I could select that alternative plank and change it in the build query.

### Notes or related things

The "Inventory Chest Box" at the bottom of the storage buildings already has a very similar interface to what would be needed, and could be identical, just instead of searching for inventories related to building, it could search for blocks included in the tag: "wooden_plank, wooden slab, stone stairs, etc."

I found myself in a world building up a city with Minecolonies, and found out that not one BYG biome that spawns Granite existed in over 10000 blocks from me, which means my beautiful new gorgeous new cedopeana or whatever they are called could not be built.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/Structurize/issues/37
