### ISSUE TITLE
Firework rockets for archers

### ISSUE THREAD

**Issue by Bossos11** [ldtteam/minecolonies-features#358]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16+
- MineColonies Version: minecolonies-0.14.92-ALPHA-universal

## Is your feature request related to a problem?

no problem, just that archers could deal more damage
## Feature description

You can use Firework as ammo for the crossbow in vanilla and it would be nice if the archer guards could do so too
(maybe as a higher lv research?)
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
New guard types are planned for the future, however will never be backported to older (unsupported) versions like 1.16
