### ISSUE TITLE
Skin Style System (including new hut)

### ISSUE THREAD

**Issue by Bossos11** [ldtteam/minecolonies-features#359]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16+
- MineColonies Version: minecolonies-0.14.92-ALPHA-universal

## Is your feature request related to a problem?

its not related to a problem, just a suggestion

## Feature description

* create a new hut ("tailors hut" as an example) where you can choose (either for the whole colony or job specific) a skin set
* every worker has a deafult skin(from the set [like asian or medieval oak])
* workers need to get a new skin every time their hut is upgraded in order to be able to use the new tools (if they have no specific skin they can only use wood tools)
* to change a skin the worker of the skin hut needs some materials (for example strings)
* (maybe?: create different levels for the deafult skin, which workers will request according to the level of their citizen/tavern/barracks hut)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I'd say this is an extension of #167
