### ISSUE TITLE
this is an idea for the economy system

### ISSUE THREAD

**Issue by Bossos11** [ldtteam/minecolonies-features#360]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Feature description

This is a suggestion for an economics system, which would be balanced for both singleplayer and multiplayer
(and it makes gold more precious). it seems like a lot of text but please read it to the end.

* **implement coins and emerald coins as items** (these can only be crafted in a hut and not by a player)
* **create a new building: the bank/treasur**y, which can only store the currency of minecolonies (here coins)
* **create a new building: the mint**, which can craft the coins
* **create a new building: the tax collector**. the tax collector will visit every citizen hut and collect a tax equivalent to the huts level and the citizens living in it, **that have a job**.
* implement a new system: the wage system. worker huts with a level higher than 1 will need a certain amount of coins (the workers wage) or else the workers wont work. the amount of coins needed will be equivalent to the huts level.

Both the wage system and the tax system will create a circulation of coins (a minimum stock that th player will always need in the bank in order to keep his colony working). By collecting more gold and emeralds he can raise the stock of coins in the bank in order to either buy something in the stores(will be explained later on) or in order to "buy" a new upgrade for a hut. (upgrades dont cost money but the huts worker will need more money as a wage). 

As a start it might be best that the wage and the collected tax per citizen are exactly the same (for example lv 2 citizen hut pays 2 coins tax per citizen; while a lv2 builder needs 2 coins wage) this will result in a constant flow of coins.

Next come the shops:

* **create a new building: the Market. The market is a building which has one worker. It will give the player access to a global shop, where he can sell/buy basic materials like cobblestone wood, etc. . The materials that are available in the specific colonies market will be determined by the huts level.**    By buying something in the market the player will increase the price of said article by a certain percentage. if the player sells a material it will lower its price. The markets store is serverwide making it possible for other players to raise and lower the price of the materials, creating a competition. In order to regulate this competition only simple items like dirt, cobblestone, etc. will be available on the market. The items in the market will also be given a "basic price"; every day the price of all items available in the market will be raised/reduced by a specific percentage(like 10%) of the current value towards the base price, until the price reaches the basic price again.

* **create a new building: the auction house.** The auction house has a worker. At the auction house the player can access an open serverwide market where he can buy/sell all the items that cannot be bought in the market (maybe mod compatible?). The player will only be able to start a certain amount of auctions (depending on the huts level), but can see all auctions on the server. There can only be one auction hut built per colony in order to prevent server crashes due to too many auctions.
### Notes or related things

some parts (like the market) have already been suggested,but they havent been suggested with these mechanics
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
We are *specifically* not going to create an interchangeable currency for balancing reasons (to not create another villager emerald abusable system)
