### ISSUE TITLE
Crusher worker make bone meals

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#363]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Enhancement or Change description
I don't think there is a worker that can craft bone meals from bones. Can the crusher do it? I want to hook up my skeleton farm to the colony.
The recipe can yield more outputs the higher the workers skill is

### Notes or related things
The maximum output for a single bone should be 6 bone meals

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by warning-djkajslh** [comment]
Haha yes

**Comment by warning-djkajslh** [comment]
Does this mean it is added in the next release?

**Comment by ravenbuilder934** [comment]
Yes

**Comment by warning-djkajslh** [comment]
Is the update out now?

**Comment by ravenbuilder934** [comment]
Yes
