### ISSUE TITLE
Damage sounds for citizens and extra children's voice lines.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#367]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
I am always jealous of raiders since instead of having the normal annoying tick sounds when hurt, they have unique grunts and quotes.
Default ticking hurt sound is annoying and if not anxious to hear.

## Enhancement or Change description
Citizens, children and visitors should have similar mechanic for when they are damaged, or die
Will be hard since each citizen, have a unique voice, between workers, unemployed, children, and 2 different genders 

### Notes or related things
Also can you add in some funny voice lines for children instead of the "tee hee" and "heee he he he" all the time when I try to talk to them?

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by carlansor** [comment]
For damage sounds we need to create a specific sound events to assign the hurt sounds, wich i think we already have for some voice profiles. About child voices, we are working on that. Feel free to share that we are looking always for active voice artist that want to contribute!
