### ISSUE TITLE
Mercenaries sould have some sounds

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#368]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
 They are silent

## Enhancement or Change description
 Some voice lines and quotes for them please

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by carlansor** [comment]
we got voice lines already, but there are no sound events specific for mercenaries. Indeed they should have, as well as a custom model too
