### ISSUE TITLE
Mega Build Structures - break down into 5 parts/levels

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies-features#375]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 36.1.4
- MineColonies Version: 0.14.97-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?

Mega builds like the Barracks, Enchanters, Hospital and University, etc. take too many resources and too much time to build.  In survival mode we find giving resources to a builder only to have to provide those resources replaced over and over.  Its a waste of time, resources and builders adding value to the colony.
## Enhancement or Change description

Ideally, having multiple builders working on structures that are X by X by X by X (or require xxx number of resources) could help speed up the process.  Alternatively some designs have towers applicable to 5 levels, but the entire structure is built/replaced at each level.  That's not a practical way of building.  They should follow the same design that Barracks are built.  There is the barracks to level up and then the four towers.  I can assign multiple builders on the same structure to complete it faster.  This could be true for any/all builds if the structures were designed to support this effort.  A lot of work I'm sure, but in the end, the user experience would be much better.
### Notes or related things

We overall love the huge structures, but we're finding they are just not worth the time to build cause they take too long and too many resources.  Even in creative mode, its still pretty painful.
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Yeah this has been discussed several times, however would be extremely complex to code (especially with fluids/etc).
