### ISSUE TITLE
Option to “Move” a building

### ISSUE THREAD

**Issue by telemenar** [ldtteam/minecolonies-features#379]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.95-BETA

## Is your feature request related to a problem?
I’ve a couple times after a building is constructed and upgraded wanted to move the building. The process of doing that today with deconstruct and the building again was something I messed up.

## Feature description
I’d love a button for buildings “Move” — that gives you some kind of building placeholder, when placed with the build tool the GUI for the building placeholder could allow for a “Begin Move” button at which point the builder would deconstruct the original building and build the new building in one step.

### Notes or related things
Bonus points if the building being moved doesn’t render the level 5 variant in the build tool while you are placing the building placeholder. 

Also could potentially accelerate the process and allow two builders to participate at the same time. So that when you click “Begin Move” that the the construction and deconstruction could happen at the same time. (Though I suppose if the old location overlaps the new location this might... Be messy.)

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
it actually used to be like this, with a `Reposition` button. However this was replaced with Deconstruct, and it's unlikely it'll be implemented again

**Comment by telemenar** [comment]
Oh well *Sighs*
