### ISSUE TITLE
Add full support of Nether Trees to the Forester

### ISSUE THREAD

**Issue by insufficient-funds** [ldtteam/minecolonies-features#380]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.77-Beta

## Is your feature request related to a problem?

The Forester can chop down the Crimson and Warped trees, but is unable to regrow them, as the 'sapling' requires being bone-mealed in order to grow.

## Feature description

With MC 1.16, Crimson and Warped 'trees' were added.  Unfortunately, they do not grow the same as normal trees.  The 'saplings' are labeled Crimson/Warped Fungus; and are only able to grow on their corresponding Nylium.  Additionally, the fungus must be bone-mealed in order to grow into a Crimson or Warped tree.   

### Notes or related things

It may make more sense to add a new hut that could handle the nether trees as well as grow the 'giant' mushrooms from red/brown mushrooms, since those all have similar growth mechanics (ie bone meal to grow).

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Already possible
