### ISSUE TITLE
Make bakers to return empty bottles and buckets in their recipes

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#381]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?
I don't want to waste a bottle everytime my baker craft bread doughs, plus wasting 9 irons for a cake is huge.

## Enhancement or Change description
- Best and preferable method: Make the worker to not consume the bottle and waste the glass everytime they craft 2 bread doughs from 1 wheat, its logical for the baker to only use the water inside and not the entire bottle.
- On the other hand, if this couldn't be resolve, you could add in another recipe: one wheat for one dough, this recipe will accompany the bottle recipe, if you have a water bottle, the baker will create 2 doughs, but if you don't, they will only make 1.
- Add in another option for the baker to request empty bottles for double doughs action
- 3 wheats recipe will only be available in low level bakery

### Notes or related things
This is actually a protest for the dough bottle consumption only, I don't care about batter recipe that much

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The baker does have a very small chance to return the bottle (higher with better skill).  The balance for this is that the fisher will typically produce more bottles than you will ever need.  Or the crusher will produce sand for glass fairly cheaply.

(Or if you keep your baker no higher than L2, then they'll make bread dough without water bottles, at the cost of more wheat.)

The baker always returns the buckets for cake batter, so there's no waste there.

**Comment by warning-djkajslh** [comment]
So what is the maximum return rate for bottles per levels? I dont see it being mentioned anywhere else, is there an equation to calculating the rate?
