### ISSUE TITLE
Some options to be added in herder huts

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#382]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

There is no option to disable breeding for sheeps and for some other animals, and I want one, why? I only want the herder to slaughter, for breeding I have another mod and the worker is keep asking for breeding foods.
Also can the shepherd have a no shearing option as well thanks.
No breeding only killing.
Yes I am currently talking about the swineherd GUI as well.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Not all of this was implemented

**Comment by warning-djkajslh** [comment]
Nah close it
