### ISSUE TITLE
Super efficient citizens

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#384]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

Why is that sometimes I see citizens just stand there for a while, idling before they decide to okay lets do the work, sometimes there are requests to be fullfilled and I see citizens arent immediately working on it, especially the crafters that craft and smelt things.
Guards could also the case as they will be brain dead for a while before respond to the nearby threay.

## Enhancement or Change description

Citizens should be super efficient, as soon as they get the work, they should get to work immediately.
I tried messing with the tick update rate in the config, but I see it is already at its maximum, and at that rate citizens are still a dud

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by warning-djkajslh** [comment]
My composters are leaving the fully composted barrel and never empty them, they dont even bothered coming to their workplace, and it is the same for some citizens, and you will have to manually call them, they should at least be standing nearby. No they werent hungry, and sometimes as you call them they just stand there????? Not doing anything at all despite their GUI shows that they are working

**Comment by ravenbuilder934** [comment]
if they're low level this is intentional. did you *change* the update rate? because it can make them slower

**Comment by warning-djkajslh** [comment]
Nope, all of the huts even guards are at l5, and my rate is 1

**Comment by ravenbuilder934** [comment]
the *citizens'* level, so their skills

**Comment by warning-djkajslh** [comment]
Not just at how fast they process stuff, they also hesitate a little while before doing ANYTHING at all, my cooker will decide to cook stuff every once in a while, and for workers that are far away feom their huts, when there is a request, they dont run toward their station, but just stand still, for a long time. You would expect npcs to immediately react to new events. For low level theory, no, there are workers that go to work on schedule like fisher, forester, farmer, beekeeper... Other crafters are dull as hell, these are baker, cooker, craftondemand people..

**Comment by ravenbuilder934** [comment]
well yes, skills are per person. It makes sense that some would have low level skills and some would be higher.
Did you change the config at all?

**Comment by warning-djkajslh** [comment]
yes I did changed some.

**Comment by ravenbuilder934** [comment]
and have you tried resetting it?

**Comment by warning-djkajslh** [comment]
I edited the config before I launched the game.

**Comment by ravenbuilder934** [comment]
edited it to make the changes, or undo the changes?

**Comment by warning-djkajslh** [comment]
edited to make changes, also another point for this was it when citizens gather at the restaurant for food, they will stand there and clumps for a while even if there are good foods available, some citizens will manage to get the foods before others, and sometimes even after finished eating, they still not leave and would like to stand at the restaurant instead.

**Comment by ravenbuilder934** [comment]
have you tried undoing the changes to the config and starting MC again?
