### ISSUE TITLE
Forester stuck on leaves when using [Passable Foliage] mod

### ISSUE THREAD

**Issue by ftzi** [ldtteam/minecolonies-features#387]
Moved https://github.com/ldtteam/minecolonies/issues/6955 here

### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.105-ALPHA-universal
- Structurize Version: 0.13.163-ALPHA-universal
- Related Mods and their Versions: PassableFoliage-1.16.5-2.2.1

## Is your feature request related to a problem?
I have to from time to time go break the leaves that are on the same position of the forester, else he will just stay stuck there. Rarely he will teleport back to the hut. I don't know if this bug still happens when not using the Passable Foliage mod, but anyway, it shouldn't happen, as any NPC/player can pass through the leaves when using this mod. The pathfinding should ignore leaves if using Passable Foliage / check they aren't physical blocks

https://www.curseforge.com/minecraft/mc-mods/passable-foliage

## Feature description
Compatibility fix between those two mods

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#135
