### ISSUE TITLE
Personality trait for npc

### ISSUE THREAD

**Issue by natenmdemon** [ldtteam/minecolonies-features#393]
Idk if it's ok to put suggestions here and Ik on there curseforge paige they say there will be something like this but can they give npc personality traits or behaviors outside of working

**Comment by ravenbuilder934** [comment]
#211

**Comment by natenmdemon** [comment]
I was told I can put suggestions here

**Comment by ravenbuilder934** [comment]
You can, but in this case, your suggestion already exists
