### ISSUE TITLE
Change to builder construction AI for more efficient building

### ISSUE THREAD

**Issue by dupontct** [ldtteam/minecolonies-features#394]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.112-ALPHA
- Related Mods and their Versions: forge-36.1.4

## Is your feature request related to a problem?

When building a large rectangular room, which is for example 2 chunks across (example: Fortress Town Hall), after completing the first row of the build level, the builder will place 1 block on one side of the structure and then start walking to the opposite side of the structure to place the next block.

## Enhancement or Change description

Currently when constructing a building the builder will rasterize the structure to find the build order.

What I mean by rasterize is the a 3x3x3 cube of blocks will be assembled in the following order as represented by the following tables show each level of the build:

Level 1:
1|2|3
---|---|---
4|5|6
7|8|9

Level 2:
10|11|12
---|---|---
13|14|15
16|17|18

Level 3:
19|20|21
---|---|---
22|23|24
25|26|27

Instead of rasterizing I would suggest that the builder use the following order as represented by the following tables show each level of the build of a 3x3x3 cube:

Level 1:
1|2|3
---|---|---
6|5|4
7|8|9

Level 2:
18|17|16
---|---|---
13|14|15
12|11|10

Level 3:
19|20|21
---|---|---
24|23|22
25|26|27

In the worse case example of building a large rectangular room, this would let the build place 2 blocks before walking to the opposite side of the structure to place the next 2 blocks.  Instead of placing 1 block then walking the other side of the structure to place the next block.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Builder modes exist now
