### ISSUE TITLE
Add in a way for guard to attack wild animals while ignore tamed animals

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#395]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

I am playing with Ice and Fire, and the mod have mobs that are tamable but natural ones are hostile, but since they are tamable they need to be labelled as animals so that golems or guards wont kill them.

## Feature description

I am aware of the guard target list in the config, but I want another addition, if a mob in the list is tagged with tamed and with an owner, that mob is ignored no matter what. That way I can have guards defend my colony from dangerous animal mobs like death worms, wolves, foxes....
Some of the examples are: dragons, rats, death worms, cockatrice, wild mobs are terrible but can be tamed and obedient.

### Notes or related things

Might have to backup my world a few time when this got implemented.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
If you had a vanilla wolf that someone tamed, and they used that wolf as part of a colony PVP attack, the guards wouldn't kill it with this feature. So it'd probably cause problems.
