### ISSUE TITLE
Add in a wiki page for the Undertaker worker, as well as the grave structure

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#398]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Pls I am thirst for knowledge

## Feature description

Pls add in wiki pages
https://wiki.minecolonies.ldtteam.com/

### Notes or related things
Additional pages are: schematic names, schematic requirements...

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/MinecoloniesWiki/issues firstly, secondly, I haven't had time yet but will do it eventually

**Comment by warning-djkajslh** [comment]
What should I include in the custom schematic for the graveyard?

**Comment by warning-djkajslh** [comment]
How to determine which graves goes where?

**Comment by ravenbuilder934** [comment]
Use the wiki issue
