### ISSUE TITLE
Only colonists that were a part of the colony when a citizen died will mourn

### ISSUE THREAD

**Issue by chandler05** [ldtteam/minecolonies-features#400]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.123-ALPHA-universal
- Related Mods and their Versions:

## Is your feature request related to a problem?

All colonists mourn whenever one dies, even those that weren't part of the colony when they died, such as a brand new citizen that replaces the deceased.
## Enhancement or Change description

I would think it would make sense for only the colonists that were part of the colony when the citizen died would mourn for them.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Changed, now only citizens that knew the deceased will mourn. as new colonists can't have known them this was implemented in a roundabout way
