### ISSUE TITLE
A new child has born message, unknown who is new

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies-features#404]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal.jar
- Related Mods and their Versions:

## Is your feature request related to a problem?
-

## Enhancement or Change description
Currently, when a new child is born there's no way to know who has just been born, especially in larger colonies it can become rather difficult to find where the new citizen is, it would be a lot easier if the name of the new citizen can be displayed inside the chat message, that way we can at least check who we have to look for.

### Notes or related things
-

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by chandler05** [comment]
Can I steal? 😅

**Comment by someaddons** [comment]
ye
