### ISSUE TITLE
Linking resource scroll to non builders hut

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies-features#407]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal.jar
- Related Mods and their Versions:

## Is your feature request related to a problem?
-

## Enhancement or Change description
Currently it's possible to link a resource scroll to a non builders hut, instead of saying something like "Please select a builders hut to link this resource scroll to" it actually just says "Linked resources for Builder's Hut". If you then proceed to use the resource scroll it says you have to bind it to a builders hut, small QoL change that could make it a bit better.

### Notes or related things
-

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
imo this is more of a bug that you *can* link it to other huts (@Raycoms, confirm?)

**Comment by Raycoms** [comment]
Well, it's def an easy fix
