### ISSUE TITLE
Healers should prioritize healing citizens during mourning days

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies-features#408]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal.jar
- Related Mods and their Versions:

## Is your feature request related to a problem?
It's a bit annoying to see my healer just walking around the city whilst the hospital is just full of sick people with influenza.

## Enhancement or Change description
Healers should prioritze healing the citizens at all times, even when someone just died and everyone is mourning, this makes more sense otherwise they'll be mourning the next day again ;)

### Notes or related things
-

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Might be easier to make them exempt from mourning like the guards are (iirc)

**Comment by chandler05** [comment]
Can I steal this assignment?

**Comment by ravenbuilder934** [comment]
Preferably not. I know I've been behind on assignments, but school ends in a couple weeks and I should have more time then 🙂

**Comment by chandler05** [comment]
Ok, that's fine! Good luck with school 👍

**Comment by ravenbuilder934** [comment]
Not really necessary anymore as now only family members and housemates mourn
