### ISSUE TITLE
[Mod Compatibility] Chisel & Bits Support

### ISSUE THREAD

**Issue by Alshina** [ldtteam/minecolonies-features#413]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134 ALPHA

## Is your feature request related to a problem?

* Builders can't build blocks made out of chisel and bits blocks. It request a block that is impossible to fulfill when building (Ex: 'block.chiselandbits.chiseledrock'. The only way to get around is to go to creative mode and fulfill the request. 
* C&B blocks don't display in the preview correctly.

## Feature description

* Proper display of the blocks in the build preview
* Builders able to build C&B blocks using either the base block or the bits.
 
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies-features/issues/135
