### ISSUE TITLE
Partially transparent current layer preview for structures being built

### ISSUE THREAD

**Issue by Typhonidite** [ldtteam/minecolonies-features#416]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134-ALPHA

## Is your feature request related to a problem?
I find builders to be too slow. Rather than making them faster, I wish there was a way to help them build yourself.

## Feature description
When a builder is constructing structure, I'd like there to be some way to have a partially transparent preview of only the current layer the builder is working on, so that you can help build properly, without having to remember a structure inside-out, or simply guessing.

### Notes or related things
Suggestion #122 is similar to this, but only mentions highlighting blocks that will be destroyed.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by seannyyx** [comment]
This!  
It's wonderful watching them build. but sometimes they're so slow at it. If you can just give them a little help..  
I personally like to help clear the area, removing trees, taking off the top layer of grass etc to get them to the actual building a little quicker. But to be able to see what they are building and help them out would be quite handy too.

**Comment by ravenbuilder934** [comment]
You can craft another hut/etc and put up another build tool preview, which will show you the blocks to be placed
