### ISSUE TITLE
More specific fertilizer request for farmers

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#419]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

There is only one fertilizer request for farmers, when you enable it, they will ask for both bone meals or fertilizer.

## Feature description

Since we now have crusher to make bone meals, can you have two separated options to either ask for fertilizer or bone meal, or even two at the same time, it should be something as follow.

Farmer request system GUI:
[ ] Bone meal
[ ] Fertilizer

Tick the box to make farmers to request the stuff and actually use it, if you don't they will ignore the item.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#166
