### ISSUE TITLE
Teach rabbit herder to turn hides into leather

### ISSUE THREAD

**Issue by Lielac** [ldtteam/minecolonies-features#433]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.166-ALPHA

## Is your feature request related to a problem?

I have a rabbit hutch that keeps churning out rabbit hides, but none of my colonists can turn the hides into leather.

## Feature description

Teach the rabbit herder, or whoever seems most appropriate, to turn rabbit hide into leather when leather is requested and the cowhand is behind on their kill quota.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
*is thinking of tanneries* Possibly the dyer? The rabbit herder isn't a crafter, so they shouldn't be able to.

**Comment by Lielac** [comment]
Oh, I hadn't checked whether the rabbit herder even has a crafting grid. Dyer could also make sense. More sense than the mechanic, at least.

**Comment by ravenbuilder934** [comment]
Technically they *do* have a crafting grid - almost every building has one. The difference is that non-"crafters" will only make items if they're requesting it themselves.
I can ask around to see if others agree with the dyer

**Comment by ravenbuilder934** [comment]
I believe the consensus was for fletcher to do it, making a PR now
