### ISSUE TITLE
Bluemap Integration

### ISSUE THREAD

**Issue by AngellusMortis** [ldtteam/minecolonies-features#435]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: N/A

## Is your feature request related to a problem?

No.

## Feature description

Add integration to the awesome server map mod [Bluemap](https://www.curseforge.com/minecraft/mc-mods/bluemap). Speicifcally:

* **MVP**: Render bounding boxes of colony + location of town hall as a marker on the map
* **Nice to have**: Render locations/details of buildings in colonies as markers on the map
* **Nice to have**: Render locations/details of colonist as markers on the map (live)
* **Super nice to have**: Let individual players opt in/out of displaying their colony on the map (or make a config option/admin command/etc.). 

### Notes or related things

Bluemap API: https://github.com/BlueMap-Minecraft/BlueMapAPI/wiki

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#135

**Comment by Nikogrelis** [comment]
Hello!
As far as I understand, this feature is missing in version 1.20.1?

**Comment by Thodor12** [comment]
This was never made, so no.

**Comment by Nikogrelis** [comment]
> Этого никогда не было, так что нет.

I made a 1.18.2 server a year or more ago and it worked. The only thing I think is that I used some addon...
