### ISSUE TITLE
dwarven skins for true dwarf style

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#437]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Dwarf style uses dwark skins

## Feature description

Dwarf skins for dwarf style

### Notes or related things

HOO HOO HOO HAA HA HAAAAAASASA!!!!!

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Please fill out the template (i.e. more than two sentences).
