### ISSUE TITLE
Dynamic trees Support

### ISSUE THREAD

**Issue by Bossos11** [ldtteam/minecolonies-features#438]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.174-BETA-universal.jar 
- Related Mods and their Versions: DynamicTrees-1.16.5-0.10.0-Beta12.jar

## Is your feature request related to a problem?

The config options(accessability) for this mod are not yet implementad

## Enhancement or Change description

Please implement dynamic trees support for the forester.

- implement the config options
- add an option whether to use dynamic trees options from config
- if dynanmic trees is on/loaded make it possible fpr the forester to use bonemeal on dynamic trees
- if dynamic trees is on/loaded the forester will only destroy the lowest block of a dynamic tree instead of starting at the highest block

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#135
