### ISSUE TITLE
Balloon Structure

### ISSUE THREAD

**Issue by AdityaDotZip** [ldtteam/minecolonies-features#439]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

A structure called as The Deflated Balloon which is a hot air balloon made up of wool and is torn apart
It can have some leather armour , some food ,some bones and a barbarian gear
This structure will be rare.

**Comment by ravenbuilder934** [comment]
How does this fit into the overall MineColonies theme? What are your reasons for suggesting it?

**Comment by AdityaDotZip** [comment]
It can have Wandering colonist which when killed can drop  Knowledge Pages Which can be used in boosting the speed of workers in univerities as the pages will have knowledge of the world

**Comment by ravenbuilder934** [comment]
okay, well, I'd say this is prolly too out of scope. Worldgen stuff like barbarian outposts and NPC colonies are planned, however I'd say a crashed balloon would be better in a separate mod with a wandering trader-like entity. In addition there are already several ways to boost speed of workers, including researchers
