### ISSUE TITLE
Citizens feel dead inside to me :(

### ISSUE THREAD

**Issue by Vravinite** [ldtteam/minecolonies-features#442]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: forge-36.1.24

## Is your feature request related to a problem?
No

## Feature description
I think something VERY important to make the citizens feel more alive (for me personally it feels like a bunch of robots) is to allow them to do something other than wake up, go get food, work, sleep, repeat.
For example maybe like 90% of persons made their own food back then, the lumberjack was usually a hunter and "chef", etc.

What I think should be done is;
Introduce currency (I'm sure this must be being worked on already), maybe make it variable like in Victoria 2

Allow multiple citizens in way more jobs/buildings

Citizens get currency by selling their produce (Or if you want, even if it is harder to code, by being paid by a noble/bourgeois/colony-owner for work day and the hirer obtains all produce. _Would be really cool tho_.)

Make citizens work if they don't have money to buy 6 "meals" in their inventory (unless they are hired)

Make citizens buy what they need from other citizens

Builders are paid for completing buildings

Don't make professions SO segmented:
- A farmer can and should grow at least 1 livestock animal, also making their own fertilizer, even if at smaller quantities
- A medic is commonly a herbalist too, sometimes even a beekeeper
- Teachers are usually librarians/researchers
- Couriers are unrealistic and slave-like, storage should be handled by each worker
- Chefs should be useful only for fancy meals
- Everyone should be able to cook their own food, maybe only when they are home
- It would make sense if an enchanter is a researcher
- Builders should do another job while they aren't doing anything so they can survive, for example working as a carpenter

Reintroduce couriers in a way that they buy the stockpile set for the manager, or the material lacking (if a building is planned for example) for a salary

Make visitors behave differently:
> They arrive to the city with a job idea and an amount of savings, so if the building for the job doesn't exist you can help them pay for the rest of the cost of building it (or all of it), or just add them to an existing building. And if you decide to add the noble/bourgeois idea, one of them could arrive and the player can allow them to set up their enterprise for a set tax rate and even make them change their mind if the tax is too high.

If nobles/bourgeois are added they can also hire visitors

Get taxes for plot size

Introduce trading between colonies, if there are no colonies, add a "faraway colony" that buys everything but at a decreased price that follows a system like:
while fcStock > 0:
price = price + 0.1
fcStock = fcStock - round(sqrt(fcStock), 1) - 0.01
> tweaking this obviously

### Notes or related things
Hope this helps

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Economy is planned and partially covered by #139 and #360, trading is planned and covered by #2, rest can go under #128
