### ISSUE TITLE
date and time

### ISSUE THREAD

**Issue by cassioJones1** [ldtteam/minecolonies-features#444]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## 

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by cassioJones1** [comment]
Implement a date and time system. Where a clock building would be placed and also a calendar where the player can configure as he wishes, this calendar would have holidays where the player can configure whether workers can work or not.

**Comment by Stoovey** [comment]
@ravenbuilder934 

Can you close/delete this? 
Nothing in this.

**Comment by ravenbuilder934** [comment]
The OP had actually posted a comment with what was presumably meant to be the body of the issue, but since it's deleted now, yeah I'll close it
