### ISSUE TITLE
Add blueprints for Postbox and Stash to the infrastructure section build blueprints menu

### ISSUE THREAD

**Issue by dupontct** [ldtteam/minecolonies-features#449]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.197-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?

When designing structures one cannot manually place either the Postbox or the Stash without being in a colony. For other blocks like this (eg all the Hut blocks) there is a single block schematic containing just that block. Having to spin up a colony just to place a Postbox or Stash is frustrating.

## Enhancement or Change description

1. Add a single block schematic containing just the Postbox block
2. Add a signal block schematic containing just the Stash block

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Fixed via ldtteam/minecolonies#7190
