### ISSUE TITLE
Incorporate Spore Blossom!

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies-features#458]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:1.17
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

No
## Enhancement or Change description

I just want a small change that is on the decorations and buildings which are supposed to be like natural and beautiful. Pls incorporate the new Spore blossom plants on such buildings and update the old schematics(If possible). Cuz they have such a unique mechanism of ambience and look cool
### Notes or related things

Its just an idea no need to rush and sry for any grammatical mistakes in advance
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
spore blossoms will ofc be worked in as will other 1.17 blocks/items. this doesn't require a feature request issue imo
