### ISSUE TITLE
For 1.17, builders should be able to place the minecraft:light block

### ISSUE THREAD

**Issue by dhouck** [ldtteam/minecolonies-features#461]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: N/A; not yet released

## Is your feature request related to a problem?

A lot of the existing lighting solutions don't fit well aesthetically with some styles, or sometimes the ones that do are expensive.  Even though (once the level 1 building is built) mob spawning isn't an issue, having lighting is still useful.

## Feature description

Builders should be able to place the invisible light block `minecraft:light` either for free or for something very cheap, instead of requiring this usually-creative-only block.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Not going to happen
