### ISSUE TITLE
A Market/Trading System

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies-features#462]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Feature description

Overall system:
    A UI in the townhall(from lvl 3)/ a structure from which we can trade for a custom currency like "$".
    Selling system: Allows items that can be farmed in masses like crops, cobblestone, woods to be sold to that worker/UI
    Buying system: Allows items that cannot be farmed or crafted by any workers like sugarcane, and are not "reward" items like dragon egg/head, netherstar, bell etc. which will include nether stuff (like blackstone/guilded blackstone, etc) from lvl 3 onwards and end stuff(like chorus fruits) lvl 5 onwards
    A bonus for lvl 5/4 of them will be player trades, where a player can put his/her own items for auction in it and other players at lvl 5/4 will be able to buy them.

Another idea of system:
    A market structure which would not have its workers of its own but some merchants will spawn at sunrise at the colony borders and they will wander to that structure and will equip a stall there and will buy items from the colony owner/ officer based on the buildings that colony has and will sell items like the previous system, and they should wander outside the colony by sunset and despawn.
    The higher the level of that structure the more discount they should give.
    Lvl 1 should have 1 stall for 1 merchant, lvl 3 should have 2 stalls for 2 merchants and lvl 5 should have 3 stalls for 3 merchants
    
### Notes or related things

The 1st system may or may not run out of stock. If it runs out of stock it should restock the next ingame day

The second system must have a limited stock (and they cant restock cuz they will despawn at the end of 1 day)

 I think this can be  pretty neat feature
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Post a comment on #2
