### ISSUE TITLE
Colonist Health Overview Tab on Clipboard

### ISSUE THREAD

**Issue by AerosAtar** [ldtteam/minecolonies-features#463]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.220-ALPHA-universal

## Is your feature request related to a problem?
I've lost count of the number of times that I have not noticed the fact a colonist is sick for an extended period, leading to various issues and delays (especially if it is a courier, builder or restaurant).

## Enhancement or Change description
An additional tab for the Clipboard that lists colonists with health issues, possibly including what the health issue is as well as the required items to cure them. Essentially a 'health' version of the regular Requests clipboard list.

### Notes or related things
Could potentially be expanded to show other 'complaints' colonists have (no house, no job, etc) instead of just health issues.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Post a comment on #67
