### ISSUE TITLE
Day/Night cycle out of sync

### ISSUE THREAD

**Issue by AngleWyrm10** [ldtteam/minecolonies-features#464]
It's 1:15 PM of day 88 in-game but oddly "all colonists are safely tucked into bed." The two builders no longer do work, and when recalled to their buildings they show "zzz" particles, apparently sleep walking. They wander aimlessly a few meters, still emitting "Zzz."

I've tried:
- exiting and restarting Minecraft
- putting a stack of bread in their inventory
- firing and then recruiting and hiring new colonists -- they take on the same behavior
- resetting time to night when the "tucked in bed" announcement pops up

---
Minecolonies v0.14.206
Minecraft v1.16.5
Forge v36.1.7
[Latest log](https://paste.ee/p/brv5k)
Issue might be related to ldtteam/minecolonies#7051 and/or ldtteam/minecolonies#6705

**Comment by Raycoms** [comment]
#135

**Comment by AngleWyrm10** [comment]
Yes there was a raid active. No one ever showed up, and it's been active for days. 

And "Zzz" is maybe not the best choice of indicator for "citizen hiding due to raid," especially after training us to associate it with sleeping guards.

Looks like I'm gonna have to disable the raid mechanics.

**Comment by ravenbuilder934** [comment]
The raid should despawn after 3 ingame days (default, can be changed in the config)

**Comment by AngleWyrm10** [comment]
There are only three options in the [config file (config/minecolonies-client.toml)](https://github.com/ldtteam/minecolonies/blob/834919bbd653a9114258109438676697c4cd0810/src/api/java/com/minecolonies/api/configuration/ClientConfiguration.java#L19)

- neighborbuildingrendering = true
- disablecitizenvoices = true
- pathfindingdebugdraw = false

Where is this despawn setting? Or is it just a memory?

**Comment by ravenbuilder934** [comment]
That's the wrong config file, look inside the save folder -> serverconfig folder ([minecolonies-server.toml](https://github.com/ldtteam/minecolonies/blob/version/main/src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java#L15))

**Comment by AngleWyrm10** [comment]
Thanks, the option to disable raid mechanics in the save-specific config file fixed the issue.

A victory message appeared, and after sleeping through the night the colonists began work on their projects.
