### ISSUE TITLE
Hauling couriers / manual courier directions.

### ISSUE THREAD

**Issue by EliasRipley** [ldtteam/minecolonies-features#468]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.177

## Is your feature request related to a problem?

Nope.

## Feature description

I would like to see a colonist who could be trained / taught to collect supplies from a chest within the colony border and take them to another chest / to the warehouse.
This could potentially be added to the tasks that the existing courier colonist already does, or a new type could be created for the situation. Hauler rather than courier perhaps?

### Notes or related things

This might require a new tool that can "direct" colonists to the chests players want them to interact with.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by EliasRipley** [comment]
Another potential solution would be a "reverse postbox" / "collection point". If we had something like that, it could easily be added to the couriers routine. Ideally the "reverse postbox / collection point" could have items added to it via hopper / dropper for better automation.

**Comment by vroni92** [comment]
> Another potential solution would be a "reverse postbox" / "collection point". If we had something like that, it could easily be added to the couriers routine. Ideally the "reverse postbox / collection point" could have items added to it via hopper / dropper for better automation.

Have a look at the stash, this already exists.

**Comment by EliasRipley** [comment]
Amazing. I'll have to get that sawmill built so I don't miss out on other things that come out of there. I'll close this. Good work!
