### ISSUE TITLE
Enable unlimited resources for builder based on level

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#47]
# Prerequisites

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**
- [X] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.x+

### Expected behavior

It would be nice to find a healthy balance for the unlimited builder resources, I wish there was a config setting to enable unlimited builder resources to be enabled or disabled by building level.

Example:
#Builder_Unlimited_Resource_Level: {0..5}

- if it's set to 0, builder never has unlimited resources,
- if it's set to 1, builder has unlimited resources for all level 1 building levels
- if it's set to 2, builder has unlimited resources for all level 2 building levels and below,
- if it's set to 5, builder has unlimited resources for all level

#### Specifications

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by Mekle001** [comment]
I like this, it feels like a first step toward #34

**Comment by Justen-N** [comment]
Feature rejected by team leads.
