### ISSUE TITLE
The ability for warehouse to detect extra racks

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#473]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

If your warehouse if full, you can only dump items out and not put in extra storage

## Feature description

Add in a new rack detecting staff that will register new racks that isn't in the schematic

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by EliasRipley** [comment]
That seems like a good idea. If this is possible, I would suggest that it should only be applied to max level warehouses. (So players don't cheese the upgrade system.)

**Comment by ravenbuilder934** [comment]
This is intentional. Only racks already in the schematic will be counted. At higher levels the warehouse has an option to increase the storage of existing racks, which can be used instead; if you absolutely need more racks you can create your own schematic.
