### ISSUE TITLE
Min Amount of Saplings for Forester's Hut

### ISSUE THREAD

**Issue by EliasRipley** [ldtteam/minecolonies-features#474]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.228-ALPHA
- Related Mods and their Versions: Plenty o Biomes

## Is your feature request related to a problem?

Not really a problem, just a small improvement that could be made to the forester.

## Enhancement or Change description

I would like to be able to have a "min stock" at the Forester's Hut. This will make it easier for the forester to replant some trees that have low sapling drop rates as they will always have some on hand... I think? (Does it have to be in their inventory rather than huts? If so, could the min stock be kept on their person?)

### Notes or related things

I first noticed this when using 'Plenty of Biomes' variant of oak. The forester didn't have any "flowering oak" so just used a normal oak sapling. I tried planting some trees that have rare drops like jungle and eventually the forester forgot that a tree used to be there in situations he couldn't replant. (I'm guessing if it's not replanted within a certain amount of days it's lost from his memory?)

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#186
