### ISSUE TITLE
Socializing citizens

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#477]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I am not going to even bother to check and see if the issue is already posted and just leave it to the team to sort it for me.

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Citizens feel like they are just biological robot and doesn't have any human needs

## Feature description

I want citizens to interact with one another, caring for each other,  stop working visiting other's worker building, and other activities involve with different citizens in the town. 

### Notes or related things

Not really a leisure activity as this is just a conversation mechanic for citizens.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> I am not going to even bother to check and see if the issue is already posted and just leave it to the team to sort it for me.

this is a bit rude, at least try to do a keyword search. I also recommend asking in the #suggestions channel on our [discord](https://discord.minecolonies.com) where we'll tell you if it's already been suggested. in this case it's already covered by #128
