### ISSUE TITLE
Implement scheduled colony backups

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#48]
# Prerequisites

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**
- [X] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.x+
- MineColonies Version: <latest>
- Related Mods and Their Versions:

### Expected behavior

Server running longer than a configured time would run the '/mc colony backup' command on a scheduled interval (configurable in Minecolonies config).

This is similar to functionality that I have seen that will save world backups on an interval (every hour while a user is logged in/chunks are loaded).

Introduced in [4674](https://github.com/ldtteam/minecolonies/issues/4674)

### Actual behaviour

Server was online, running smoothly on a personal computer for 10 days. Since no server restart was needed to fix any issues in the interim, no backup was created for the colony. When the computer ITSELF had an issue (graphics card error), on hard reboot of the system the colony data for that 10 days was lost and restored from the previous state (last restart) since no manual backup had been performed (I was unaware of this command until after the crash).

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by PowerSchill** [comment]
@raycoms Is this something that would be covered by any Minecraft server backup plugin? And do we want to include that functionality?

**Comment by Mekle001** [comment]
I would say yes. my servers have all of the minecolonies data backed up, since most of those get everything under the world folder, if not everything under the minecraft folder. In addition, the world/Minecolonies folder has regular backups of the colonies.dat file as zip files.

**Comment by someaddons** [comment]
Note that the backup is normally not needed, the Colony data is stored in capabilities. The backup files are a fallback for when those capabilities happen to get lost

**Comment by Raycoms** [comment]
I don't think this is needed. What I think is needed is scheduled pruning.
