### ISSUE TITLE
Remove: Smelter asks for ore all the time

### ISSUE THREAD

**Issue by Vito0912** [ldtteam/minecolonies-features#480]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.230-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?
I use the clipboard a lot. However, since I got the smelter, it always tells me that it has no ores. This is not the case with the restaurant, for example. Here, the food is then administered when it is delivered. Why frgat the Smelter now but all the time, about the request bubble and accordingly also the clipboard ore on ? Could you deactivate the permanent / introduce a setting. Here is an example:

![Example](https://user-images.githubusercontent.com/86927734/124395598-478e1180-dd05-11eb-9db0-41304f1a8cba.PNG)

## Enhancement or Change description
deactivate requesting Ores about the requesting System

## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Uyarrr** [comment]
Yes, I agree that.
