### ISSUE TITLE
re-enable crafting in the library

### ISSUE THREAD

**Issue by Dryelo** [ldtteam/minecolonies-features#488]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- Forge Version: 1.16.5-forge-36.1.16
- MineColonies Version: minecolonies-0.14.289-ALPHA-universal

## Is your feature request related to a problem?
In one of the last updates (where the buildings' GUIs were changed) the possibility for library students to learn recipes was removed. Please re-enable this.

## Feature description
Library students were able to craft the books they need. Teach them how to make paper from sugar cane and teach them how to make books from paper and leather. Both 2x2 recipes. Sugar cane was requested from the plantation, leather was requested from the cowboy.

Up until the recent GUI update this was possible. Now the library doesn't have the tab to teach recipes.
Was this left out intentionally?

### Notes or related things
Is there any other building I'm missing that crafts books?
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Plantation is intended to craft books, library has no real reason to

**Comment by Dryelo** [comment]
okay, thanks for the feedback.
