### ISSUE TITLE
Improve Upon Warehouse Organization & Sorting Ability

### ISSUE THREAD

**Issue by Mewcenary** [ldtteam/minecolonies-features#496]
### Prerequisites 

- [Yes ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ Yes] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ Yes] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:  1.16.5
- MineColonies Version:  minecolonies-0.14.279-ALPHA-universal

## Is your feature request related to a problem?

I am frustrated that I can't keep the warehouse organized even with the sort option from another mod, all the items are spread out randomly and I have to hunt for them. 

## Feature description

I would like to request that a smart sort feature is implemented into the warehouse that lets you set what item goes into each rack, up to say reasonably, 5 item types per rack.  That would help keep the big bulk items like wood and stones easier to track.  It could also have a feature to simply sort by item type, like oak = all oak items or spruce, etc, cobblestone = all cobble items.  Or a combination of both would be great.

### Notes or related things

I thought there was a sort button, but I have none for my lvl 5 warehouse.  if there is an option for better sorting I can't find it.
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The sort button is always there, although is only enabled starting at L3.  But in addition to the sorting there is also a search function: click on the little chest icon at the bottom and start typing the item you want to find, and then you can click a button to highlight which rack that item is in in-world.  (And you can see this highlight through walls, so it's very easy to find.)

The automatic sorting will group items by mod id (among other things), so if you search for any one item from a particular mod you'll usually find all the other items from that mod in the same rack, after a recent sort.

**Comment by Mewcenary** [comment]
> The sort button is always there, although is only enabled starting at L3. But in addition to the sorting there is also a search function: click on the little chest icon at the bottom and start typing the item you want to find, and then you can click a button to highlight which rack that item is in in-world. (And you can see this highlight through walls, so it's very easy to find.)
> 
> The automatic sorting will group items by mod id (among other things), so if you search for any one item from a particular mod you'll usually find all the other items from that mod in the same rack, after a recent sort.

Ooooh Okay, I had to remove and readd the mod, I see it now.  SOOOO much better!!!!!!!!!!!!!  still think the idea though is good.  Thank you for confirming the option since it was missing at first.
