### ISSUE TITLE
A JAIL AND PRISONER SYSTEM

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies-features#499]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:

## Is your feature request related to a problem?

No.
## Feature description

A new jail system:
1. The last 2/3 remaining raiders/pirates, etc will have a chance to surrender to the player/guards
2. For player, when the player can either kill him or hold him captive(by right clicking on that raider or pirate a UI opens up if there pirates prompt, where they have a request message to spare their life), where the guards will take them to the jail building(if there is enough space else or just leave them free where they despawn)
3. For guards, there will be a option in the townhall menu(like the option with child being born in colony), where if its on, any surrendering pirates or raiders will be held captive by the guards
4. For the jail building, (it should work like school building) where a keeper will be employed and rest will be the prisoners
5. The keeper will give the prisoners books to make them educated(like teacher at school) and give food keep them fed as prisoners cant go to restaurant
6. After the attackers are held captive, they will turn into citizens but with a prisoner outfit and job and will have stats like current tavern level but have better stats on fields which influence guard
7. After a certain time, the prisoners can be recruited for other jobs or can be set free
8. If they are set free, they will roam around a little bit like tavern visitors(at which state, the player can again take them to the colony for free) and then eventually despawn
9. The level of Jail will specify how many prisoners can be held captive at once 
10. The building for jails should be fairly large and can be built multiple times
### Notes or related things

I think this can be a pretty neat and easy feature to add in this mod
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Comment on #113
