### ISSUE TITLE
Minecolonies make name tags craftable?

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#500]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Name tags are only obtained from dungeon raiding, **VILLAGER** or fishing.

## Feature description

- A recipe for name tag
- A worker that can make them on request, preferably required research(like blacksmith).

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
we're not going to add recipes for vanilla stuff unless that vanilla stuff is *very useful* to a colony, such as chain armor. name tags aren't really necessary for *anything* and I see no reason to add a recipe for them
