### ISSUE TITLE
Allow manual house assigning in the Townhall's GUI

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#501]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

From my experience with manual hosing assignment, once you have abundant of household and someone die, you will have to run around to find that one empty house to assign.

## Feature description

Housing feature in the Townhall, check to see the number of citizens inside a house and what are available and assign the citizen to that house.
Once the citizen has a house, you will see the citizen run home while at the townhall.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#281
