### ISSUE TITLE
Medieval skin recognition for custom schematics

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#502]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

I want to make my own set of schematic, but I want this townhall to create medieval citizens, but I can only have default skin

## Feature description

Can you have an option for custom schematic to use the medieval skin?

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This already is a thing..you need to tag the town hall block with `medieval`, iirc. In the future please post suggestions in Discord first to ensure they don't already exist.
