### ISSUE TITLE
Citizens should head to the nearest restaurant they can find

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#507]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

I tried to ask this question in the discord but no one know since they only have one restaurant.
If you have multiple restaurant, citizens will just head to the first one.

## Enhancement or Change description

Citizens should head to the nearest restaurant they can find if a colony has multiple restaurants, that will save them time for their journey

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
*sigh* This should already happen, if not it's a bug. Again please ask in #suggestions before submitting an issue, we'll tell you if it's invalid in some way.
