### ISSUE TITLE
Better Builder Rack managment

### ISSUE THREAD

**Issue by Aleksejus1** [ldtteam/minecolonies-features#510]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.314-ALPHA
- Related Mods and their Versions: Structurize 0.13.205-ALPHA

## Is your feature request related to a problem?

It's annoying/time consuming to see my builder go up and down to the basement and ground level floor to collect materials for building so many times. Haven't counted it exactly, but he usually goes up/down ~10-20 times perhaps even more each time he comes back for materials. He does this even if i move all items into the racks in the basement, he keeps going up to the first floor near the builder house block and then back down again.

## Enhancement or Change description

In short: A way to have my builder spend less time collecting materials from racks and more time actually building.
In long, I've got a couple of ideas how this could be done, but if none of them are good enough I would love to see an alternative solution to this problem, here's my ideas:
1. Allow player to specify which inventories the builder should check when collecting items and which ones he should not (including the house block)
2. Allow player to change the location of racks within the building, no need to have more racks than there already are, but simply the ability to move them to a different place would be nice.
3. Have the material collection algorithm be a bit "smarter". From my own observation i'm assuming that currently the algorithm is something along the lines of:
a. Builder has a list of items he wants to take from racks into his inventory
b. Chooses first item in that list
c. Goes through all racks to collect that item
d. Repeat from b.
A simple alternative would be to have the builder go through each rack, check each item in the rack if it matches any of the items that the builder requires, if so picks up all the items from the rack that it requires and moves on to another rack. This way he'd only need to visit each rack once, or maybe max a couple of times if he had to empty his inventory somewhere along the way.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SivartMcDorf** [comment]
I've always thought it would be cool if when building or upgrading it set up a small work area next to the build site.  Sawhorses and stuff then the courier could deliver the supplies to the job site instead of the builder's hut.  This would allow prepping several jobs at once.

When deconstructing the same process could happen in reverse, the builder could put out a stash(or similar functioning device) and deconstruct putting items in the stash until it is full, then he waits for couriers to empty it until the site is gone then the courier takes the stash item with him when it is complete.

**Comment by Knaxia** [comment]
I can't agree more with that. I've been playing again recently on 1.17 and I made the medieval dark oak alternative builder hut. The thing is, starting from rank 2, the racks are in the basement in a different building, so my builder enters the main building to the builder block, then goes back out, enter the other building, goes down the spiral stairs, to the rack, comes backup and repeats. Plus, he has to navigate both doors, which he pauses to open and close each time, and the spiral stairs which also causes pathing issues as I can see him jump a few times in them. Each building steps can take more than 5 minutes of just going back and forth for the mats.

--> What I had in mind is allowing the builders, and, in fact, any other jobs, to have full direct access to any of their racks, directly from their job block, just like in the warehouse, without having to directly walk to their physical rack to pick the stuff up. It would greatly speed up grabbing and storing.
