### ISSUE TITLE
Add in the minimum stock function for guard and barrack tower

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#511]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

When the armors of the guard is broken, they become vulnerable, and it will take a while for armor to be made and delivered.

## Feature description

Minimum stock for guard structures, that way guards will immediately have available gears, weapons and foods

### Notes or related things

Protection is crucial for the colony
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#186
