### ISSUE TITLE
Beacons should buff citizens

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#512]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Beacons should also be applied to citizens, as any other Minecraft physics.

## Feature description

Any effects in the beacons will also be applied to npcs, including visitors.
Minus raiders and mercenaries.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Beacons only affect players in vanilla. them not affecting colonists is intentional
