### ISSUE TITLE
Structure blocks and storage rack managing.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#535]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

I sometimes lost track of where which item is deposited in which rack.

## Enhancement or Change description

Add in the warehouse highlight system for other structures as well, to help players navigate items.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This already exists, at least for the builder hut although I think the other huts have it as well
