### ISSUE TITLE
Renewable dirt

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#549]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Thanks to this mod, we can have sand, gravel and clay renewable, but not dirt?

## Feature description

My suggestion would be composter can craft dirt from compost.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is already a thing that the composter can do.

**Comment by warning-djkajslh** [comment]
wait what???? please tell me the recipe for it, or can I tell the composter to output dirts from the barrel?

**Comment by uecasm** [comment]
Go to the composter's hut and switch it from compost to dirt in the settings.  It's covered in the wiki, although the UI looks a bit different now.
