### ISSUE TITLE
Colony specialization...the unused TH button :(

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#55]

**Comment by PowerSchill** [comment]
This is a planned feature but would it hurt to disable the button in the meantime?

**Comment by Nightenom** [comment]
At <https://github.com/ldtteam/minecolonies/blob/version/1.15/src/main/resources/assets/minecolonies/gui/townhall/layoutactions.xml#L15>
```diff
-            <button id="changeSpec" size="120 19" pos="38 153"
+            <button id="changeSpec" size="120 19" pos="38 153" enabled="false"
```
