### ISSUE TITLE
New worker and schematic: cobblestone digger and cobblestone factory.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#550]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

The cobblestone digger (name undecided) is the worker who operates a cobble generator and obtain infinite cobble/stone for the colony.

## Feature description

Similar to crusher and digger, at L1-L4 the worker will have a limit of how many cobbles will he made everyday, at L5 it is unlimited. The tool restriction rule also applied as normal.
The hut's schematic will have a cobblestone generator blueprint in it (careful of workers burning to death).

### Notes or related things

Eventually when miner dig out every parts of the colony, there would be a dire need for cobblestone to sief into more stuff.
Because we can't have miner operating cobblestone generators, we should have a dedicated worker for that matter.
Not gonna have the worker operate stone generator, you will have to have the smelter smelt them.

THE END

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
A quarry is already planned, that will be the intended method to obtain cobblestone.

**Comment by warning-djkajslh** [comment]
Wouldnt a quarry eventually run out of cobbles? If it not, then how??? There is already a built in mechanic where you just sit around and harvest cobbles, now we just need to have a citizen to automate thism

**Comment by ravenbuilder934** [comment]
> Wouldnt a quarry eventually run out of cobbles? If it not, then how??? There is already a built in mechanic where you just sit around and harvest cobbles, now we just need to have a citizen to automate thism

*Theoretically* it would, but that would take a LONG time due to the sheer size of colonies. We aren't going to add a way to create cobble for free, even if the mechanic exists in vanilla - ✨ balance and progression ✨ 

however, you could set up a cobble gen and simply stick it in the path of the miner, they shouldn't continue while there's still cobble to mine

**Comment by warning-djkajslh** [comment]
But wouldn' the miner also destroy the entire generator to fill the mines schematic?

**Comment by ravenbuilder934** [comment]
yeah, but only if they got past breaking that initial cobble block, which they won't (if you position it correctly)

**Comment by warning-djkajslh** [comment]
I get your point, then I will build one that can generate multiple cobbles at 1 time.

**Comment by warning-djkajslh** [comment]
Next question, can I situate the generator at the highest level to safe walking time for miner?

**Comment by warning-djkajslh** [comment]
Next question, can I situate the generator at the highest level to safe walking time for miner?

**Comment by ravenbuilder934** [comment]
> Next question, can I situate the generator at the highest level to safe walking time for miner?

sure, as long as you make sure they're mining there at the time

**Comment by warning-djkajslh** [comment]
Next question, can I situate the generator at the highest level to safe walking time for miner?

**Comment by warning-djkajslh** [comment]
Iirc you can assign the mining level, so that should tell the miner which level to mine right?

**Comment by ravenbuilder934** [comment]
> Iirc you can assign the mining level, so that should tell the miner which level to mine right?

yep

**Comment by uecasm** [comment]
GitHub is not intended for extended conversations, you can join the discord if you want to ask questions.
