### ISSUE TITLE
Have Knights and Archers in training use bed

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#551]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

They moved from their old house to the facility, but they essentially do t use the bed nor require any sleep.

## Feature description

Have them actually use the bed at night like any other citizens.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
they *should* use the bed, if they don't it's a bug and goes on the bug repo
