### ISSUE TITLE
Permanently young children via data packs

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#554]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

I am always frustrated when I see kids eventually grow up and the teacher eventually have nothing to do.
Currently, you can only make it for children to grow slower.

## Feature description

I would like to suggest to basically make children to NEVER grow up, since this is obviously cheaty I think it should be available through data packs.

### Notes or related things

Children are adorable and it help spicing up the town for players, too bad they all eventually grow up.
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
iirc you can change the amount of time it takes for them to grow up in the config

**Comment by warning-djkajslh** [comment]
Oh I just meant that the config will not make it so that children stay young forever though, it only make it so children take longer to geow up.

**Comment by warning-djkajslh** [comment]
No idea why doesn't it show up in the description, as I clearly typed it it.

**Comment by warning-djkajslh** [comment]
Pls reopen? As I mentioned beforehand you can only make children mature slower and not having stay young forever.

**Comment by ravenbuilder934** [comment]
you can also make them not grow up by not letting them get food or sleep. outside of that i don't really see a use for this

**Comment by warning-djkajslh** [comment]
But not having any sleep should be easy, just set houses into manual assignment and unregister the children right?
Thereotically speaking, if you see them congregating at the townhall then it mean they don't get any sleep right? And do both foods and sleep requirements need to be met to stun their growth?

**Comment by ravenbuilder934** [comment]
> But not having any sleep should be easy, just set houses into manual assignment and unregister the children right? 

yep

> Thereotically speaking, if you see them congregating at the townhall then it mean they don't get any sleep right?

yep

> And do both foods and sleep requirements need to be met to stun their growth?

I'm not sure

**Comment by Sandriell** [comment]
I too would like to see this properly implemented. Just purely from an aesthetic stand point I would love to see lots of children running around my colony, it would make it feel much more real and immersive.
