### ISSUE TITLE
Decorational trap doors

### ISSUE THREAD

**Issue by Josbud1** [ldtteam/minecolonies-features#558]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:1.17.1
- MineColonies Version:minecolonies-1.17.1-1.0.84-ALPHA

## Is your feature request related to a problem?

I find it annoying that villagers always walk past trap doors that are a part of the decorations on a building and they open the trap door. This often results in the build looking worse and the now open trap door stop other villagers who will stand infront of it till they open it.

## Feature description

I think there should be a variant of the trapdoor that maybe the carpenter can craft that cannot be interacted with and is used in builds were the trapdoors don't have a functional purpose.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
In DO there are "panel" blocks, they look similar to trapdoors but don't do anything, usually used for walls but can also be used for fake trapdoors
