### ISSUE TITLE
Builder Range

### ISSUE THREAD

**Issue by Josbud1** [ldtteam/minecolonies-features#559]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:1.17.1
- MineColonies Version:minecolonies-1.17.1-1.0.84-ALPHA

## Feature description

Builders have a research tree that increases their break/placement range. Would allow builders to more efficiently build later in the game requiring less wasting time running back and forth to build.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You can try reducing the amount of running around that builders need to do by switching the iterator type (in the structurize config file, or later in the builder hut GUI after a certain research) to `hilbert` or `inwardcircleheight4`.   Changes will only affect newly-started builds, not any already in progress.

**Comment by Thodor12** [comment]
Also they already have a very long placement range to the point where it's almost unrealistic. You cannot grab something that is 5 metres away from you, why would the citizens be able to do so?
