### ISSUE TITLE
New resource scroll feature: The scroll glows when there is unsufficient materials

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#565]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

It might be hard when you're trying to manage between multiple scrolls and can't figure out which one is which, this suggestion is to solve that.
Sometimes the builder may even have missing materials when he accidentally knocked some of, light lanterns and torches and the build will be underconstructed for indefinitely

## Feature description

When the bound resource scroll detects that there are missing materials, it will emit an enchant tinted glow to alarm the player of the missing materials, the player can then right click on the scroll to see it for themselves.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
The resource scroll itself checks nothing actively. It only loads the contents of the linked builder if and when requested (GUI opened), putting this on a continuous check is not a good idea.
