### ISSUE TITLE
Optional Mod Integration: brining the END to the Colonies (literally)

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies-features#566]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: Irreliavant
- Related Mods and their Versions: also irrelivant

## Is your feature request related to a problem?

no
## Enhancement or Change description

I noticed that this mod has gone to lengths to include a variety of options to what theme your building can be and includes a nether themed option, so why not do the same with adding an end theme? why not have something end thened structures that can be built for those who wish to recreate a "end city" in the overworld, or some mad lads that might wanna try to take it to the extremes and make a colony in the end

### Notes or related things

it may not be as flashy, but mods like BetterEnd could be useful, the types of blocks in that mod and their logs are amazing and maybe some optional feature to show structures that rely on betterend blocks can become usable if the mods precese is detected within the pack, that way if they dont have the mod the structure style wont show up 
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
A style for this exists, it's called SpaceWars, it's based on a lot of end blocks.
As for mod dependencies, that's a no-go. We're not going to add arbitrary mod dependencies to be used with official styles, because that would make it so everyone has to download a mod specifically for SpaceWars to function.
