### ISSUE TITLE
Factory Hut: Interface between Minecolonies and machine mods

### ISSUE THREAD

**Issue by specklogan** [ldtteam/minecolonies-features#568]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.124-ALPHA

## Is your feature request related to a problem?
With certain modded machines there's no real interface between Minecolonies and that mod. There's no real way to teach a colonist to use that machine and to expect an output.

## Feature description
Similar to how you teach a sawmill to turn certain things into their products, you could teach this worker (perhaps industrialist), to drop certain items or input them into a chest/other storage devices, which could then be hoppered, or pulled using other mod pipes to be processed in the machine which they player would design themselves; the teaching of the recipe would involve telling of what would go in, and what would come out, and where it would come out at, this could be a wand that could be right-clicked at the beginning and ending where the worker could easily pick up.

### Notes or related things
The point of the building isn't meant to be custom fit to all machines across all mods, it's sort of a blank canvas that the player would have control over, with teachable recipes scaling up with the building size. 

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Going to close this because of balancing issues, this is "I'm gonna do it all" kind of suggestion, this feature would void all progression systems in the mod.
