### ISSUE TITLE
Feature suggestion: Shift right click a rack to another one to make it stay disconnect to each other.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#569]
Similar to vanilla chests which will join with each other unless you shift right click to place them.
The disconnected racks will still be seen by the building's schematic.
https://minecraft.fandom.com/wiki/Chest

The builder should recognize which racks are disconnected in their build as well.

**Comment by Thodor12** [comment]
Not using the issue template, plus there's no point for ever adding this since racks are just arbitrary inventory for the buildings workers, you still have the same amount of inventory space in the end
