### ISSUE TITLE
More perks for Patreon visitors

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#573]
### Prerequisites 

- [X] I am running the latest **alpha** version of MieColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [C] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem

Things to add for Patreon traveler

## Enhancement or Change description

First and foremost, have the Patreon visitors to always be a top-tier visitor, meaning they will always wear Diamond boots, or none at all since their unique story also reveal what they are good at.
Secondly, have the visitors to have an increase in some stats accordingly to their specialty, which is determined by their background story, such as:
A doctor - Healer stats
Swordfighter - Knight and Archer stats
A wanderer - Courier, farmer and fisherman stats
Finally, along with their own dialogue and recruiting item, they should also come with additional gears, such as swords or armors, the difference is that unlike other visitors, these gears will be retained once they are recruited. Have them break out of the boot ranking system for normal visitors and design their own set.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Currently special visitors don't have a lot going for them, they already lose their skins etc when hired.
This is probably something that has to be tackled, your suggestion however is something we're definitely not going to do.
If you start raising stats (making them better than default citizens) you start raising problems in the direction of pay to win, seeing as you can only get these by paying for the mod it's development.
This can cause issues on servers if one person has an army consisting of original patreon visitors with higher stats.
