### ISSUE TITLE
suggestion: lag reduction to AI like in AI improvments

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies-features#576]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: not relivant
- Related Mods and their Versions: not relivant

## Is your feature request related to a problem?

idk if this is the case but in the colony im makign with 170 mods, one issue that I noticed is that having alot of them is droping the FPS and i think it might have todo with the AI
## Enhancement or Change description

im aware of a mod called AI improvments whose goal is to reduce the LAG that can generate from lots of mobs being present and was wondering if it could be planned for a possable method to reduce the emount of lag the clolonist seems to be produceing , if thats possable that is

I love this mods idea and concept and im going quite well, only thing is that I think the AI is causing FPS issues and the known mods (Optifine, FPS reducer, AI improvments, eitc.) are present in this pack I put together, 
### Notes or related things

on an irrelivant note, I found that biomes where mobs dont normaly spawn like the mushroom isles is a great place to set up shop. not sure if that was expected or not, Just though I should let you know in here
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
AI is serverside, AI improvements mod is a shallow hull which does exactly nothing at this point
