### ISSUE TITLE
New worker: The Punisher and visitor farming

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#582]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

New meat drop fir citizens, visitors and raiders

## Feature description

New drop: Human meat, can be obtained from dying citizens, visitors, raiders, mercenaries and even players and villagers. Human meat can be cooked, it is as good as muttons. 
Despite this, citizens will treat human meat as a low tier food source, only eat them in dire times such as rotten flesh.
Children will also gladly consume humans when the urge strikes.
Eating too much human meats can make citizens go mad and need to be treated.
New worker: The punisher, the punisher is a butchering worker, the punisher will go out in the morning and make a visit to the tavern to slay any available visitors that appear using an axe, however, visitors are very barbaric and uncivilized individuals that will maul any attacker to death with a supernatural human strength, as a result, the punisher can use armor to protect themselves from the visitors.
You can decide which gender will be killed on sight, men or women.
The punisher will deposit any drops into their hut, any human meats will be stored in the warehouse or the restaurant to be consumed in later times, along side the visitor's bones, which can be crushed into bone meals.
When attacked by monsters, the punisher will retaliate but won't actually target monsters on their own initiative.

There are drawbacks of doing this, firstly, the Tavern is deemed "evil" and **no more** visitors will show up, ever.
Secondly, if you or the colony consume too much human meats, you will unlock a new raider, called the Wendigo, unlike other raiders, the Wendigo comes alone and without any structure, it is however, extremely powerful. The Wendigo will wreck havoc upon your colony, killing any citizens and turn them into its minions. A visit from the Wendigo will certainly leave your colony in shamble.

### Notes or related things
Don't worry, this suggestion isn't about citizens killing each other for meat, its about citizens killing the human-like animal that is the visitors for meat, sure, if a citizen dies, they will drop meats and get consumed by other citizens, but in no way would citizens purposely murder other citizens for this, consuming a fallen citizen's meats and bones only make sure that even in death, that citizen can still contribute to the growth of the colony.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by StrangerSon71** [comment]
No.

**Comment by pantsguyapp** [comment]
Yes

**Comment by DiamondCoder1000** [comment]
No

**Comment by Thodor12** [comment]
I'm gonna close this because of recent activity this popped up again, this is completely out of the scope of the mod and way too brutal compared to the rest of the mod.
