### ISSUE TITLE
Shulker box crafter

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#583]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

No crafter for normal shulker box

## Feature description

Some crafters for shulker box as well as dyeing them

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Dyeing could be solved by the dyer, but what's the point of having shulkers? The colony can't gather shells so why would they have to craft them?
If an end worker is ever considered or even made then this functionality is probably going to reside within them.
