### ISSUE TITLE
Add FTB Quests compatability

### ISSUE THREAD

**Issue by VampireTechnologyLord** [ldtteam/minecolonies-features#595]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:

## Is your feature request related to a problem?

No

## Feature description

I have been working on a modpack including Minecolonies and I was trying to do some Quests via FTB Quests, but sadly, there is no compatibility between these Mods.

Personally, I'd like to see the following things, but I'm sure there will be something useful 👍 :
 - A Quest Criteria for a number of citizens
 - A Quest Criteria for a total number of buildings levels (Housing 2 + Housing 1 would result in Housing 3)
 - A Quest Criteria for a maximum building level (Housing 2 + Housing 1 woud result in Housing 2)
 - A Quest Criteria for a number of Survived Raids
 - A Quest Criteria for a number of Citizens Died

### Notes or related things

Nothing else

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
This would be up to FTB, the minecolonies api is available

**Comment by Thodor12** [comment]
Out of the scope of our mod
