### ISSUE TITLE
Tavern should serve food

### ISSUE THREAD

**Issue by Larkas** [ldtteam/minecolonies-features#601]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.311-BETA
- Related Mods and their Versions: Structurize 0.13.254-ALPHA

## Is your feature request related to a problem?
By the time you build a restaurant and properly set it up, your citizens will be starving. The Tavern should ease the introduction of that system

## Enhancement or Change description
The Tavern should have a job slot (let's call it the Barkeep), and it should serve ready-made meals, such as bread, baked potatoes or cooked meats, for the colonists. It shouldn't, however, have the ability to MAKE such meals, nor the ability to serve raw food (though maybe you'd have a really small number of raw food slots to manually set up - I'm thinking maybe two at first level). At first, they should be supplied by the player. After that, however, you'd want to place huts that actually make those meals to automate the process a bit - such as the Bakery and maybe even the Restaurant.

### Notes or related things
Under such a system, the Restaurant wouldn't be strictly necessary. Having one, though, might give the colonists some bonuses (such as happiness, smaller chance of contracting diseases, etc.). By making this change, you'd have a somewhat functional colony with just three buildings (Town Hall, Builder and Tavern) and could branch out from that before having to build other obligatory huts. Do you want to get to mining and logging ASAP? Or would you rather set up the food supply chain (with Farm + Bakery or Cowhand + Restaurant) before getting down to that? It's your call, really, and it would make play more immediately rewarding.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
The purpose of the tavern is to provide 4 bedding slots and open up the colony to visitors. Having it serve food also would make the cook useless, this probably wont happen

**Comment by Maddremor** [comment]
Would a street vendor that can only distribute one or two food types with no ability to craft be an option? 
I guess the issue at hand is whether the distribution of food needs to be gated as much as the production of it. It might or might not.

**Comment by Moobien** [comment]
The devs wont add anything that will make existing things pointless

**Comment by SomewhatDamaged** [comment]
If the food distribution only applied to the 4 villagers living in the tavern, it wouldn't negate the restaurant.

**Comment by Moobien** [comment]
> If the food distribution only applied to the 4 villagers living in the tavern, it wouldn't negate the restaurant.

Still won't happen. The tavern's sole purpose is cheap easy starting housing
