### ISSUE TITLE
Add a Courier job slot to Warehouses

### ISSUE THREAD

**Issue by Larkas** [ldtteam/minecolonies-features#602]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.311-BETA
- Related Mods and their Versions: Structurize 0.13.254-ALPHA

## Is your feature request related to a problem?
The Warehouse is gated behind the Courier hut, and the Courier hut is useless without a Warehouse.

## Enhancement or Change description
Warehouses should have a single job slot for a Courier _itself_, so you could drop it and make it immediately productive. I could certainly see the Courier hut as an optional building so you can hire more than one courier for any given Warehouse. But gating the errand system behind the Courier hut isn't too great.

### Notes or related things
Currently, if you build the Courier hut first, you'll have an idle citizen until you finish building the Warehouse, and if you build the Warehouse first, you'll have a mostly idle Warehouse until you finish building the Courier hut and hire a courier to run errands.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Closing as this has become obsolete because of current warehouse functionality
