### ISSUE TITLE
Add Toolmakers!

### ISSUE THREAD

**Issue by Larkas** [ldtteam/minecolonies-features#603]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.311-BETA

## Is your feature request related to a problem?
Workers keep breaking their tools, and you have to build a University and a level 3 Mine before you can even research the Blacksmith hut to automate the process of making replacement tools. Until then, you have to manually make tools for your workers, which is pretty annoying.

## Feature description
I suggest adding in the Tool Shop and the Toolmaker. The Tool Shop would be a hut available as soon as you've built your a Builder, and it would hire Toolmakers that can make tools (and only tools - no swords) for your workers. At hut level 1, it would make wooden tools, at level 2 it would make stone tools, at level 3 it would make iron tools and at level 4 it would make diamond tools. But here's the catch: it can only be upgraded to level 3 AFTER a Blacksmith's placed in town, gating higher quality tools behind the tech tree. 

### Notes or related things
This would automate what I consider to be one of the most annoying aspects of early MineColonies play pretty early on, without making it unbalanced. For example, if you go Forester->Tool Shop, the toolmaker would supply the forester with the wooden axes they need to chop down trees, and the forester would supply the toolmaker with the wood needed to make wooden tools!

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
I can see benefit to this. Would need a minor rework of the blacksmith though

**Comment by AlmightyAnubis** [comment]
Would also be nice, if this hut could not improve the recipe. So if you want to save materials you still need the blacksmith

**Comment by Thodor12** [comment]
You actually missed a big point here, the tool maker would only craft tools, how do they get the sticks and planks? You still have no access to a sawmill, making the toolmaker pretty much useless anyway as they still cannot be automated.
The requirements for getting the sawmill are almost identical to the blacksmith (level 3 forester opposed to level 3 mine) so I see no benefit to this at all.

If you also need to add these special building construction conditions you're only adding technical debt into the mod, so with all this combined I'm gonna close this as a wontfix.
