### ISSUE TITLE
Midday break for citizens

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#619]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Citizens should make use of the afternoon and stockpile on their foods and happiness

## Feature description

- Citizens should have a chance to go on a break at noon. The citizen starts their break time by going to the restaurant for lunch, then they may decide to either go to the tavern for a drink or their home, or they can just use their time to meet each other and have a chat and socialize with other fellow citizens.
- Crafters should have a lower chance to go on a break since their job are just basically standing around and wait for materials.
- Intensive workers such as the couriers or the producers are more prone to go to chill in the tavern in preparation for the rest of the day.
- Citizens that mourn will not have a need to take a break midday as they has already on a break the entire morning.
- Guards who don't have a dedicated free time will have the highest requirement for a break midday.
- Lastly, midday breaks should be an option for players to choose when building their colony, as this will indeed lower the productivity of their colony. Happiness isn't going the be increased much at all, but the colony will become much more lively for the player to enjoy. Lunch breaks is an optional university research.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
With Minecraft it's day cycle not being very long, a short "break" in the middle of the day might take up the entire afternoon depending on how long the action is going to take. Remember the game doesn't use an actual 24h day cycle.
I think isn't something we want, but rather have off days which is planned in recreation/leisure.

Going to close this, feel free to reopen if you feel further change is required.
