### ISSUE TITLE
Firefighting

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#62]
## Feature description
Citizens would be able to extinguish fires using a bucket, the option for them to do so would be in the TH or the config (or possibly have a dedicated firefighter worker)

**Comment by ravenbuilder934** [comment]
Goes well with #63

**Comment by ShadowProtocol** [comment]
It does. But we are preferring to avoid interaction with fire (and griefing in general) so this is a wontfix.
