### ISSUE TITLE
Forester uses shears to collect leaf blocks option

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#632]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

No leaf automation yet.

## Feature description

Option that allow forester to make requests for shears instead on hoes to break leaf blocks.
Allow leaf collecting for the composter

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This is now possible as per ldtteam/minecolonies#8383
