### ISSUE TITLE
Deepslate cobble recipe for stone crusher

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#634]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:  1.18.1
- MineColonies Version:

## Is your feature request related to a problem?

Request a recipe for the stone crusher to make gravel out of deepslate cobble other mods like IE already has this built in
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SivartMcDorf** [comment]
wanted to add i have added this via datapack
Level 1 requires 2 deepslate just like the cobble version, I have also added a 1 cobble, 1 deepslate recipe to allow a mix
level 2 requires 1 deepslate just like the cobble version

**Comment by Legorfyr** [comment]
I support this, it's annoying for sifters/glassblowers.

**Comment by Moobien** [comment]
Already added
