### ISSUE TITLE
The ability to minumum stock/request Domum Ornamentum blocks

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#637]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

While constructing the quarry, the quarrier needs lots of Crossed timber cobblestone, and I would like to be able have the workers auto construct the blocks and deposit it for the quarrier to take out immediately, rather than waiting for manual requesting.
It is also frustrating that you cannot request for those blocks in the postbox

## Feature description

Minimum stock function and postbox request should have some unique GUI that can classify those blocks.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is already a thing.  Just have one of the block in your inventory and then you can request it at postbox and minimum stock.
