### ISSUE TITLE
sort the warehouses

### ISSUE THREAD

**Issue by laboriens** [ldtteam/minecolonies-features#643]
have a button in the warehouse to ask the courier to sort the warehouses and put them away, because I have the warehouse where items are in different chests while he has space and even some are not not even stack

**Comment by Talyda** [comment]
There's a button in the warehouse that you can press to sort. After level 3 I think
And when you start a new feature request, there's this whole template - please use it

**Comment by Thodor12** [comment]
Closed because this feature already exists
