### ISSUE TITLE
Solve version Chaos

### ISSUE THREAD

**Issue by Karlosbubi** [ldtteam/minecolonies-features#645]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ x ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.18.2
- MineColonies Version: 1.0.479-ALPHA
- Related Mods and their Versions: 
     - Structurize Version : 1.0.3.4.9-ALPHA
     - multi-piston Version : 1.2.3-ALPHA
     - blockui Version : 0.0.47-ALPHA
     - domum_ornamentum Version : 1.0.39-ALPHA

## Is your feature request related to a problem?

I'm always frustrated, when installing a fresh version or fresh Minecraft Instance, it is very hard for me to find the right Structurize version. Some might already have noticed, that the upper mentioned combination won't work, since i've just installed lastest version of both on curse, after i've tried the Version Recomended by Curse for Both. Now I'was loocking for the version specified as required in the log (1.0.347-ALPHA) and am unable to find it on Curse.

## Enhancement or Change description

I woul'd like for an easy way to match, if possible influence the Listing on curse, or provide an (easy to find) look up table !!With Download Links!! to the correct versions.

### Notes or related things

I am open to any improvement, since i am not involved in development and don't know how the current situation is linked to your Workflow.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Read the changelog

**Comment by Karlosbubi** [comment]
Curse dosen't normally show all the changelogs, only of the recomended version, but where this might be my own fault. 
There is still the problem of downloading the Exact required version, i need 1.0.**347**-ALPHA (structurize) and curse offers 1.0.**344**-BETA and 1.0.**350**-ALPHA, none in between like the one i need.

**Comment by Talyda** [comment]
You need to click the "view all" link at the top of the files list

**Comment by Karlosbubi** [comment]
How did i go YEARS without realizing this button exists :0. (Probably cause i didn't need it otherwise)

But it's still a nice enhancement to account for idiots like me.

**Comment by Talyda** [comment]
Because it is invisible until someone points it out to you! *nods seriously*
If you'd asked on discord before coming here we have a trick with a pre made message that we use to tell you that it is invisible 'til then too!

**Comment by Thodor12** [comment]
Closing as this is a workflow problem we're not going to solve.
This is just how the version releasing process works and we can't do much about it.
If something goes wrong the launcher will always complain saying it needs a specific structurize version, it's a bit annoying but unfortunately we can't do any better because of incompatability with dependent versions.
