### ISSUE TITLE
Market

### ISSUE THREAD

**Issue by TimLiz** [ldtteam/minecolonies-features#648]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 
- MineColonies Version: 

## Feature description
Market. Other colonies will be able to see what other colonies need and trade. For example, Colony A has a market, and it does not have enough stone, but at the same time a lot of planks. Colony B also has a market and its citizen are already asking for planks, but it has a lot of stone. As a result, market workers exchange.

This can also be done through lvl 5 of the town hall, which will make its improvement more useful.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Trading is planned
