### ISSUE TITLE
Crafter for Slime Blocks

### ISSUE THREAD

**Issue by SerranoPancake** [ldtteam/minecolonies-features#650]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.502-BETA

## Is your feature request related to a problem?

No workers can create slime blocks but some builds require them
## Feature description

Need a citizen that can make/breakdown slime blocks from/into slime balls.
### Notes or related things

Mechanic would be obvious choice since they already do honey blocks and will need slime for sticky pistons.
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Slime blocks can be crafted by mechanics
