### ISSUE TITLE
Great Wonder Structures

### ISSUE THREAD

**Issue by TrojanHorseForSale** [ldtteam/minecolonies-features#655]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.16.5-1.0.550-ALPHA.jar

**## Is your feature request related to a problem?** 
< No  -->

### ## Feature description
<! It would change the game up if Great Wonder style expensive buildings were introduced for mid to late game colonies that when built provide various buffs. You could have a coliseum wonder that when built makes all citizens more happy. A military academic that increases all soldiers strength. A Great Wall that slows down the advance of Barbarians. A Great Library that provides free research every few days. A Great temple that makes all citizens immune to disease/poison and slowly regen health. A great lighthouse which doubles all water based buildings production. These wonders could also require specific resources to be built. Also Allowing custom wonder schematics to be made and added would be great.     -->

**### Notes or related things**

**Comment by Moobien** [comment]
some styles already have megastructures, and the mystical site serves as the 'great wonder' of mincolonies

**Comment by TrojanHorseForSale** [comment]
> some styles already have megastructures, and the mystical site serves as the 'great wonder' of mincolonies

The wonders don't have to be great structures themselves but expensive to build. And having player decide between wonders to build would spice the replay ability of minecolonies.

**Comment by Moobien** [comment]
Don't forget, this is minecolonies, not age of empires.

**Comment by Moobien** [comment]
And it would be very time consuming for the builders, as we would have to stop all our current projects to go make these things.

**Comment by uecasm** [comment]
It is already possible for builders or anyone else to make additional Mystical Site structures in whatever size and cost is desired.  These already provide a happiness buff.  The other things are handled via research rather than structures.

If you have some particular building style in mind, you could perhaps try designing such a megastructure yourself and contribute it.

**Comment by TrojanHorseForSale** [comment]
> It is already possible for builders or anyone else to make additional Mystical Site structures in whatever size and cost is desired. These already provide a happiness buff. The other things are handled via research rather than structures.
> 
> If you have some particular building style in mind, you could perhaps try designing such a megastructure yourself and contribute it.

I suppose but the idea just seemed to fit in with minecolonies' essence.
