### ISSUE TITLE
New Builder/Worker: Merchant/Trader

### ISSUE THREAD

**Issue by NeptunesOrca** [ldtteam/minecolonies-features#656]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.541-ALPHA

## Is your feature request related to a problem?

No, unless a distinct lack of auto-trading is considered a problem.

## Feature description

Merchant worker (associated with a new building, called Caravansery, Market, Trading Post, or some other such related term). The Merchant would allow the player to automate trading with villagers in a certain fashion, and would attempt to find villagers nearby to trade with using items from their workstation. The player would need to be able to designate which items/trades the merchant is allowed to perform.

I have listed below a few options for your consideration that seem viable to me for what the implementation of this feature might look like, though these options are certainly not exhaustive, and will likely have issues in their implementation that I have not considered.

One method of accomplishing this might be via a two-phase system. The Merchant would spend a period of time to look for villagers, making a list of their trades, and then require the player to select which trades to make. With a list of allowed trades, Phase 2 would begin, and the Merchant would attempt to make as many of those allowed trades as possible until the next period they would attempt to look for new trades.

Alternatively, a list of all villager trades, or perhaps villager professions, could be listed in the Merchant's work station, and the player would select which trades should be made from the appropriate menu. The Merchant would then walk about looking for villagers with the appropriate trades.

### Notes or related things

Automated trading is rad-tastic, and it would be super cool if you could implement it. I do understand that it might be very difficult, however, so I completely understand if you don't think it's worthwhile. Thank you for your consideration.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
economy is already planned

**Comment by Thodor12** [comment]
Closed with above reason, trading and economy is planned
