### ISSUE TITLE
Guard coverage map

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#660]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
The ability to see what parts of your colony are covered by a guard tower so that you can look for holes in coverage, this will be handy when rearranging a town too.

## Feature description
Provide a simple toggle on the map integration to allow for this view maybe even a heat map to show where you have more than enough coverage like multiple overlaps.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
FWIW, you can use features in [colony4cc](https://github.com/uecasm/colony4cc/wiki#colonyhighlightbuildingpos-options-dir) to show this sort of thing as in-world overlays. 😁

**Comment by Thodor12** [comment]
With the additition of the town map (although this specific feature is not present) it should be easier to at least determine this.
