### ISSUE TITLE
More Brick Colours and Misc. Blocks

### ISSUE THREAD

**Issue by tundrarich** [ldtteam/minecolonies-features#662]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

No.

## Feature description

Introduction of new brick colours, similar to the beige, brown and cream colours.
For example, golden, orange and dark/black.

Glossy painted wood.

Furthermore ornate windows and other miscellaneous blocks that can help increase the amount of detail present in builds.

This list is very brief as I wished to see if the possibility was open first, before explaining with further details.

### Notes or related things

This request is presented as I wish if possible to introduce a new style of schematics to Minecolonies called "Scottish". Some buildings have been completed at Level 5 for personal use already such as citizen, dyer, florist ect. However some use accent blocks which simply do not exist yet or very specific colours which would greatly benefit the builds. Currently external mod blocks are being used, for example Create's Gabbro and Quark's Deepslate.

I have attached images of some of the buildings that are already completed so you can get a better idea of what the style entails.

Thank you for the consideration.

![Builder Storefront](https://user-images.githubusercontent.com/57719391/162646865-1584dfd2-4c24-448f-8541-97454ec24edf.png)
![Dyer or Tailer](https://user-images.githubusercontent.com/57719391/162646876-be909b9b-bb7b-44bd-9c21-f8dc8eb13e1d.png)
![Florist](https://user-images.githubusercontent.com/57719391/162646886-78d0b558-cb25-4d48-b5f0-4ba0f31b7b84.png)
![Hotel](https://user-images.githubusercontent.com/57719391/162646891-2706bb62-d56f-415e-aac3-c69e38c05397.png)
![Houses](https://user-images.githubusercontent.com/57719391/162646893-a910447d-dd54-4fda-8741-9cca8ea345f7.png)
![Inside Dyer](https://user-images.githubusercontent.com/57719391/162646903-411ef703-0855-4d58-9e6d-d5edb62430ca.png)
![Inside Florist](https://user-images.githubusercontent.com/57719391/162646907-3377db5e-b90d-498b-be11-48db34191278.png)
![Outside Grocers](https://user-images.githubusercontent.com/57719391/162646913-f08aa608-9126-492a-b6a1-8f91c81d3537.png)
![School](https://user-images.githubusercontent.com/57719391/162646926-0e72f636-7c56-49cb-8edc-c367c67bf33b.png)
![Sweet Shop](https://user-images.githubusercontent.com/57719391/162646933-b9368602-0b59-43de-b037-53cdafb1ea34.png)

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

---

**Comment by Thodor12** [comment]
There are new blocks in more recent versions.
However if you still feel like this is needed make an issue on the [Domum Ornamentum](https://github.com/ldtteam/Domum-Ornamentum) repository, that is where all these blocks are maintained.
