### ISSUE TITLE
Request for a demolitions expert to be added for a fun way of demolishing/destroying structures

### ISSUE THREAD

**Issue by Michael5156** [ldtteam/minecolonies-features#663]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.428-RELEASE

## Is your feature request related to a problem?
I was replacing an abandoned naturally generated structure (from minecolonies) with a new townhall, but I had a problem because structurize does not remove existing blocks. Was gonna go into the config files, or use worldedit to make the job easier but I thought a more fun way of doing this is getting a demolition team to "demolish" a build but sadly that does not exist so here I am : )

## Feature description
* A demolitionist is a new set of, or a singular entity which can be assigned the task of demolishing a structure.
* Their demolitions would be much faster than a player
* They stay in their own structure made largely of obsidian at lvl3 because I think that's funny.
* They can be called into a job with or without a demolitions hq 100 blocks from the player. Though calling them in will cause a delay of about 2400-4800 ticks. Once arriving in a horse, with a few donkeys with chests full of tnt and pickaxes, the demolitionist will follow the player to the task at hand or go directly to the bounding box mentioned below.

* To demolish a structure, the player has to set an A and B point which then encloses any structure (minecolonies or player made) within a bounding box. Whatever block is in the box will be demolished with an exception to bedrock.
* They will use tnt for builds that spans more than 20x by 20y blocks. Tnt explosions will not affect anything outside of the bounding box.
* They will use tnt for builds that spans more than 20x by 20y blocks. Tnt explosions will not affect anything outside of the bounding box.
* Everything will be autonomous. If a demo-man needs to cross a gap, they will use scaffolding.
* Their demolitions would be much faster than a player

* While the demolitions will be very fast, resources gathered from the process will be only an eighth to half of the amount of blocks/resources demolished.
* They will use tnt for builds that spans more than 20x by 20y blocks. Tnt explosions will not affect anything outside of the bounding box.

### Notes or related things
Would be cool if there's a rare chance for a demolitionist to use a demo-man skin from tf2

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Closed because this is planned ldtteam/minecolonies#4535 [Digger Worker]
