### ISSUE TITLE
Physical request board to replace the clipboard

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies-features#668]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.652-ALPHA.jar
- Related Mods and their Versions: N/A

## Is your feature request related to a problem?
N/A

## Enhancement or Change description
Currently the clipboard is responsible for keeping track of all requests in the colony it's attached to, personally I feel like this is a bit too powerful and takes away a bit of the management from the player side, making you less involved in the colony.

Instead of the clipboard I'd suggest an actual physical board you can place in your colony (either just craft and place or build tool), this would then serve the purpose of the clipboard and show all the requests when you click on it.

(Optionally) These boards would have a max range on them, so they would only log requests from buildings close enough to them.
(Optionally) Couriers could walk these boards if they don't have anything else to do in order to write the requests out (this is purely cinematic and wouldn't impact the function of the board)

### Notes or related things
N/A

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
If you downvote the issue at least comment on it to say *why* you don't like it.

**Comment by uecasm** [comment]
You can already use a computer monitor to display a request board in a single location if you want to do that.

Having a mobile version is still much more convenient, though, so that you can check what items you need to bring over while you're near your storage, double-check they're still needed when you're at the warehouse, or just keep an eye on anything gumming up while you're working on other projects.  And in general, people tend to request making even more things available in a portable format, not less.

**Comment by Thodor12** [comment]
Closed because the issue was not well received and after discussion turned into something else
