### ISSUE TITLE
New job - Item Classifier is needed

### ISSUE THREAD

**Issue by HexatomicRing** [ldtteam/minecolonies-features#671]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.2
- MineColonies Version: 1.0.662

## Feature description
Couriers cannot place some items into warehouse in order, such as flowers, wools and ores.  These items fill up almost every rack in the warehouse. To keep my warehouse in order, I have to spend a lot of time arranging these items, otherwise I will consume more time looking for items I need. (Making requests is not convenient for getting items wanted immediately.) This mechanical and repetitive work can be done by citizens. So I request a new job, maybe called item classifier, at warehouse. 

The work may not be simple. Classifiers should know which items can be placed into each slot in the racks, so new functions must be added to racks. . Players can toggle a rack that belongs to a warehouse into classified mode (I call them classified and unclassified racks below), then the rack will memorize the item type in each slot. Couriers must unload items into unclassified racks, and they prefere to get items from unclassified racks. Meanwhile, classifiers will check each slot in classified racks. If the slot is not filled  up, and there are items of the same type in unclassified racks, they will put these items into this slot. Classifiers do not need to check slots at a high frequency, but this will help save time for players. It is also helpful to save slots for warehouses.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You get a sort button at level 3, just press that every now and then

**Comment by HexatomicRing** [comment]
> You get a sort button at level 3, just press that every now and then

Well, I didn't notice this function and I tried it just now. This is very useful. Thank you!
