### ISSUE TITLE
[Feature Request]: "Warehouse Stock Only" Button for Composter Hut

### ISSUE THREAD

**Issue by SomewhatDamaged** [ldtteam/minecolonies-features#672]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.502

## Is your feature request related to a problem?
Composters requesting vast quantities of things that don't exist.

## Feature description
A check box in the Composter's Hut: "Warehouse Stock Only" so they could only draw from current stores and not needing-to-be-crafted crafted items.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This is already how composters work, it is controlled by the warehouse min stock. This is the amount of stacks of every items that should be present in the warehouse before items start being sent to the composter.
If they are constantly requesting all items it means you've likely set the min stock to 0.
Closing this issue.
