### ISSUE TITLE
NEW SUGGESTION: SHOPS

### ISSUE THREAD

**Issue by CaptainAhmed18** [ldtteam/minecolonies-features#674]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.709-ALPHA

## Is your feature request related to a problem?
No. It is a Feature Request.

## Feature description
Shops where Citizens, Visitors & Players would visit and buy anything they'd like and try some items before buying with Emeralds, etc..

### Notes or related things
They would come in Multiple Themes, Designs, Styles and more. E.G. Fish Shop, Gem Shop, Food Shop, etc... Couriers would deliver Items to/from Shops. They Will be open from Sunrise till Sunset Daily. Attempting to steal Items from Shops Without Paying will result in Guards Raiding stealers (Except for Players in Creative Mode).

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This is not gonna happen as economy is already a no-go, trading is planned but it is going to work in item-item trading.
There's not going to be a currency for balancing reasons (to not create another villager emerald problem).
