### ISSUE TITLE
The builders moves too much

### ISSUE THREAD

**Issue by ImEr1c** [ldtteam/minecolonies-features#676]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.750-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?

The builder moves from a place to another then it places 2-3 blocks and moves again
## Enhancement or Change description

It would be better if it didnt move that much because of time loss
### Notes or related things

I wanted to say Frequently not much in the title
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
First off, please fill in the template correctly.
Secondly, this provides no clear description of what is to be done at all, saying "the builder moves too much" is no clear explanation of an existing issue at all.

**Comment by ImEr1c** [comment]
Is it ok now? I wanted to say too frequently

**Comment by Thodor12** [comment]
This is likely just not going to happen, there's a maximum reach for a reason, arms don't stretch until infinity.

**Comment by MotionlessTrain** [comment]
There is a research, which lets you select other builder modes (orders of placement).
E.g "inwardcircle4" and "hilbert" are much more efficient than the default, in terms of walking distance between blocks

**Comment by batmanatorul** [comment]
ok, didn't know that, thnx, should I close this?

**Comment by ImEr1c** [comment]
Ok, didn't know that, should I close this?

**Comment by MotionlessTrain** [comment]
Yeah, since the enhancement has already been made some time ago
