### ISSUE TITLE
Let work order choose between multiple recipes for same item.

### ISSUE THREAD

**Issue by ArkenorOakshadow** [ldtteam/minecolonies-features#679]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.7850-ALPHA
- Related Mods and their Versions:

Expected Behaviour: If crafters have more than one recipe for the same thing, if they lack the ingredients for one of the recipes, they try the other one.

What actually happens: They pick one of the recipes, and if they lack the ingredients, they do not check the other, and instead bother the player.

What I would like to have happen: Is for them to try the different recipes until they find one they have the ingredients for, including if more than one crafter has a recipe for that product.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You can research "warehouse master". That gives you an extra option at the crafters, to craft based on warehouse stock.
So if don't pick the topmost recipe anymore, but the one for which there are the most items in the warehouse, which will be the second recipe in your example.

**Comment by ArkenorOakshadow** [comment]
Oh, that's what that does.

I really wish it was not gated behind research. It means that, for example, the datapack I'm working on breaks things until you get that research, which is clearly an unacceptable flaw for a datapack.

**Comment by MotionlessTrain** [comment]
You can change research in a datapack too. I'm not sure on what you can exactly change with that, but _maybe_ it is possible to make this not require research at all.

**Comment by ArkenorOakshadow** [comment]
That doesn't sound like something I want to have to regularly do to get datapacks to work, and is probably going to lead to more problems. My strong suggestion would be to do away with intentionally making recipe selection work in a non-intuitive way.
