### ISSUE TITLE
Miner

### ISSUE THREAD

**Issue by ImEr1c** [ldtteam/minecolonies-features#680]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 
- Related Mods and their Versions:

## Is your feature request related to a problem?

no
## Enhancement or Change description

Some kind of setting for the player to choose if the miner should use low tier pickaxes for mining and only use high tier like iron when needed (for mining diamonds, emeralds or whatever)
### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
There is not really a good definition for "low tier" though. For a large colony, iron may not be a problem at all, and may be classified as "low tier". For other colonies, iron is a constant struggle and would be considered "high tier"

**Comment by AlmightyAnubis** [comment]
Yeah, but setting a prefered pickaxe level would be nice. But you can use the minimum stock for that

**Comment by Thodor12** [comment]
This is indirectly already possible by using building minimum stock + there's a setting in the warehouse which can fullfill requests based on the amount of items in the warehouse.
So a request that can use any type of wood will be fullfilled with whatever type of wood, based on which items has the most amount of said item.
If any citizen doesn't have a high enough level of tool to complete their job they will ask for a new capable of the job anyway.
