### ISSUE TITLE
church, mosque

### ISSUE THREAD

**Issue by polikarpov5** [ldtteam/minecolonies-features#683]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

- Minecraft Version: 1.18.2
- MineColonies Version:minecolonies-1.18.2-1.0.768-BETA

## Is your feature request related to a problem?

Allows you to add an occupation during a death and add a building and a worker: the priest, bishop, Imam...

## Feature description
Add a religious building.
1: There is a death
2: the undertaker finds the dead man's body
3: he brings it to church
4: The locals go to church and pray
5: they go to the cemetery in procession.
6: They can resume their work

If there is no church or cemetery, the inhabitants pray for a whole day.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
Religion in some manner is already planned
