### ISSUE TITLE
Modrinth Release

### ISSUE THREAD

**Issue by wertercatt** [ldtteam/minecolonies-features#684]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: All
- MineColonies Version: All

## Is your feature request related to a problem?

CurseForge has been actively hostile to community launchers lately, and I've lost trust in them

## Feature description

Post mirrors of the Minecolonies modpack and mods/resourcepacks to the open source Minecraft modding directory Modrinth.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
There is currently no incentive for the mod to be moved into Modrinth, it *might* happen in the future but don't get your hopes up, for now closing this issue.

**Comment by SpiritOTHawk** [comment]
Maybe publishing mod both: modrinth and curseforge. It will help modpack devs.
