### ISSUE TITLE
Allows citizens to visit random mystical sites

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#687]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

Citizens only visit the first mystical sites placed down, even if there are a multiple of them in the colony.

## Enhancement or Change description

Allow each individual citizens to randomly roll for which site will they visit today.

### Notes or related things

Might want to do the same for other leisurable structures.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Closed in favor of ldtteam/minecolonies#4535 [Recreation]
