### ISSUE TITLE
Copper Plate Armor

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#694]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

no

## Feature description

a copper version of plate armour for archers that is lighter would be a great addition to Minecolonies to burn up some copper, along with possibly creating a few custom researchable weapons like a battle sword that does more damage that could use copper as an accent on it, or a copper accented bow.
copper potion holders for the alchemist and druids

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Please follow up on #694
