### ISSUE TITLE
map maker

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#695]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

no

## Feature description

map maker that makes maps to exotic locals and has a chance to find things like villages, shipwrecks, dungeons, mines, and stuff and create a map for you to that location, even a tiny opportunity for locating strongholds.  In their hut, have an area between 5x5 to 9x9 on the floor with frames that maps go in, and they will slowly populate though you could give maps to the mapmaker to fill them in faster as you explore as well.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Is this a request for a worker who does this as a sole job?
There is a new archeologist worker being implemented, even though he is not finalized it might be better to wait for that to release and see if this meets your needs, if not I'd make a new feature request afterwards.

Closing this for now but feel free to reopen if you want to continue this discussion.

**Comment by SivartMcDorf** [comment]
Well I don't know what the archaeologist would do but it could possibly be
added to that but the feature of creating a giant floor or wall map is a
unique idea that would be awesome to keep.  Essentially the builders would
include frames on the floor or wall with a tag in the middle of the field
and the minimum of 5x5 and max 9x9 and allow it to fill over time.  If that
fits in to the archaeologist job then great if not then a stand alone
adventure guide or cartographer job.
