### ISSUE TITLE
Improve the building upgrade process.

### ISSUE THREAD

**Issue by SeagalKru** [ldtteam/minecolonies-features#697]
- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

- Minecraft Version - 1.12.2:
- MineColonies Version - minecolonies-1.12.2-0.11.804-RELEASE-universal.jar:
- Related Mods and their Versions - _:

**Comment by MotionlessTrain** [comment]
1.12 is not supported anymore

And for a suggestion to be considered, it is necessary to provide more information than just "improve"

**Comment by SeagalKru** [comment]
I don't quite understand how to do it right, sorry! :-)
Can you help me put everything in its place?

(Google translation from Russian)

Hello!
I would like to ask you to finalize the mod in the following direction:
- I have a mod installed on my server that adds realism to torches - if the torch "falls" on a combustible block (boards, for example), then they light up.

This problem is almost 100% likely to occur when upgrading any building: when a builder replaces a block with a new one, then if there was a torch on it, it falls out and a fire occurs, which almost completely destroys the building and can spread to others if they are built nearby.

Knowing about this problem, I now have to remove all torches from the building before pressing the "Improve" button.

Teach the Builder how to do it yourself: when upgrading a building, remove all torches first and then upgrade the building!

Cool mod!
Thanks for your work!

**Comment by SeagalKru** [comment]
And all. I saw that 1.12.2 is no longer supported. It's a pity.
