### ISSUE TITLE
Forester saplings and crafting

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#703]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

I know minecolonies doesn't develop based on other mods, but many mods use crafted saplings for fruit tries.  It would be nice if the forester could first off craft the saplings.  Also, if they could recognize the trees properly and replace the correct saplings, many of the fruit trees use oak leaves and trunks so, which causes them to just replace them all with oak trees.  This could be accomplished with a quick scan of the leaves to realize there are fruits in the trees.

The second request is better support for the warped and crimson fungus, they can't be selected in the list of saplings.  I know I have had a forester cut them down and replace them, but it seems inconsistent.  

3rd it would be nice if they could properly cut and harvest chorus trees.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Chinthor** [comment]
A more basic improvement might be to detect "log on top of dirt, replace log with matching sapling" for every log, every time. If I planted dark oak or 2x2 jungle, replant the same, please. Or add a multiple sapling planting option at higher levels. I remember sequoia saplings planted 7x7 that were painful to automate. More advanced for modded trees, register EVERY block that a tree can spawn, and scan both up and down from ground level. Example is menril trees from Integrated Dynamics. They grow multiple log types depending on if the log contains resin or not. But the forester doesn't harvest them and stops harvesting normal logs if the resin logs are between him and them. Old IC2 rubber trees would have similar problem. Scanning down would be for trees like Thaumcraft's silverwood that sometimes have a root structure.

**Comment by MotionlessTrain** [comment]
> A more basic improvement might be to detect "log on top of dirt, replace log with matching sapling" for every log, every time. If I planted dark oak or 2x2 jungle, replant the same, please.
That is actually how the forester works, already

The largest issue with the saplings is that the tree is not an "object", which could be recognised by the forester. Rather, after a tree has been generated, it is just a selection of logs and leaves. There is no nice relation between those, and no good way to know which tree generated there (if it was a tree in the first place, and not some random logs with leaves on top). Hence the forester must examine the drops of the leaves to find out what sapling belonged to the tree (otherwise, the forester would not know whether he is cutting down an azalea tree or an oak tree, as they both have the same kind of logs).
The fruit trees of Pam's Harvestcraft drop vanilla saplings, not fruit saplings. Hence the forester cannot know it was a fruit tree.

**Comment by SivartMcDorf** [comment]
how about a tool to designate where to plant saplings, then even if it is a sapling from another mod then you could designate a space for it to be planted.  This could also be used for creating a tree farm so that if a forester had 3/4 dark oak saplings then later got a 4th could come back and plant the missing sapling.

**Comment by Thodor12** [comment]
If you are looking for better mod integration then add that as a comment to #135
