### ISSUE TITLE
Resurrections should have bonus

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#705]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:880

## Is your feature request related to a problem?

We lose time when citizens mourn the dead
## Feature description

citizens mourn when someone dies, and those same citizens that mourn should get a massive boost if that person is resurrected.  examples miner finds extra ore for three days, the fisherman has increased luck, forester finds double saplings... etc.  maybe better chance of reducing recipes, increased research, massive happiness boost, double saturation boost from foods
### Notes or related things

these are just ideas of what could be done as a bonus; since resurrections are rare and infrequent, I don't think this would be game-breaking and would be a nice reward for working on the cemetery.
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
The undertaker immediately attempts to revive the dead person after bringing them to the graveyard, so it's more likely that by the time he reaches the graveyard, the time has not passed into the next day yet and they will not have mourned yet.

The fact that the citizen has died and being brought back to life is already a "bonus" enough.
