### ISSUE TITLE
Natural colonies like villages?

### ISSUE THREAD

**Issue by Luke7381** [ldtteam/minecolonies-features#707]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

No
## Feature description
Can you add natural colonies that are already set up, with npcs in it? And if by choice players can claim the colony if they want. Im not sure if its possible due to how the mod works (you need claim a colony to even do stuff with it)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
There are already abandoned colonies in worldgen in 1.18.  If you claim one, it will start to attract colonists.

**Comment by Luke7381** [comment]
> 

Ik that what im talking about is colonies that already have NPCs in them, colonies that are active.

**Comment by Thodor12** [comment]
This is a planned feature
