### ISSUE TITLE
A way to highlight what block Builders are looking at

### ISSUE THREAD

**Issue by aaronhowser1** [ldtteam/minecolonies-features#709]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.2
- MineColonies Version: minecolonies-1.18.2-1.0.919-ALPHA

## Is your feature request related to a problem?

It can get very frustrating watching a Builder standing still in a building apparently doing nothing. It's scanning to make sure everything is placed correctly, but that isn't obvious. This is apparently enough of a problem that the Discord has a command for it.

## Feature description

An item or command or something to highlight the block a Builder is looking at, visible through blocks. This way we can see for sure that it isn't just sitting there doing nothing.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This would not be helpful at all, because they are not necessarily stuck on the building part, if they are looking for resources in their hut they are not necessarily "looking" at a block.
A better way would be different status updates /w images in their UI to give a basic indication of what they are doing.
