### ISSUE TITLE
Minecolonies + Ice and Fire

### ISSUE THREAD

**Issue by SidosX** [ldtteam/minecolonies-features#715]
Just got a little problem with Minecolonies and Ice and Fire.
The guards always want a "dread knight sword" (from ice and fire) but it isnt craftable.
my question is: is there a way to change the weapons they use to vanilla only or maybe add some new ones from other modpacks like spartan weaponary?

i couldnt find anything online or in the code to change that
currently im on version 1.16.5 but i dont think that matters

thank you and have a nice day!

**Comment by MotionlessTrain** [comment]
1.16.5 is not supported anymore

Besides, they ask for weapons with a range of materials (e.g. at least wood/gold, at max diamond), and that sword is just an example of one that fits the criteria
