### ISSUE TITLE
Have the rate of Patreon visitors adjustable in the config file

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#716]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

I want to have it so that special visitors completely replace normal visitors, but there is no easy way to do it, rather, I need to go into the mod's file and edit them one by one.

## Feature description

Have the rate for special visitors to appear available in the config {From 1 to 100).

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
That defeats the point of them being special visitors, and removes the flexibility of giving them different chances for different visitors, so this is not going to happen.
