### ISSUE TITLE
Patreon visitor should retain their player skin once hired

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#717]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

I don't like it that you can have special visitors but not colonists.

## Feature description

When recruited from the Tavern, the Patreon visitor will not change their skin before they join you.
You can have it so it is not a guarantee thing, but chance wise and can be capped, the chance is scale with the Tavern's level and there is no university research to increase this chance.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
They can't. Player models are not the same as citizen models.

**Comment by pantsguyapp** [comment]
But what if they do?

**Comment by Talyda** [comment]
Player models are different to citizen models.
Minecolonies citizens have a custom model (several custom models) they aren't the same as a player, therefore they can't wear the same skin.

**Comment by pantsguyapp** [comment]
Ah... So only visitors and unemployed citizens share the same model with the player?

**Comment by Talyda** [comment]
No, all Minecolonies citizens have custom models

**Comment by Thodor12** [comment]
This would be rather difficult as explained prior. The only way is by having patreon skins mapped on all possible worker models which would take a lot of work.
