### ISSUE TITLE
Add-On Support

### ISSUE THREAD

**Issue by Karlosbubi** [ldtteam/minecolonies-features#720]
### Prerequisites 

- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.405-BETA

## Is your feature request related to a problem?
No, it's not. (At least not directly)

## Feature description
Add-On Policy, Api and/or Turorial.
Under the lable "Compatibility: Mod" there are quite a few requests for Mod specific addons like an AE2 worker. And while it's certainly nice for users when common mods work out of the box, it's infeasable to support every combination mod side. Therefore it would be awesome to have a (more) straight forward Possibility to extend it for people themselves. Like the Datapacks which are already possible, but more powerful, and without the need to load them into every world for e.g. easier use in Modpacks. 

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The mod has an API for precisely that reason.
Also, 1.15.2 is not supported anymore

**Comment by Karlosbubi** [comment]
Nice, the i am sorry never mind, where would i find the Wikipage ??

Also i am aware of the latter that just happen to be my open modpack since the form made me feel obligated to give an answer.

**Comment by MotionlessTrain** [comment]
The only documentation is in the code (and javadoc) on GitHub:
https://github.com/ldtteam/minecolonies/tree/version/main/src/api

**Comment by Karlosbubi** [comment]
In the rare case i'll finish my plan i'll write up something like this, to make it more visible.
https://appliedenergistics.github.io/api
In the more likely case i won't let it inspire a kind soul. working on thier own addon.
