### ISSUE TITLE
Plantation

### ISSUE THREAD

**Issue by MarobsKoco** [ldtteam/minecolonies-features#722]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.2
- Forge: 40.1.84
- MineColonies Version: 1.0.1065

## Is your feature request related to a problem?
 the garged of the plantation is half empty

## Feature description
 Is it posible to let the Plantation just do the total garden, u have the choice of bamboo cactus and sugar cane. When u choose one, the planter always just use or kwart or half the garden, never the full garden. thats space wasted i would say. I would make it like: dose not matter what type u use, it always can use the full garden

### Notes or related things
 And thnx for this mod, i do like it alot.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![2022-10-18_18 45 05](https://user-images.githubusercontent.com/64714142/196492715-a1d3424d-bbc4-4e18-b8d9-78bf37f55ec6.png)
![2022-10-18_18 44 50](https://user-images.githubusercontent.com/64714142/196492745-8cabef36-f13d-4bec-bc7d-a4bf9f8680b6.png)

**Comment by MotionlessTrain** [comment]
That would mean all sand spots are eligible for all plants, which is definitely not always the case (sugarcane is often planted next to each other, next to water, but that won't work for cactuses)

**Comment by MarobsKoco** [comment]
thats true, cactusses cant be next to each other, but it could be made like in the back with the cactusses, that it would be like a checker pattern with water between them

**Comment by MotionlessTrain** [comment]
That would mean every single plantation in every style has to be redesigned

**Comment by MarobsKoco** [comment]
true, or they have to make it so that the pantation can do them all at the same time but with a helper, else it would be to much work for the planter alone, but 3 kwart garden empty is no sight, if the farmers did that in real lif they are realy stupid.

**Comment by MotionlessTrain** [comment]
There is a research such that they can do two of them

**Comment by MarobsKoco** [comment]
i didnt know that, becourse im not that far yet. but it still would be nice if they can use the full garden ofcourse.

**Comment by uecasm** [comment]
They can use the whole garden, you just need to periodically switch the types.  The types that aren't currently enabled will still be left to grow, as long as you switched it after they were planted but before they were harvested.  Then later you can switch types and they'll harvest and replant, then you can switch again.

**Comment by Thodor12** [comment]
Closing as this is "kind of" being worked on at the moment, but in a different way
