### ISSUE TITLE
fertilizer @ plantations

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies-features#724]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
if outside the tick range crops don't grow

## Feature description
currently the farmer uses fertilizer which will force grow crops even if the player is farther away than the tick range.  Plantations however do not benefit from this.  There are mods out there that make it so that cactus, bamboo, and other crops not normally affected by bonemeal are given this ability.  It would be possibly game breaking to give the player the ability to bonemeal these crops as that would allow bonemeal super tick autofarms, but if the npc's had this ability as farmers do then it would allow better effective use of the plantation.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
The old (and new) plantation will continue to utilize native mechanics to Minecraft, we're not going to introduce possibilities for plants to be grown outside of their natural way.
Adding bonemeal to the mix won't even solve the issue as the AI's are ticking entities too, AI's will always stop working when going out of range.
The "forceloadcolony" option can help with this by keeping the chunks loaded at all times, provided you are somewhere within the colony too.
