### ISSUE TITLE
jungle biome tree and building issues

### ISSUE THREAD

**Issue by cole333333** [ldtteam/minecolonies-features#725]
### Prerequisites 

- [x] I am running minecolonies-1.16.5-1.0.978-RELEASE.jar for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context minecolonies-1.16.5-1.0.978-RELEASE.jar

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.978
- Related Mods and their Versions:

## Is your feature request related to a problem?
when starting in a jungle the building blueprints are too large/expensive

## Enhancement or Change description
rather than costing stacks of logs and vines (they demand vines instead of jungle leaves for whatever reason) it may be better to have them demand 4 jungle saplings and to have them plant a large jungle tree instead, this could be done by having them place 4 saplings then having them appear to bonemeal the saplings for an arbitrary time then generating the desired tree structure. this will also fix their issue of attempting to place leaves that are not connected to logs and instantly having them disintegrate

### Notes or related things
in my own play through i was already out of starter food before i finished my builder hut and TH.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
1.16 is no longer supported. The schematics have been updated since then I believe.

**Comment by cole333333** [comment]
ahh oof
