### ISSUE TITLE
[Suggestion] Please add support for Dynmap

### ISSUE THREAD

**Issue by IceGoalie31** [ldtteam/minecolonies-features#728]
Please add support for Dynmap, something along the lines of the attached image. 
![image](https://user-images.githubusercontent.com/99508283/200681691-d1611411-803a-4194-8b74-7e6093af16c8.png) I have found documentation and they do have an API although I do not know how useful their documentation is, here are some links that might help. https://gist.github.com/JOO200/eb99b294ebd16a353750f83d8dcdce23 (all the API documentation I could find. Note: was given to me on their discord server.) https://github.com/webbukkit/dynmap/wiki/Using-markers#area-markers (Might help with getting the area markers for the colony borders.)
Note: Dynmap is different from JourneyMap as it is targeted towards servers I believe. This is because it runs in a web browser without needing to have the Minecraft client open. It also allows Isometric map viewing.
Link to Dynmap Forge Version: https://www.curseforge.com/minecraft/mc-mods/dynmapforge

Thanks.

**Comment by Thodor12** [comment]
I'll go ahead and look into this, this could be a useful optional plugin to have.
One question, can you tell from your Dynmap if DO blocks (like the shingles etc) are already able to render correctly?
Would help me narrow the scope of the MR a bit.

**Comment by IceGoalie31** [comment]
It appears that it ignores shingles. I have a screenshot, the circles show where shingles should be: 
![image](https://user-images.githubusercontent.com/99508283/200854301-347b092c-8027-4395-827a-12256788e603.png)
Dynmap does have stuff on their wiki page about custom blocks although I do not know exactly what you are looking for: https://github.com/webbukkit/dynmap/wiki/Custom-Block-Definitions
There are more things in the table of contents at the bottom under "Mod Support"
