### ISSUE TITLE
Feature Request: Cultivator

### ISSUE THREAD

**Issue by f1vetails** [ldtteam/minecolonies-features#729]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.0.1106-ALPHA

## Is your feature request related to a problem?

I always want to see more buildings, and help add things to the mod that do not exist, since Kelp is needed to restore a sickness, and coral is hard to obtain, and could be used in buildings (along with sea grass) it would be nice to have a way for colonists to get these items.

## Feature description

*So the building would be the Cultivator: This building will make Kelp, Seagrass, and Corals (in a similar fashion to the flower shop.) It is a coastal building, that has 
*Composted dirt 12x per level (like the plantation.) 4 each for Corals kelp and sea grass, and uses compost to make/plant these items.

*Similarly it would be locked behind research, like the plantation.
*It should also have compost barrels and a furnace in its build (to make dried Kelp as a craft, and bundle it)

*The research would be 64 Kelp.

I've enclosed an image of the level 5 building built in my style (High Magic):
![2022-11-13_12 41 41](https://user-images.githubusercontent.com/118127957/201539391-daf15b6e-6d6d-43a5-b518-fef96904df89.png)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I think this is already planned/being worked on?  I have faint memory!

**Comment by Thodor12** [comment]
This will be part of the plantation in the future.
