### ISSUE TITLE
Add "e" to the keybinds that can close the mod's UIs

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies-features#730]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: ColonyVenture-1.13.zip
- Related Mods and their Versions:

## Is your feature request related to a problem?

Annoying to have to switch over to Esc to close GUIs when am used to using E in most such UIs

## Enhancement or Change description

small QOL perk request
Make "E" close the clipboard, hut GUIs, resource scrolls. I use E to open/close inventory and E gets me out of chests for instance. Annoying to have to switch over to Esc for the mentioned items.
A note, existing inv mods handle it fine, if focus is in a textbox it is ignored. Will add.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
"E" is the inventory key (by default, which I always change because it's silly) and only opens/closes inventories, which most of the mcol GUIs are not.  So it is entirely inappropriate to bind E for that purpose.
