### ISSUE TITLE
Minimum stock feature enhancement for bigger efficiency of couriers and workers

### ISSUE THREAD

**Issue by ManosB** [ldtteam/minecolonies-features#733]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

When you set minimum stock to a worker couriers will have to fill it up as soon as the worker use the item/s from the stock.
## Enhancement or Change description

The suggestion is adding the feature of maximum stock alongside with the minimum stock in huts, so when a worker requests items cause of his already set minimum stock(stock<minimum), couriers will give him enough items to reach the maximum stock. This way the couriers will have to do less trips between the warehouse and the worker's station since while the number of items is between the minimum and maximum stock(minimum<stock<maximum) no items will be ordered. That will lead to a more efficient way of management and also needing less couriers especially in endgame. The feature can also be unlocked via a research in the university. 
### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The MOQ research is available in both 1.18 and 1.19 now, which implements something sufficiently similar to this.
