### ISSUE TITLE
Expanded Statistics

### ISSUE THREAD

**Issue by EricTurner3** [ldtteam/minecolonies-features#737]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: Forge 1.19.2
- MineColonies Version: 1.19.2-1.0.1122-ALPHA

## Is your feature request related to a problem?
No

## Feature description
In the town hall, you can see basic statistics of your colony. I think it would be cool to expand on this idea.

My idea was that each building block would get a new tab for statistics. It would look like the requests menu except instead be an output of the total # of items that building has performed.

For example the restaurant block could have a list of 200 cooked cod indicating since it was built it has cooked 200 cod.

The miner could have 15 raw iron, 30 diamond, 1520 cobblestone to indicate all the blocks they have mined.

So on and so forth for the remaining buildings and their respective output (or even things used as input such as coal or seeds).

I think it would be useful to see which buildings are your top performers that handle the most requests. 

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
We have something like this available now, it doesn't contain the *exact* things you put as examples but the main idea is there.
