### ISSUE TITLE
New command for managing in-progress research of colonies.

### ISSUE THREAD

**Issue by anthony-benavente** [ldtteam/minecolonies-features#743]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.19.2-1.0.1149-ALPHA.jar

## Is your feature request related to a problem?

I run a fairly popular private Minecraft server with MineColonies on it and have wanted a way to complete research for people in the server as an OP. Having a command for this would be a great way for me to do this as well as potentially making a reward system for the users in the server.

## Feature description

The new feature would be a new command that allows OPs to view, complete and cancel research in their colony from the command line. Example of this would be the following commands:

 * `/minecolonies colony research {colonyId} list`
 * `/minecolonies colony research {colonyId} complete {researchId}`
 * `/minecolonies colony research {colonyId} cancel {researchId}`

### Notes or related things

I whipped up a little bit of code that implements this feature quickly if you're interested in seeing how I solved it within your codebase.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Unless I'm misinterpreting your meaning of "complete", this set of commands makes no sense.

You have a complete action to instantly complete a research, a cancel to stop a research, but what about starting a research?
It seems more like you are looking for a way to complete a research only, and that the cancel functionality can go away, in it's current state this one doesn't look useful at all.

As for the list, it would depend highly on the implementation if this is useful, as you may know there are a *lot* of different researches, adding them into a list wouldn't be the best looking and might have you scrolling through pages over and over to find the correct one.

Re-think about the implementation of the commands and add how you think these commands would function (what would they output, etc), the issue is incomplete as of right now.

**Comment by uecasm** [comment]
I think "cancel" was meant in the sense of "uncomplete"/"undo"/"remove".  i.e. remove an already-completed research.  That's not inconsistent.

Having said that, I don't really see the point in having these commands.  As an op in creative mode you can already visit their university and trigger the research almost instantly -- provided they gave you permission first, or you use commands to override the permissions.  Or you can just `/give` them the resources to start the research themselves.  And this avoids complications with dependent research and level requirements.

**Comment by anthony-benavente** [comment]
@Thodor12 The purpose of the commands were more of a means to manage in-progress research. And yes, you are correct about me really being after the completion aspect of the command since the usefulness for me would come from being able to finish other players' research without having to switch to creative and tp. In addition, it would be nice to be able to run these from the server console so I don't even have to be logged into the game.

So overall I guess my vision for this implementation would be something like the following commands.

 - `/mc colony research <colonyId> list` - To see what research is in progress so we can choose which one should be completed. 
 - `/mc colony research <colonyId> complete <researchId>` - To actually complete the research

Here's an image of what I'd expect the output would be. Note: It would be formatted better, and I would probably remove the estimated time, I just had it there for debugging reasons for now and I didn't feel like compiling for another 5-7 minutes.

![image](https://user-images.githubusercontent.com/12239350/212367856-b0889ae9-c5e4-4c30-8ca0-a4e19f2b92df.png)

**Comment by Thodor12** [comment]
I'm going to agree with Mirality here, this is already possible through numerous ways.
Just ask the others to add you as an officer into the colony and complete the researches for them, alternatively give them the resources to be able to complete it.
