### ISSUE TITLE
Roman Architecture 

### ISSUE THREAD

**Issue by JapaneseWeasel** [ldtteam/minecolonies-features#744]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 
minecolonies-1.16.5-1.0.978-RELEASE

## Is your feature request related to a problem?
No

## Feature description
I would like to see another style of building added to the game, which is roman architecture. Thing with lots of pillars, and diorite maybe. 

### Notes or related things
N/A

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
There is currently a byzantine style in the works by one of our builders, however this won't appear back in 1.16.5 anyway as this version has gone unsupported.
Version 1.17 and above introduced a new mod called Domum Ornamentum which introduces these pillars etc you are talking about.
So this style will only appear in 1.18 and above.
