### ISSUE TITLE
My request is about mine hut. I think its very inefficiency, because while the miner is digging he builds much structure while digging it, and it slows the process very much. Other thing is the nodes and the hole is very big for a one miner, so i thing solution is increasing the miner amount for the mine huts. I think 3 at the end of upgrading would be the best but i hope you guys evaluate my opinion.

### ISSUE THREAD

**Issue by metoozen** [ldtteam/minecolonies-features#745]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Multiple workers in many huts have always been denied so far.

Also fill in the issue template correctly next time.
