### ISSUE TITLE
Colony weapon variety (Matchlock Ranged Firearms)

### ISSUE THREAD

**Issue by Mr-Artillery** [ldtteam/minecolonies-features#746]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context

- Minecraft Version: 1.19.3
- MineColonies Version: N/a

## Is your feature request related to a problem?
Yes, primarily with ranged combat, due to the lack of ranged weapon variety and I've seen no addon mods that add in certain weaponry that would suit an 18th-century Colony (Normal colony without reskins). While providing a fairly powerful but balanced weapon that could generate some interesting battles

## Feature description
 Essentially, It's a ranged Musket with/or Bayonet as a mid-to-end-game weapon that is meant for Mid-range to long-range engagement, while being fairly balanced with long reload times and inaccuracy (Smoothbore Musket). Colonists can be hired as the "Marksmen" Profession at guard towers.

Tech tree:
**Gunpowder Matchlocks** (Unlocks matchlock pistol, short-range combat, unlocks early game defense)
**Smoothbore Musket** (Unlocks Musket, Mid to short-range combat)
Rifled Musket (Unlocks a Sharpshooter variant with increased range and Accuracy)
**Bayonet** (Attachment to the Musket, allowing for close-quarter combat if a hostile player/mob gets too close!)
Breechloading Upgrade (Significantly Reduced reload time)

### Notes or related things
To make things balanced, I would suggest making the Matchlock NPC-only weapons, so players can't abuse the Musket's damage output 

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
We specifically have knights and archers, separate guard types.
We're not going to introduce a "one does it all" kind of weapon.

Not to mention that making a standalone weapon doesn't actually do anything, because separate guard types will utilize different weapons.

That being said there are plans for axe bearers, horseback riding and possibly crossbowmen.

**Comment by Thodor12** [comment]
Ray confirmed on stream that this is not within the current scope of the mod/minecraft
