### ISSUE TITLE
Delay for children spawning

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#75]
Suggestion from Discord

## Feature description
> I seem to be having an issue where people are not getting beds before kids are born.
I have 2 people that are not able to get beds and hanging in the Townhall. When I build or upgrade a citizen hut, a kid is born before they claim the bed.

> yeah - I think there should be a delay before a new child is born - probably over night 
> so that you have the day to finish building and assigning citizens to homes
(https://discord.com/channels/139070364159311872/620499986349555742/722142866952159242)

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by PowerSchill** [comment]
Kids do spawn during the day in the current builds

**Comment by ravenbuilder934** [comment]
This was a suggestion that they should only spawn in the very early morning (or maybe at night). They should *not* spawn during the day (unless both their parents are unemployed and don't have anything to do).

**Comment by PowerSchill** [comment]
That wouldn't work on servers though since most people won't let the night happen.

**Comment by ravenbuilder934** [comment]
> very early morning

or could just do morning.

**Comment by PowerSchill** [comment]
Do you remember the details of the request?

**Comment by ravenbuilder934** [comment]
Just that discord link. It makes sense though, because how do parents make kids if they're working and not near each other?

**Comment by PowerSchill** [comment]
Well we won't go into the fact that they are sharing the house with up to three other adults and not necessarily staying in the same room as their partner. :) or that genetically they could be descended from the same four colonists.

**Comment by ravenbuilder934** [comment]
Why'd you close this?

**Comment by Raycoms** [comment]
Because it was already implemented to some degree
