### ISSUE TITLE
Make Fields and Quarries available in the build menu for ALL styles.

### ISSUE THREAD

**Issue by TwilightSparkleHonkers** [ldtteam/minecolonies-features#752]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.0.1247-BETA
- Related Mods and their Versions: -

## Is your feature request related to a problem?

**I was very frustrated that some essential buildings such as the Quarry and Field are hidden away in the default Mine Colonies style. They are not visible at all in the build menu in any other style. Placing down a quarry block without the build menu will not work either, you HAVE to know that the quarry is in the default style, and switch to it. This is *very* confusing and unintruitive for new players.**

![image](https://user-images.githubusercontent.com/38990462/220728659-e1662a24-1e09-4a4b-8b1f-3ef8cdc8be02.png)

![image](https://user-images.githubusercontent.com/38990462/220729458-510b0714-c583-4625-ba26-09b1f9769b7e.png)

This is my first playthrough with this mod, and I took a lot of time and frustration to find those essential buildings. If I hadn't seen a letsplay featuring them, I wouldn't even have known they were separate buildings honestly. I was in voice chat with friends, all of them also new to the mod, and between the 4 of us no one directly found the solution. One thought that the quarry/field weren't separate buildings, and you just had to put the field block in the middle of your own farmland. Another one thought it was just a bug or that those buildings weren't present in alpha versions. We didn't find anything helpful online or in the official wiki, but after well over 20 minutes of headscratching we eventually figured it out...

I understand that not every building is available in every style, especially when it comes to decoration, roads, etc. But _**fields and quarries are not just cosmetic, they are essential**_ for some professions to work, and any colony in any style could need them at some point. Even if the building is the same across all styles (because a field will always just look like a field), _**it should be available in the build menu for all styles of colonies.**_

## Enhancement or Change description

Either make variants of quarry and fields for all styles (high effort), or make the current field and quarry buildings available in the menu for all styles.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This is up to style pack designers, we have no hard control over what style designers put and don't put in their packs, not even the core buildings.

Edit: The field is also not even a building, all you have to do is place down a field block, set it's plant and go from there.

**Comment by TwilightSparkleHonkers** [comment]
> This is up to style pack designers, we have no hard control over what style designers put and don't put in their packs, not even the core buildings.

Can't you make it so that when an important building isn't in a style pack, the default building is in the menu instead ? I don't care that there isn't a quarry in my colony style, I just wished that there was a quarry at all in the menu

**Comment by Talyda** [comment]
Hold quarry block in your hand, right click the air, it tells you where to find them.
There's not really any "default" building
(same method for fields)

Also, sorry, another edit, fields as you mean them are not essentials, the items itself is essential, the "fields" you are talking about are decorative. You just need the field item. You can hoe earth around it for them to farm in. You absolutely can (and I usually do) "put the field block in the middle of your own farmland" =)
And personally I never use the quarry, really dislike it, so I would argue that isn't essential either, but that is semantics ;)
