### ISSUE TITLE
Possible "Anti-Waypoints" Implementation

### ISSUE THREAD

**Issue by BoundingAsp1559** [ldtteam/minecolonies-features#753]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I This request is a "duplicate" of a request from ***4 Years Ago***, but also provides a possible solution/implementation

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.0.1247

## Feature description
"Anti-Waypoints" Implementation. Adding a Tool to the Town Hall that behaves similarly to the Patrol Tool from a Guard House,  allowing the Player to see/place/remove these "Anti-Waypoints" to prevent Colonists from walking into dangerous areas such as Mob Grinders/Factories or simply walking off a cliff...

**Comment by Talyda** [comment]
Already suggested here =) You can add anything there you can think of! 
https://github.com/ldtteam/minecolonies-features/issues/42

**Comment by Thodor12** [comment]
Duplicate
