### ISSUE TITLE
Black banner not working for nordic buildings

### ISSUE THREAD

**Issue by finntenzor** [ldtteam/minecolonies-features#754]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.12.2
- MineColonies Version: minecolonies-1.12.2-0.11.841-ALPHA-universal
- Related Mods and their Versions: MCEternal

## Is your feature request related to a problem?

Related issue: https://github.com/ldtteam/minecolonies/issues/4597

Black banner with below NBT is not accepted:
```
{BlockEntityTag: {Patterns: [{Pattern: "tts", Color: 11}, {Pattern: "bts", Color: 11}, {Pattern: "mr", Color: 11}, {Pattern: "mc", Color: 1}]}}
```

However, black banners with below NBT are accepted:
```
{BlockEntityTag: {Patterns: [{Pattern: "tts", Color: 11}, {Pattern: "bts", Color: 11}, {Pattern: "mc", Color: 11}, {Pattern: "mr", Color: 11}, {Pattern: "mc", Color: 1}]}}
```

**So, the invisible red circle under the red circle prevent players to upgrade their Town Hall to level 4.** This is not a programming bug, but an architectural bug. 

## Enhancement or Change description

Maybe it would be a good idea to update the way these flags are made. Since there are still a lot of players playing 1.12, this update may not require a code change.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
1.12.2 is not supported anymore
