### ISSUE TITLE
[Suggestion] Build tool remembers previously selected structure

### ISSUE THREAD

**Issue by MarioSMB** [ldtteam/minecolonies-features#755]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.18.2
- MineColonies Version: 1.0.966-RELEASE
- Related Mods and their Versions: Structurize 1.0.424-ALPHA

## Is your feature request related to a problem?
It is a tad frustrating to have the build tool re-open a massive quarry structure whenever I right-click a block!

## Enhancement or Change description
It would be nice if the build tool would remember the previously selected structure when starting to make a new one. This would make building larger structures out of multiple pieces much easier, thanks!

### Notes or related things
Apologies if this has been reported before - I couldn't find anything similar with a quick search.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This has been improved in 1.19 with the build tool rework. This won't be backported to 1.18

**Comment by MarioSMB** [comment]
I see, thanks for the heads up.
