### ISSUE TITLE
Dynmap support for 1.19.2

### ISSUE THREAD

**Issue by militaryk** [ldtteam/minecolonies-features#757]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.0.1262-ALPHA

## Is your feature request related to a problem?

I am involved in developing and running a server and would like to implement Minecolonies with Dynamap, the implementation has already been completed for 1.18 versions but is not implemented for 1.19 versions. An implementation for 1.19.2 would be quite useful.

## Feature description

"Ability to render borders of colonies on Dynmap using a new marker set "Colonies". Renders the colony name, owner and population count on the description of the colony. Automatically updates Dynmap when the following occur: The colony name gets changed The colony it's team color is changed The colony borders change when a building is constructured/repaired/removed The colony it's population count changes, either when colonists are born or die."
**As per https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/4239144**

### Notes or related things

Minecolonies file where Dynmap was already implemented for 1.18.2 https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/4239144

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This still needs to be done, after publishing the Dynmap for 1.18.2 I haven't tested it live yet, so the migration to 1.19.2 has never happened yet.

**Comment by samuelh2005** [comment]
I would love to see 1.20.x as well.

**Comment by Thodor12** [comment]
This will soon be ready, yesterday required code for this to work was merged into Minecolonies.
So I will be able to actually provide a release version for an addon mod [Dynmap for Minecolonies](https://legacy.curseforge.com/minecraft/mc-mods/dynmap-for-minecolonies) (currently invisible because no release candidiates have been made, but will soon be available)

**Comment by Thodor12** [comment]
This mod has now been released!
