### ISSUE TITLE
[Feature request] Any Mod compatibility building

### ISSUE THREAD

**Issue by tabr** [ldtteam/minecolonies-features#758]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version:1.19.2-1.0.1287-ALPHA

## Is your feature request related to a problem?

There are some mods that can be integrated with a simple way... i think

## Feature description

A construction with name MOD_COMPATIBILITY_BUILDING that has 3 zones:
1) input chest zone
2) output chest zone
3) some clear zone where player can place things from other mod, an [electric furnace], [crusher], [coal electric generator]. Zone because can be multiblock.
4) Upgrades can be:
4.1) Only input
4.2) Input and output
4.3) 2 x input and 1 x output
4.4) ..
4.5)  (with a little bigger zone at each level?)
5) Exp can grow for time of crafting.
6) Research as last level of tech tree
So player can make a scheme with pipes and other that can convert one items to another.
in MOD_COMPATIBILITY_BUILDING block would be settings where player can select [how many and which items ] would be converted to [other num of items ]. Somethin like this have AE2 mod.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
You are talking about experience, but what would a worker even do in this building if the whole point of it is to be automated?
We cannot code in that the worker is supposed to add items into slots into different machines.

**Comment by Thodor12** [comment]
> 4.5) (with a little bigger zone at each level?)

Not going to happen, schematics should not change in size

**Comment by tabr** [comment]
> You are talking about experience, but what would a worker even do in this building if the whole point of it is to be automated? We cannot code in that the worker is supposed to add items into slots into different machines.

Worker would be transfer items from racks to input zones, and get the back from output.

**Comment by tabr** [comment]
> > 4.5) (with a little bigger zone at each level?)
> 
> Not going to happen, schematics should not change in size

![image](https://user-images.githubusercontent.com/683886/225451642-0c913808-9e26-4ae6-bcc8-2b26c5317e71.png)
not all schematics, just "zone". If it is possible, of course.

**Comment by Thodor12** [comment]
I'm not really a big fan of this.

The worker would essentially just be a glorified courier, at which point I don't think he'd even be needed anymore.
It is outside the scope of the mod, we focus on Minecolonies, not having it work with every single mod out there.

I can't think of a single scenario where the colony needs all these machines in order to make blocks that the colony needs.
Do remember that these buildings exist to serve a purpose within the colony, not serve a purpose to autocraft things for you. (There are much better setups that achieve this for you)

**Comment by Talyda** [comment]
Would be better as an addon mod adding a new worker =) Wouldn't do anything at all if you didn't have mods to use it, so a great deal of people wouldn't have any use for it. And that aside, you can't make a worker for mods that you have no control over.

**Comment by Thodor12** [comment]
> Would be better as an addon mod adding a new worker =) Wouldn't do anything at all if you didn't have mods to use it, so a great deal of people wouldn't have any use for it. And that aside, you can't make a worker for mods that you have no control over.

The way he invisioned it is that you have I/O chests, which are piped outside of, into machines, back into the output chest, so the worker wouldn't touch any of the systems inside the zone.

**Comment by Talyda** [comment]
Still, would have no purpose at all for a great deal of players. As you said, outside of scope. What would be the point of putting all that work into a worker, when it has no use!

**Comment by tabr** [comment]
> 

There is mod "FarmersDelight" that have own block to pre-cook some food. Crops from this mod Farmer can grow, some food can be crafted, but some can't.
After mekanism's digital miner resources become almost infinite. Also there is refined obsidian armor, tools and weapons, that use colonists and can be crafted by colony. But ingots i must craft by myself, because infusing :(
Steel too...
Can be Nuclear reactor that need a fuel.(here would be nice if player can set armor requirements)
Also it is fun to automate this=)
AE(or any other) tube trough whole city not quite a good idea, couriers is better=) For electricity  immersive engineering has a good wires.
The worker can be removed, of course. I just suggested how he can be used. If he need, you can give him a wrench and he may "fix" some mechanisms... Or he can switch a lever or button with redstone signal, to turn on/off the machine. If he need, of course.
But maybe crafttweaker can close some questions...

**Comment by Thodor12** [comment]
Regardless, this is already flagged as Add-on, we are not going to make this because with solely Minecolonies installed (which is the standpoint we make on new features), this addition will have no benefit to us at all, because it solely relies on interaction with other mods.

If you want this, it will come down to doing it yourself or finding someone who will.
