### ISSUE TITLE
Search Function for Finding Specific Buildings Across Packs

### ISSUE THREAD

**Issue by pyromartian** [ldtteam/minecolonies-features#761]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:1.19.2
- MineColonies Version:1.0.1371-ALPHA

## Is your feature request related to a problem?
Yes, it is related to the problem of not being able to easily find specific buildings in all packs due to different packs containing different buildings.

## Feature description
I would like to request a string search function to search through all packs to find specific buildings. This feature would enable users to search for a specific building, even if it is not included in the specific pack they are using. This would be particularly useful for buildings such as bridges which may not be included in all packs. The string search function would search through all available packs to find the specific building requested.

### Notes or related things
Thank you for considering my feature request. Please let me know if you need any additional information or clarification.
Edit: This would be mainly used for decorations as hutblocks already have a list of all the styles that have that building, and which section of the build tool they are in.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
If you right click a hut block in the air, it opens an interface with all schematics of that building in all styles

**Comment by Thodor12** [comment]
Closing because this is already possible
