### ISSUE TITLE
integration for mrcrayfish's gun mod where guards use guns

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ldtteam/minecolonies-features#771]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Enhancement or Change description
 it would be nice to make it so guards use guns from mrcrayfish's gun mod

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Mojang is bound to ban firearms from servers, with this in mind support for those kind of mods is definitely not going to happen.
On top of that, previously we've already denied the request for firearms mods to be supported.

**Comment by SonicTheHedgehog58987276** [comment]
that will definitely fail for mojang, they probably don't understand their own game

**Comment by SonicTheHedgehog58987276** [comment]
destroy gtm!

**Comment by SonicTheHedgehog58987276** [comment]
Eliminate Gtm!

**Comment by Thodor12** [comment]
I don't care if it will fail or not, we still have to comply by these rules. If Minecraft wishes not to have firearms portrayed in their game, then we shall not do so.
We've also repeatedly in the past chosen not to do anything with this mod anyway because it does not fit the aim for the mod.

**Comment by Thodor12** [comment]
If you really want to make, then I'd say make an addon mod yourself where you do it, because we aren't going to.

**Comment by SonicTheHedgehog58987276** [comment]
i do not know how to mod other than mcreator

**Comment by SonicTheHedgehog58987276** [comment]
i will need to request to someone else.
