### ISSUE TITLE
Qusstion / Feature request ( Minecraft 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [ldtteam/minecolonies-features#782]
Do colonies ( all buildings and all villagers ) generate naturally ? If no, could You add it ?

**Comment by Thodor12** [comment]
1.12.2 is not supported for ages anymore. We only support 1.19.2 and 1.20.1 currently, only versions from 1.18.2 and beyond have worldgen colonies (although not occupied with citizens).
Full AI colonies are planned for the future.
