### ISSUE TITLE
Buildings status item

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#79]
Suggestion from Discord

## Feature description
> Creating some tool that shows you all your colony buildings, along with it's level and even the worker/inhabitant. I was trying to find out which one of my citizen huts needed upgrade and I had to go and click on each one to check, and upgrade if needed. This tool may even be able to issue upgrade commands straight from it's GUI.
(https://discord.com/channels/139070364159311872/240841248750043137/725469975896129608)

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Why Wontfix?

**Comment by Thodor12** [comment]
Doesn't need to be a tool, all these different tools make usage only more and more difficult, just put this in the townhall (make a new issue if none exist)
