### ISSUE TITLE
Direct building an higher Level of Buildings

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies-features#790]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: -
- MineColonies Version: -

## Is your feature request related to a problem?
Nup

## Feature description
Please ad an Option, witch allows the Builder to build directly higher Tears of Buildings (without being in Creative, of curse).
I find it relay annoying, especial in later game, that i always have to tear up new Buildings stepp by stepp to the Level i ant them.
As max Level of "direct Building" i suggest the current Level of the Townhall. Individual Upgrading should of Course stay possible.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Requested and denied in the past, progression is part of the mod

**Comment by ghost** [comment]
Just to make sure, i'am was understood correctly:
I am not asking of "removing the Progression" (there is the Creative for).
I am just asking vor "i have an Tear 5 Builder and want to build an second Tear 5 Farm. Then i want the Builder to Build direcly the Tear 5 Farm. I do not want to have to go trough all 5 Tears, just to Build the Second one."
If the fear is, that you might "rush to upgrade the Townhall", for skipping the Progression on Buildings... well, this is understandable.
But this can be Fixt be making sour to have at least one Building of the curent Typ at the desired Tear.

**Comment by Thodor12** [comment]
This is exactly what everyone has been suggesting, by allowing to upgrade buildings directly through the levels in any way you bypass "natural progression", even if you require an existing building at the level to do so. This has been denied and will continue to be denied.

**Comment by ghost** [comment]
Hum... Sad.
And for me at least, not understandable (why is this an bypassing, if have to first progress to an Point X...).
But this  is something we have to accept then.
Thank you.

**Comment by Thodor12** [comment]
By mod design we require that each building must level on it's own, mostly because upgrading buildings brings with them additional benefits.

It's supposed to take effort to upgrade buildings, if you plop down a level 5 immediately you skip all of the upgrading, and gathering earlier materials.

Schematics usually change over time (e.x. wood -> stone -> etc), by going immediately to the last level all of this prior material gathering will not be taken into consideration.

**Comment by ghost** [comment]
I can see that, but do not shear the position.
And this okay, because i can understand it :)
