### ISSUE TITLE
Warehouse's search function should be on the first place

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies-features#792]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

Manually clicking on the chest icon everytime you want to search something can get a tideous overtime.

## Enhancement or Change description

It will be much more convenient to put the search function of the warehouse to be on the first place, considered it is the mostly used function for the warehouse, so that people can just open up the warehouse and quickly locate the things they wnt.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MarioSMB** [comment]
I would also like to add that the chest icon is not very intuitive in a GUI full of text buttons (especially one next to a text button for Inventory) - it took me a while to find out that I could click the chest, which is not good considering this is such an important functionality of the warehouse.

**Comment by Thodor12** [comment]
We aren't going to make specific GUI's like that for any building, the default landing page is the same for all worker huts and the same for housing options.

It's better to focus on accessibility and making it clear *how* to access the inventory.

**Comment by MarioSMB** [comment]
Hopefully those accessibility plans include making it more obvious that a random chest icon is a button to such a vital menu.
