### ISSUE TITLE
Button to Switch Recipe Output when Teaching Colonist

### ISSUE THREAD

**Issue by manosrules** [ldtteam/minecolonies-features#808]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.0.1247 (atm8 version 1.0.14)

## Is your feature request related to a problem?

I want to teach my farmer how to turn grapes into grape seeds, but the result is always purple dye, even when using JEI to try to place the recipe for grape seeds into the farmer's crafting recipe ui.

## Feature description

If a recipe has multiple outputs, add a button or key bind to allow switching of the resulting recipe. Similar to the button that appears when the player is using a crafting table and there are multiple results for the same recipe.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
That would become a custom button, unfortunately.
It looks like Polymorph (the mod that adds the button to the regular crafting table) is made in a way it isn't really possible to make an addon to it to add the same button to other crafting interfaces (like the teach recipe menu)

**Comment by manosrules** [comment]
Ok. If the new button is out, is there a possibility cycling through multiple outputs using something on the keyboard, like scrolling with a mouse wheel?
