### ISSUE TITLE
Way to distinguish between multiple rallying banners

### ISSUE THREAD

**Issue by rsnow** [ldtteam/minecolonies-features#812]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.20.1
- MineColonies Version: 395-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?

No issue with gameplay

## Enhancement or Change description

Some method to distinguish between multiple rallying banners in inventory.  Currently they are the same color and nametags do not work on them, so you cannot tell them apart except for tower counts.  If you could recolor or name the banner it would help greatly for those of us who use more than one banner.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by rsnow** [comment]
Currently, the only way I've found is to have different number of towers attached to each banner, seems being able to use a nametag or color them would be really useful for those of us who use more than one rally banner because sometimes I have to fight multiple raiders group because sometimes I'm solo (family server, kids have school)

**Comment by MotionlessTrain** [comment]
You should be able to name them
Any item can be (re)named in an anvil (not just name tags)

**Comment by rsnow** [comment]
I'm a dumbass.  Closing.
