### ISSUE TITLE
chat ai?

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ldtteam/minecolonies-features#824]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [ ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SonicTheHedgehog58987276** [comment]
i wish i could talk to my citizens!

**Comment by Thodor12** [comment]
Requested and denied before, AIs are for a large part out of our control and we don't want to be responsible if they start cursing thanks to bad actors their input.

**Comment by SonicTheHedgehog58987276** [comment]
could you just make them not curse?

**Comment by MotionlessTrain** [comment]
There is no way to say exactly to an AI what they aren't allowed to say, or which subject should be skipped. 
AI has had that issue before a few times in other cases, where they e.g. accidentally started discriminating, which took quite some work for the companies using the AI to get that right

**Comment by SonicTheHedgehog58987276** [comment]
is minecolonies for all ages or what age do you recommend?

**Comment by Talyda** [comment]
Minecraft is 10+

**Comment by Thodor12** [comment]
This is non negotiable, AI cannot be controlled.
