### ISSUE TITLE
Is it possible to put back Blockminingdelaymodifier and Builderbuildblockdelay in server-configs

### ISSUE THREAD

**Issue by rorp24** [ldtteam/minecolonies-features#832]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.20.1
- MineColonies Version: 1.1.536-BETA
- Related Mods and their Versions:

## Is your feature request related to a problem?

Waiting for builder to break and place blocks can be really exausting, expecially when we do builds like caverns. In previous editions of the mod, it was possible to speed builders up with `Blockminingdelaymodifier` and `Builderbuildblockdelay`, but those options aren't here anymore.

## Enhancement or Change description

put back `Blockminingdelaymodifier` and `Builderbuildblockdelay` in config (and BTW the code that interact with them) so it is possible to change builder's building and breaking speed.

### Notes or related things

If you can't put them back in, can you at least explain why you removed it in the first place ?

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This was intentionally removed because it was being wrongfully used. We have intention of even adding this back.
Level up your builders their stats and do research to increase their speed, that's the only way we will support.
