### ISSUE TITLE
Different NPC skins based on style of TownHall

### ISSUE THREAD

**Issue by Mariozah21** [ldtteam/minecolonies-features#838]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.20.1
- MineColonies Version: 1.1.567-BETA

## Is your feature request related to a problem?
No my feature is not related to any problem.

## Feature description
When a player choses to build a certain style for example Nordic (Vikings) the  npc skins could change to fit that style more. Or if a player choses the undeground one the npcs could be dwarves so it feels more imersive. 

### Notes or related things
Also if it would be possible it would be nice if along with that the warriors would want to use different weapons based on the style of the TH (or guard tower). So dwarves would want a pickaxe, nordic would want an axe... etc.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Citizen skins do exist, however they are a Patreon only feature.
