### ISSUE TITLE
Request to create saperate armour slots for citizens and allow to wear modded armours for minecolonies version 1.12.2

### ISSUE THREAD

**Issue by RonitNarkhede** [ldtteam/minecolonies-features#844]
- Minecraft Version: 1.12.2
- MineColonies Version:1.12.2

I was playing minecolonies mod of version 1.12.2 and I was playing others mods too such as AHZNB Naruto mod, AHZNB Naruto addon, Kabuto addon, AHZNB boruto expansion,  Naruto mod addon and biblocraft. There are many armours in the AHZNB mod such as konoha's ninja jacket, leggings, slippers and armours of other villages so, I want that the npc's or citizen's should have seperate slots or inventory for armours and allow them to wear the armours of other mods such as AHZNB Naruto mod and AHZNB Boruto expansion addon etc. can you please add it

**Comment by RonitNarkhede** [comment]
And also allow them to use the weapons from the other mods of Minecraft instead of allowing them to use only vannila weapons

**Comment by Thodor12** [comment]
1.12.2 is not supported anymore. The only supported versions are 1.19.2 and 1.20.1 at the moment.
