### ISSUE TITLE
Request for creating new project 

### ISSUE THREAD

**Issue by RonitNarkhede** [ldtteam/minecolonies-features#848]
So, I was playing this mod with the mod called ninshu origins of Minecraft 1.19.2 which was pretty interesting and ossome but, while playing, i had got an idea of creating a mod same as minecolonies for Naruto lovers in which, we can create our Villages like shown in anime and manga. We would get same citizens as we got in minecolonies mod with additional options as ninja. In which, we can enroll him to ninja accademy where he can learn, grow, find and make some cool jutsus etc. and once they grown up, we can give them missions based on their ranks and we can keep chunin exams to promote them as chunins and also same for jonins level . the other villages except from the village we selected start developing themselves through npc's and it would become a lot intresting if we add war system in it. I mean that we can attack the other villages for example i create leaf village then, other other villages such as mist, sand, stone, clod village can attack on us and we can attack on them too . This would make this mod a much more interesting 

So, this was my idea or opinion for creating the same mod as minecolonies but in Naruto edition. 
I hope you will like my idea and take some action on it and helpe me to create such mod 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.19.2

**Comment by Thodor12** [comment]
This is going to be completely out of scope for the project.
You can fork Minecolonies and modify it to your hearts content by changing citizen skins, names, guard roles, whatever you desire.
