### ISSUE TITLE
Block names and job names should be separate keys

### ISSUE THREAD

**Issue by momo-i2** [ldtteam/minecolonies-features#865]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.21.1
- MineColonies Version: 1.1.802
- Related Mods and their Versions:

## Is your feature request related to a problem?

There is only one translation for "Sifter", and I think the job and the block name are the same.

## Enhancement or Change description

Sifter is a different word for a person and an object in Japanese, so please separate them.

### Notes or related things

This may be the case here too, but the discussion on Crowdin is not very active, and even when I send a request on each translation page, I get no response.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
- `"com.minecolonies.building.sifter": "Sifter"`, ->Building name
- `"com.minecolonies.job.sifter": "Sifter",` -> Job name
- `"block.minecolonies.blockhutsifter": "Sifter",`* -> Block name

**Comment by momo-i2** [comment]
> * `"com.minecolonies.building.sifter": "Sifter"`, ->Building name
com.minecolonies.building.sifter.desc found, but above one not found
> * `"com.minecolonies.job.sifter": "Sifter",` -> Job name
Can't find it anywhere.
> * `"block.minecolonies.blockhutsifter": "Sifter",`* -> Block name
com.minecolonies.coremod.job.sifter found, but above one not found

Where can I find those translations on Crowdin, I've looked for that 3 files but can only find existing ones?

I'm wondering if this is the same phenomenon as item.minecolonies.mint_tea where the keys are implemented but Crowdin doesn't reflect them.

**Comment by Thodor12** [comment]
I can't quite explain why they're not showing up in crowdin honestly. They're in the source file, they're even already translated according to the output files. I just don't see them in crowdin directly.

The current translations are:
```json
"com.minecolonies.building.sifter": "選鉱師",
"com.minecolonies.job.sifter": "選鉱師",
"block.minecolonies.blockhutsifter": "選鉱師",
```

As for mint tea, it seems no translation key was made for it at all.
