### ISSUE TITLE
Create Mod Train Compat

### ISSUE THREAD

**Issue by iSeeEthan** [ldtteam/minecolonies-features#868]
### Feature Request: Create Mod Train Compat

---  
name: Feature Request - Create Mod Train Compat
about: Add functionality to enable MineColonies NPCs to use trains for faster travel between stations.  
title: "Train Passenger Boarding System"  
labels: 'Feature: Request'  
assignees: ''  

---  

### Prerequisites  

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.  
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.  
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**  

### Context  

- Minecraft Version: 1.21.1+
- MineColonies Version: 1.1.815+

## Is your feature request related to a problem?  
It can be frustrating to watch NPCs walk long distances between workstations or destinations when more efficient transportation options like Create mod trains.

## Feature Description  

Introduce a new **MineColonies Station Block** that can be placed under a station (compatible with Create). The block would function as follows:  
- If there are **seats** available on a nearby train at the station, NPCs will board the train when traveling between stations equipped with the same Train Station Block.  
- NPCs will only choose this travel method if it offers a quicker route compared to walking.  
- The block could integrate with pathfinding, checking the train route's estimated travel time.  
- Upon arriving at their destination, NPCs disembark and continue to their intended task or destination as normal.  

This system would make colonies more efficient and allow for the creation of advanced infrastructure.  

### Implementation Details  
1. Add a MineColonies Station Block with the following attributes:  
   - Recognizes trains stopped at the station with available seats.  
   - Interfaces with MineColonies NPC pathfinding to calculate optimal routes.  
2. Extend NPC AI to evaluate travel methods (walking vs. train).  
3. Optionally, provide an interface for customizing train station routes or preferences for certain NPC types.  

### Notes or Related Things  
- Integration with the Create mod adds a layer of automation to MineColonies.  
- This feature would greatly enhance the gameplay experience, especially for larger colonies.

**Comment by Thodor12** [comment]
#135

**Comment by Gerpus** [comment]
Hello, as I understand it, you have abandoned this function?

**Comment by LuckyLMJ** [comment]
It is very unfortunate that this is not planned. I really wanted to have a server with my friends where I could build a metro system using create mod trains and my friend to build a minecolonies village where the villagers will use the metro.

**Comment by MotionlessTrain** [comment]
This was closed, as there is another issue to keep track of mod compat feature requests

And secondly, if you know a good way to tell citizens to wait for something during pathfinding, rather than choosing a direct way to go there, to effectively use a route planner to get there, using a timetable that doesn’t really exist, and to tell citizens which of the trains arriving at a station is actually a passenger train, and not a freight train, it might be possible. But some of those things I listed are actually problems outside of minecolonies as well (I haven’t find the perfect public transport route planner myself yet)
