### ISSUE TITLE
Battle formations for guards

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#87]
Suggestion from Discord

## Feature description
See the conversation in the messages before and after: https://discord.com/channels/139070364159311872/240841248750043137/724611123160285185

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ShadowProtocol** [comment]
Closing this, because there is little description of implementation in the Discord conversation, and this may be fixed to an acceptable standard by #86. If someone wants to make a more involved suggestion after that feature has been implemented, then they may do so in a new issue.
