### ISSUE TITLE
Increased build speed for practiced builders

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#92]
Suggestion from Discord

### Expected behavior

- Dynamic builder build speed based on level of the building being built
- Builders can build huts faster if they have built them before
- https://discord.com/channels/139070364159311872/240841248750043137/723228853534720057

#### Specifications

- See the Discord conversation for any given details. Continue the discussion here.

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Ah okay, we have wontfix
=D

**Comment by ravenbuilder934** [comment]
Why wontfix?

**Comment by Raycoms** [comment]
I will close this, because we have already an experience and leveling system for that, would be kinda duplicate then

**Comment by ravenbuilder934** [comment]
**Wontfix**

**Comment by Raycoms** [comment]
We have to close some things too, else we'll have 100s of pages. things that don't make any sense get closed
